### PR TITLE
[test] Rerun libxml2

### PR DESCRIPTION
**Pull request by NancyLi1013**
llibxml2 failed on osx pipeline in the PR #10770 

```
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _xmlIconvWrapper in libxml2.a(encoding.c.o)
  "_iconv_close", referenced from:
      _xmlFindCharEncodingHandler in libxml2.a(encoding.c.o)
      _xmlCharEncCloseFunc in libxml2.a(encoding.c.o)
  "_iconv_open", referenced from:
      _xmlFindCharEncodingHandler in libxml2.a(encoding.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I checked the CMakeLists.txt and found that iconv has been linked. And I also cannot reproduce this on my local. 

Related issue #11001.

### CODE REVIEW

**Comment by Neumann-A** [comment]
Not libxml2 is failing. The port cmake is failing as a depent of libxml2 since it does not know that libxml2 has been linked with iconv. The vcpkg-cmake-wrapper needs to be adjusted to reflect that libxml2 has been build with iconv. This is already done for Windows but not for osx. Just take a look into libxml2 vcpkg-cmake-wrapper and you should directly see it

**Comment by NancyLi1013** [comment]
Thanks for your update. 
I understood it now. It is about the usage of libxml2. Will add the dependency later.

**Comment by NancyLi1013** [comment]
After further investigation about this, it seems that this is not a bug for libxml2. So I close this PR now.
