### PR TITLE
[xbyak] update to 7.30

### PR DESCRIPTION
**Pull request by toge**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

https://github.com/herumi/xbyak/releases/tag/v7.30

### CODE REVIEW

**Comment by BillyONeal** [comment]
Appear to be legitimate compilation failures due to xbyak templated comparison operators:

```console
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(417): error C2666: 'ov::reference::jit::RegistersPool::Reg<Xbyak::Reg64>::operator +': overloaded functions have similar conversions
D:\installed\x64-windows\include\xbyak/xbyak.h(1081): note: could be 'Xbyak::RegExp Xbyak::operator +(const Xbyak::RegExp &,const Xbyak::RegExp &)' [found using argument-dependent lookup]
D:\installed\x64-windows\include\xbyak/xbyak.h(1116): note: or       'Xbyak::RegExp Xbyak::operator +(const Xbyak::RegExp &,size_t)' [found using argument-dependent lookup]
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\reference\include\openvino/reference/utils/registers_pool.hpp(61): note: or       'Xbyak::RegExp ov::reference::jit::RegistersPool::Reg<Xbyak::Reg64>::operator +(const ov::reference::jit::RegistersPool::Reg<Xbyak::Reg64> &,const Xbyak::RegExp &)' [found using argument-dependent lookup]
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(417): note: while trying to match the argument list '(ov::reference::jit::RegistersPool::Reg<Xbyak::Reg64>, const size_t)'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(417): error C7732: expected an expression before ']'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(417): error C2679: binary '[': no operator found which takes a right-hand operand of type 'int' (or there is no acceptable conversion)
D:\installed\x64-windows\include\xbyak/xbyak.h(1445): note: could be 'Xbyak::Address Xbyak::AddressFrame::operator [](const Xbyak::RegExp &) const'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(417): note: 'Xbyak::Address Xbyak::AddressFrame::operator [](const Xbyak::RegExp &) const': cannot convert argument 2 from 'int' to 'const Xbyak::RegExp &'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(417): note: Reason: cannot convert from 'int' to 'const Xbyak::RegExp'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(417): note: 'Xbyak::RegExp::RegExp': ambiguous call to overloaded function
D:\installed\x64-windows\include\xbyak/xbyak.h(1015): note: could be 'Xbyak::RegExp::RegExp(const void *)'
D:\installed\x64-windows\include\xbyak/xbyak.h(995): note: or       'Xbyak::RegExp::RegExp(size_t)'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(417): note: while trying to match the argument list '(int)'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(417): note: while trying to match the argument list '(const Xbyak::AddressFrame, int)'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(417): error C2660: 'ov::runtime::jit::ComputeHash<ov::reference::jit::avx512_core>::uni_vbroadcasti64x2': function does not take 1 arguments
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(209): note: see declaration of 'ov::runtime::jit::ComputeHash<ov::reference::jit::avx512_core>::uni_vbroadcasti64x2'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(417): note: while trying to match the argument list '(ov::reference::jit::RegistersPool::Reg<Xbyak::Zmm>)'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(419): error C2666: 'ov::reference::jit::RegistersPool::Reg<Xbyak::Reg64>::operator +': overloaded functions have similar conversions
D:\installed\x64-windows\include\xbyak/xbyak.h(1081): note: could be 'Xbyak::RegExp Xbyak::operator +(const Xbyak::RegExp &,const Xbyak::RegExp &)' [found using argument-dependent lookup]
D:\installed\x64-windows\include\xbyak/xbyak.h(1116): note: or       'Xbyak::RegExp Xbyak::operator +(const Xbyak::RegExp &,size_t)' [found using argument-dependent lookup]
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\reference\include\openvino/reference/utils/registers_pool.hpp(61): note: or       'Xbyak::RegExp ov::reference::jit::RegistersPool::Reg<Xbyak::Reg64>::operator +(const ov::reference::jit::RegistersPool::Reg<Xbyak::Reg64> &,const Xbyak::RegExp &)' [found using argument-dependent lookup]
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(419): note: while trying to match the argument list '(ov::reference::jit::RegistersPool::Reg<Xbyak::Reg64>, const size_t)'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(419): error C7732: expected an expression before ']'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(419): error C2679: binary '[': no operator found which takes a right-hand operand of type 'int' (or there is no acceptable conversion)
D:\installed\x64-windows\include\xbyak/xbyak.h(1445): note: could be 'Xbyak::Address Xbyak::AddressFrame::operator [](const Xbyak::RegExp &) const'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(419): note: 'Xbyak::Address Xbyak::AddressFrame::operator [](const Xbyak::RegExp &) const': cannot convert argument 2 from 'int' to 'const Xbyak::RegExp &'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(419): note: Reason: cannot convert from 'int' to 'const Xbyak::RegExp'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(419): note: 'Xbyak::RegExp::RegExp': ambiguous call to overloaded function
D:\installed\x64-windows\include\xbyak/xbyak.h(1015): note: could be 'Xbyak::RegExp::RegExp(const void *)'
D:\installed\x64-windows\include\xbyak/xbyak.h(995): note: or       'Xbyak::RegExp::RegExp(size_t)'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(419): note: while trying to match the argument list '(int)'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(419): note: while trying to match the argument list '(const Xbyak::AddressFrame, int)'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(419): error C2660: 'ov::runtime::jit::ComputeHash<ov::reference::jit::avx512_core>::uni_vbroadcasti64x2': function does not take 1 arguments
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(209): note: see declaration of 'ov::runtime::jit::ComputeHash<ov::reference::jit::avx512_core>::uni_vbroadcasti64x2'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(419): note: while trying to match the argument list '(ov::reference::jit::RegistersPool::Reg<Xbyak::Zmm>)'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(503): error C2666: 'ov::reference::jit::RegistersPool::Reg<Xbyak::Reg64>::operator +': overloaded functions have similar conversions
D:\installed\x64-windows\include\xbyak/xbyak.h(1081): note: could be 'Xbyak::RegExp Xbyak::operator +(const Xbyak::RegExp &,const Xbyak::RegExp &)' [found using argument-dependent lookup]
D:\installed\x64-windows\include\xbyak/xbyak.h(1116): note: or       'Xbyak::RegExp Xbyak::operator +(const Xbyak::RegExp &,size_t)' [found using argument-dependent lookup]
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\reference\include\openvino/reference/utils/registers_pool.hpp(61): note: or       'Xbyak::RegExp ov::reference::jit::RegistersPool::Reg<Xbyak::Reg64>::operator +(const ov::reference::jit::RegistersPool::Reg<Xbyak::Reg64> &,const Xbyak::RegExp &)' [found using argument-dependent lookup]
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(503): note: while trying to match the argument list '(ov::reference::jit::RegistersPool::Reg<Xbyak::Reg64>, const size_t)'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(503): error C7732: expected an expression before ']'
D:\b\openvino\src\2025.2.0-98de5d7579.clean\src\core\src\runtime\compute_hash.cpp(503): error C2679: binary '[': no operator found which takes a right-hand operand of type 'int' (or there is no acceptable conversion)
```

Possibly caused by https://github.com/herumi/xbyak/commit/8728007a8dcb2c8f6f86af7e17a050d1658836db or https://github.com/herumi/xbyak/commit/0cef2127a4dfdad6a116dbfb0ed3eaf32dbdca96 etc.

**Comment by dg0yt** [comment]
#51264 is more recent, by the same author. @toge please cleanup your backlog.

**Comment by BillyONeal** [comment]
> #51264 is more recent, by the same author. @toge please cleanup your backlog.

Closing this one for that reason.
