### PR TITLE
[date] add patch for MSVC 2019/2022 compatibility

### LINKED ISSUE #676: date::parse doesn't work with VS2019 v16.10 anymore
Hello,

I just updated my compiler to the current v16.10 release of MSVC and unfortunately, `date::parse` seems not to work anymore.

Take this example (inspired by: https://stackoverflow.com/a/41613816):

```
std::chrono::time_point<std::chrono::system_clock> tp;
std::istringstream("2021-02-18T08:00:00") >> date::parse("%FT%T", tp);
```

This used to compile just fine but now it will give an error:

> error C2672: 'date::parse': no matching overloaded function found
> error C2893: Failed to specialize function template 'unknown-type date::parse(const CharT *,Parsable &)'
> date.h(7883): note: see declaration of 'date::parse'
> note: With the following template arguments:
> note: 'Parsable=std::chrono::time_point<std::chrono::system_clock,std::chrono::duration<std::chrono::system_clock::rep,std::chrono::system_clock::period>>'
> note: 'CharT=char'
> error C2780: 'unknown-type date::parse(const std::basic_string<_Elem,_Traits1,_Alloc1> &,Parsable &,std::basic_string<_Elem,_Traits1,_Alloc1> &,std::chrono::minutes &)': expects 4 arguments - 2 provided
> date.h(7869): note: see declaration of 'date::parse'
> error C2780: 'unknown-type date::parse(const std::basic_string<_Elem,_Traits1,_Alloc1> &,Parsable &,std::chrono::minutes &)': expects 3 arguments - 2 provided
> note: see declaration of 'date::parse'
> error C2780: 'unknown-type date::parse(const std::basic_string<_Elem,_Traits1,_Alloc1> &,Parsable &,std::basic_string<_Elem,_Traits1,_Alloc1> &)': expects 3 arguments - 2 provided
> note: see declaration of 'date::parse'
> error C2784: 'unknown-type date::parse(const std::basic_string<_Elem,_Traits1,_Alloc1> &,Parsable &)': could not deduce template argument for 'const std::basic_string<_Elem,_Traits1,_Alloc1> &' from 'const char [6]'
> note: see declaration of 'date::parse'

### PR DESCRIPTION
**Pull request by JulZimmermann**
**Describe the pull request**

This PR adds a new patch to the date library

- #### What does your PR fix?
  Fixes https://github.com/HowardHinnant/date/issues/676 and https://github.com/HowardHinnant/date/issues/717
  Backport of https://github.com/HowardHinnant/date/pull/677

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
no changes,No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  No, did changes manually

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by Cheney-W** [comment]
Please run following command when you git commit a new commit:
.\vcpkg x-add-version {Port name}
git add .
git commit --amend --no-edit
git push

**Comment by Cheney-W** [comment]
Pinging @JulZimmermann  for response. Is work still being done for this PR?

**Comment by JulZimmermann** [comment]
Sorry for not doing further work for this PR. As a workaround for us, I added the current master build (with the fix) of `date` to our private intern vcpkg registry.

What is the general rule about such a "bugfix backport patch" as I did with this PR? Is this OK at all? I actually wasn't sure about that when creating the PR.

If this PR has a chance to get merged, I can do the requested changes next week.

Thanks!

**Comment by Cheney-W** [comment]
If the patch modifies the upstream source, these modifications need to be approved by the upstream.
Also, any modification to the port must also modify vcpkg.json. If it is not update version, then you need to modify or add the `"port-version"` field.
After you submit any commit, you need to update the json file corresponding to the port, the command is as follows:
`.\vcpkg x-add-version {Port name}` (If you have executed this command before, after the new modification, you need to add `--overwrite-version` parameter)
`git add .`
`git commit --amend --no-edit`
`git push`

**Comment by Cheney-W** [comment]
Pinging @JulZimmermann for response. Is work still being done for this PR?

**Comment by Cheney-W** [comment]
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.
