### PR TITLE
[llfio] Fix build with [status-code] feature enabled.

### PR DESCRIPTION
**Pull request by BillyONeal**
https://github.com/ned14/llfio/pull/175

This cast is necessary to build on Visual Studio 2026 18.6.0 / MSVC 19.51 when `llfio[status-code]` is turned on

```console
C:\Dev\vcpkg2\buildtrees\llfio\src\20260506-b0cb791d93.clean\include\llfio\v2.0\status_code.hpp(401,79): error C2440: 'default argument': cannot convert from 'system_error2::errc' to 'system_error2::system_code'
                     SYSTEM_ERROR2_NAMESPACE::system_code not_matched = errc::resource_unavailable_try_again) noexcept
                                                                              ^
C:\Dev\vcpkg2\buildtrees\llfio\src\20260506-b0cb791d93.clean\include\llfio\v2.0\status_code.hpp(401,79): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```

I'm not sure exactly why the implicit conversion isn't working on the default argument here :/

### CODE REVIEW

**Comment by BillyONeal** [comment]
I'm not 100% positive on this one so I want upstream to comment before proceeding.

**Comment by BillyONeal** [comment]
Closing because upstream does not appear to like the change
