### PR TITLE
[libffi] Upgrade to 3.2.1 - Waiting for 3.3 release

### PR DESCRIPTION
**Pull request by LilyWangL**
Related to #6618
1. Update to version 3.2.1
2. Fix old patches 
3. Fix build error: `error C2061: syntax error: identifier '_Complex'`

### CODE REVIEW

**Comment by wangli28** [comment]
Due to a known problem, version 3.2.1 of libffi built failed for the x86_64 architecture.

Related: [#149](https://github.com/libffi/libffi/issues/149).

**Comment by dan-shaw** [comment]
Hi! We are waiting for the official 3.3 release on this one - since libffi works on x86_64 on 3.3rc0.

**Comment by dan-shaw** [comment]
#6119
