### ISSUE TITLE
[readline-win32] dynamic linking fails

### ISSUE THREAD

**Issue by dyfer** [microsoft/vcpkg#34501]
**Describe the bug**
Linking against shared/dynamic library of `readline` seems to fail.

**Environment**
- OS: Windows (triplet: x64-windows)
- Compiler: MSVC 2019 16.11.34031.81

**To Reproduce**
1. `./vcpkg install readline`
2. (configure and build supercollider, which uses readline from vcpkg)
3. build fails with `fatal error LNK1120: 3 unresolved externals`

**Expected behavior**
Linking works and build succeeds 

**Failure logs**
build log:
```
(...)
     Creating library D:/a/supercollider/supercollider/build/lang/Release/sclang.lib and object D:/a/supercollider/supercollider/build/lang/Release/sclang.exp
libsclang.lib(SC_TerminalClient.obj) : error LNK2019: unresolved external symbol rl_readline_name referenced in function "private: void __cdecl SC_TerminalClient::inputThreadFn(void)" (?inputThreadFn@SC_TerminalClient@@AEAAXXZ) [D:\a\supercollider\supercollider\build\lang\sclang.vcxproj]
libsclang.lib(SC_TerminalClient.obj) : error LNK2019: unresolved external symbol rl_catch_signals referenced in function "private: void __cdecl SC_TerminalClient::inputThreadFn(void)" (?inputThreadFn@SC_TerminalClient@@AEAAXXZ) [D:\a\supercollider\supercollider\build\lang\sclang.vcxproj]
libsclang.lib(SC_TerminalClient.obj) : error LNK2019: unresolved external symbol rl_basic_word_break_characters referenced in function "private: void __cdecl SC_TerminalClient::inputThreadFn(void)" (?inputThreadFn@SC_TerminalClient@@AEAAXXZ) [D:\a\supercollider\supercollider\build\lang\sclang.vcxproj]
D:\a\supercollider\supercollider\build\lang\Release\sclang.exe : fatal error LNK1120: 3 unresolved externals [D:\a\supercollider\supercollider\build\lang\sclang.vcxproj]
```

**Additional context**
It seems this failure was introduced in #33892. When I check out an earlier commit of vcpkg (e.g. [the previous change to readline](https://github.com/microsoft/vcpkg/commit/80f8da23a88a982cf2d81d1a01623c55bb58df15)), building and linking work fine.

**Comment by dg0yt** [comment]
CC @xiaozhuai

**Comment by xiaozhuai** [comment]
@dyfer 
Thanks for reporting this, please try #34502 to see if it works or not.

**Comment by dyfer** [comment]
@xiaozhuai Thanks!
Yes, https://github.com/microsoft/vcpkg/pull/34502 seems to fix the issue, it builds and links without errors.
