### ISSUE TITLE
[osg] is broken due to moving tiff to static linking

### ISSUE THREAD

**Issue by neshume** [Microsoft/vcpkg#5806]

**Comment by neshume** [comment]
this was done in:

[tiff] Changed library linkage to static. #5766

pull request

**Comment by andyzhshg** [comment]
got the same issue on installing osg:windows-x64
```
       “C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\install.vcxproj”(默认目标) (1) ->
       “C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\ALL_BUILD.vcxproj”(默认目标) (3) ->
       “C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj”(默认目标) (107) ->
       (Link 目标) -> 
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_std_error referenced in function TIFFjpeg_create_compress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_std_error [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_CreateCompress referenced in function TIFFjpeg_create_compress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_CreateDecompress referenced in function TIFFjpeg_create_decompress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_CreateDecompress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_set_defaults referenced in function TIFFjpeg_set_defaults [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_set_colorspace referenced in function TIFFjpeg_set_colorspace [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_set_quality referenced in function TIFFjpeg_set_quality [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_suppress_tables referenced in function TIFFjpeg_suppress_tables [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_start_compress referenced in function TIFFjpeg_start_compress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_write_scanlines referenced in function TIFFjpeg_write_scanlines [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_finish_compress referenced in function TIFFjpeg_finish_compress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_write_raw_data referenced in function TIFFjpeg_write_raw_data [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_write_tables referenced in function TIFFjpeg_write_tables [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_read_header referenced in function TIFFjpeg_read_header [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_read_header [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_start_decompress referenced in function TIFFjpeg_start_decompress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_start_decompress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_read_scanlines referenced in function TIFFjpeg_read_scanlines [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_read_scanlines [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_finish_decompress referenced in function TIFFjpeg_finish_decompress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_read_raw_data referenced in function TIFFjpeg_read_raw_data [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_read_raw_data [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_has_multiple_scans referenced in function TIFFjpeg_has_multiple_scans [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_abort referenced in function TIFFjpeg_error_exit [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_destroy referenced in function TIFFjpeg_destroy [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_destroy [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_resync_to_restart referenced in function TIFFjpeg_data_src [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_code referenced in function LZMAEncode [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_end referenced in function LZMASetupDecode [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_memusage referenced in function LZMADecode [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_lzma_preset referenced in function TIFFInitLZMA [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_stream_encoder referenced in function LZMAPreEncode [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_stream_decoder referenced in function LZMADecode [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\bin\osgPlugins-3.6.2\osgdb_tiffd.dll : fatal error LNK1120: 27 unresolved externals [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]

```

**Comment by luckMike** [comment]
> got the same issue on installing osg:windows-x64
> 
> ```
>        “C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\install.vcxproj”(默认目标) (1) ->
>        “C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\ALL_BUILD.vcxproj”(默认目标) (3) ->
>        “C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj”(默认目标) (107) ->
>        (Link 目标) -> 
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_std_error referenced in function TIFFjpeg_create_compress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_std_error [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_CreateCompress referenced in function TIFFjpeg_create_compress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_CreateDecompress referenced in function TIFFjpeg_create_decompress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_CreateDecompress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_set_defaults referenced in function TIFFjpeg_set_defaults [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_set_colorspace referenced in function TIFFjpeg_set_colorspace [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_set_quality referenced in function TIFFjpeg_set_quality [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_suppress_tables referenced in function TIFFjpeg_suppress_tables [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_start_compress referenced in function TIFFjpeg_start_compress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_write_scanlines referenced in function TIFFjpeg_write_scanlines [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_finish_compress referenced in function TIFFjpeg_finish_compress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_write_raw_data referenced in function TIFFjpeg_write_raw_data [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_write_tables referenced in function TIFFjpeg_write_tables [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_read_header referenced in function TIFFjpeg_read_header [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_read_header [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_start_decompress referenced in function TIFFjpeg_start_decompress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_start_decompress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_read_scanlines referenced in function TIFFjpeg_read_scanlines [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_read_scanlines [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_finish_decompress referenced in function TIFFjpeg_finish_decompress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_read_raw_data referenced in function TIFFjpeg_read_raw_data [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_read_raw_data [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_has_multiple_scans referenced in function TIFFjpeg_has_multiple_scans [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_abort referenced in function TIFFjpeg_error_exit [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_destroy referenced in function TIFFjpeg_destroy [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_destroy [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_resync_to_restart referenced in function TIFFjpeg_data_src [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_code referenced in function LZMAEncode [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_end referenced in function LZMASetupDecode [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_memusage referenced in function LZMADecode [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_lzma_preset referenced in function TIFFInitLZMA [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_stream_encoder referenced in function LZMAPreEncode [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_stream_decoder referenced in function LZMADecode [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
>          C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\bin\osgPlugins-3.6.2\osgdb_tiffd.dll : fatal error LNK1120: 27 unresolved externals [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> ```

I also encountered this problem, how did you solve it?

**Comment by andyzhshg** [comment]
> > got the same issue on installing osg:windows-x64
> > ```
> >        “C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\install.vcxproj”(默认目标) (1) ->
> >        “C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\ALL_BUILD.vcxproj”(默认目标) (3) ->
> >        “C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj”(默认目标) (107) ->
> >        (Link 目标) -> 
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_std_error referenced in function TIFFjpeg_create_compress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_std_error [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_CreateCompress referenced in function TIFFjpeg_create_compress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_CreateDecompress referenced in function TIFFjpeg_create_decompress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_CreateDecompress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_set_defaults referenced in function TIFFjpeg_set_defaults [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_set_colorspace referenced in function TIFFjpeg_set_colorspace [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_set_quality referenced in function TIFFjpeg_set_quality [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_suppress_tables referenced in function TIFFjpeg_suppress_tables [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_start_compress referenced in function TIFFjpeg_start_compress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_write_scanlines referenced in function TIFFjpeg_write_scanlines [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_finish_compress referenced in function TIFFjpeg_finish_compress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_write_raw_data referenced in function TIFFjpeg_write_raw_data [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_write_tables referenced in function TIFFjpeg_write_tables [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_read_header referenced in function TIFFjpeg_read_header [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_read_header [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_start_decompress referenced in function TIFFjpeg_start_decompress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_start_decompress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_read_scanlines referenced in function TIFFjpeg_read_scanlines [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_read_scanlines [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_finish_decompress referenced in function TIFFjpeg_finish_decompress [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_read_raw_data referenced in function TIFFjpeg_read_raw_data [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_read_raw_data [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_has_multiple_scans referenced in function TIFFjpeg_has_multiple_scans [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_abort referenced in function TIFFjpeg_error_exit [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_destroy referenced in function TIFFjpeg_destroy [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_destroy [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_resync_to_restart referenced in function TIFFjpeg_data_src [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_code referenced in function LZMAEncode [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_end referenced in function LZMASetupDecode [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_memusage referenced in function LZMADecode [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_lzma_preset referenced in function TIFFInitLZMA [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_stream_encoder referenced in function LZMAPreEncode [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_stream_decoder referenced in function LZMADecode [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> >          C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\bin\osgPlugins-3.6.2\osgdb_tiffd.dll : fatal error LNK1120: 27 unresolved externals [C:\develop\tools\vcpkg\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
> > ```
> 
> I also encountered this problem, how did you solve it?

As @neshume mentioned this issue was introduced by #5766, I rollback to commit dc970afe341ef37877a3b8481ffc75dd54e07575

**Comment by tourdeli** [comment]
me too,,,,

**Comment by JackBoosY** [comment]
Duplicate with #5889, close this issue.
