### ISSUE TITLE
[New Port Request] <MITK>

### ISSUE THREAD

**Issue by thkvc** [microsoft/vcpkg#8730]
Library name: MITK

Library description: The Medical Imaging Interaction Toolkit (MITK) is a free open-source software system for development of interactive medical image processing software. MITK combines the Insight Toolkit (ITK) and the Visualization Toolkit (VTK) with an application framework.

Source repository URL: https://github.com/MITK/MITK

Project homepage: http://mitk.org

**Comment by JackBoosY** [comment]
Block by boost-python build failure:
`wrap_python.hpp(57): fatal error C1083: Cannot open include file: 'pyconfig.h': No such file or directory`

**Comment by vpaladino778** [comment]
I'll try putting a pull request for this.

**Comment by vpaladino778** [comment]
I attempted to throw together a portfile, but it looks like there's an issue with qt5-base. QT5 is a dependency for this library, so i added it as a build-depends. But QT5 is having errors building (Seems independent from anything involving my portfile. I tried installing QT5 alone and it still resulted in an error) 

```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/Users/vpaladino/Desktop/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe /J 8
    Working Directory: C:/Users/vpaladino/Desktop/vcpkg/buildtrees/qt5-base/x86-windows-rel
    Error code: 2
    See logs for more information:
      C:\Users\vpaladino\Desktop\vcpkg\buildtrees\qt5-base\build-x86-windows-rel-out.log
      C:\Users\vpaladino\Desktop\vcpkg\buildtrees\qt5-base\build-x86-windows-rel-err.log
```

Here's the QT5 error logs
[config-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3772586/config-x86-windows-dbg-out.log)
[config-x86-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/3772587/config-x86-windows-rel-err.log)
[config-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/3772588/config-x86-windows-rel-out.log)
[build-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/3772589/build-x86-windows-dbg-err.log)
[build-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3772590/build-x86-windows-dbg-out.log)
[build-x86-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/3772591/build-x86-windows-rel-err.log)
[build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/3772592/build-x86-windows-rel-out.log)
[config-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/3772593/config-x86-windows-dbg-err.log)

**Comment by JackBoosY** [comment]
boost-python failure will be fixed in #8882.

**Comment by Neumann-A** [comment]
Error:
`C:\Users\vpaladino\Desktop\vcpkg\buildtrees\qt5-base\src\5.12.5-0f870116d4\src\3rdparty\angle\src\libANGLE\renderer\d3d\d3d11\texture_format_table_autogen.cpp : fatal error C1083: Cannot open compiler generated file: '': Invalid argument`

`C:\Users\vpaladino\Desktop\vcpkg\buildtrees\qt5-base\src\5.12.5-0f870116d4\src\3rdparty\angle\src\libANGLE\renderer\d3d\d3d11\texture_format_table_autogen.cpp `
is already 237 characters long..... should we make the path length warning fatal if the root path is much longer than the warning level? So that people actually try to build with shorter paths before posting an issue? 
If that is not the root problem I would assume insufficient disk space.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by al-sabr** [comment]
Since the **DCMTK** library on which **MITK** is depending is now integrated in vcpkg why doesn't **MITK** part of this?

I've looked into the CMakeLists.txt and **BlueBerry**, **CppMicroservices** should be used directly from vcpkg and not integrated inside of that big mess.

Currently supported by **vcpkg**: 

- **CppMicroservices**

- **DCMTK**

Missing port:

- **BlueBerry Framework**
- **MITK**

Please let us know when this is doable.

Best Regards

**Comment by qaler** [comment]
> Since the **DCMTK** library on which **MITK** is depending is now integrated in vcpkg why doesn't **MITK** take part of this?
> 
> I've looked into the CMakeLists.txt and **BlueBerry**, **CppMicroservices** should be used directly from vcpkg and not integrated inside of that big mess.
> 
> Currently supported by **vcpkg**:
> 
> * **CppMicroservices**
> * **DCMTK**
> 
> Missing port:
> 
> * **BlueBerry Framework**
> * **MITK**
> 
> Please let us know when this is doable.
> 
> Best Regards

Well, according to Stefan, the CppMicroservices of vcpkg is probably not the same one that MITK is using.

> CppMicroServices started like BlueBerry as MITK subproject (Modules/CppMicroservices) and it is still a subproject in its initial version (which we are using). There’s also subsequent versions of CppMicroServices that are completely decoupled and are hosted on http://cppmicroservices.org/ and have nothing to do with MITK anymore (and won’t work out of the box with MITK).

https://www.mail-archive.com/mitk-users@lists.sourceforge.net/msg08284.html
