### PR TITLE
[Many Ports] Baseline Fixes for 2020-10-24 CI Build

### PR DESCRIPTION
**Pull request by BillyONeal**
Several fixes for problems discovered in recent CI builds: https://dev.azure.com/vcpkg/public/_build/results?buildId=44482&view=results

========================================
[libnice] Disable parallel configure.

REGRESSION: libnice:x64-windows. If expected, add libnice:x64-windows=fail to .\scripts\ci.baseline.txt.

CMake Error at CMakeLists.txt:13 (configure_file):
  configure_file Problem configuring file

========================================
[knet] Disable parallel configure.

REGRESSION: knet:x64-windows. If expected, add knet:x64-windows=fail to .\scripts\ci.baseline.txt.

CMake Error at src/CMakeLists.txt:1 (configure_file):
  configure_file Problem configuring file

========================================
[nvtt] Devendor libsquish

This was regressed by https://github.com/microsoft/vcpkg/pull/13674

REGRESSION: nvtt:x64-linux. If expected, add nvtt:x64-linux=fail to .\scripts\ci.baseline.txt.
REGRESSION: nvtt:x64-osx. If expected, add nvtt:x64-osx=fail to .\scripts\ci.baseline.txt.
REGRESSION: nvtt:x64-windows-static. If expected, add nvtt:x64-windows-static=fail to .\scripts\ci.baseline.txt.
REGRESSION: nvtt:x64-windows. If expected, add nvtt:x64-windows=fail to .\scripts\ci.baseline.txt.

Installing package nvtt[core]:x64-linux...
The following files are already installed in /mnt/vcpkg-ci/installed/x64-linux and are in conflict with nvtt:x64-linux

Installed by libsquish:x64-linux
    debug/lib/libsquishd.a
    include/squish.h
    lib/libsquish.a

========================================
[akali] Disable parallel configure.

REGRESSION: akali:x64-windows. If expected, add akali:x64-windows=fail to .\scripts\ci.baseline.txt.

Attempts to fix:

CMake Error: Could not open file for write in copy operation C:/Dev/vcpkg/buildtrees/akali/src/fc94eb83a9-01654d3f7c.clean/include/akali_config.h.tmp
CMake Error: : System Error: Permission denied
CMake Error at CMakeLists.txt:20 (configure_file):
  configure_file Problem configuring file

========================================
[libp7client, libp7-baical] Combine identical ports and update to libp7client 5.6.

REGRESSION: libp7client:x64-windows-static. If expected, add libp7client:x64-windows-static=fail to .\scripts\ci.baseline.txt.
REGRESSION: libp7client:x64-windows. If expected, add libp7client:x64-windows=fail to .\scripts\ci.baseline.txt.
REGRESSION: libp7client:x86-windows. If expected, add libp7client:x86-windows=fail to .\scripts\ci.baseline.txt.

Installing package libp7-baical[core]:x86-windows...
The following files are already installed in C:/Dev/vcpkg/installed/x86-windows and are in conflict with libp7-baical:x86-windows

Installed by libp7client:x86-windows
    bin/P7x32.dll
    bin/P7x32.pdb
    debug/bin/P7x32d.dll
    debug/bin/P7x32d.pdb
    include/P7/GTypes.h
    include/P7/P7_Client.h
    include/P7/P7_Cproxy.h
    include/P7/P7_Extensions.h
    include/P7/P7_Telemetry.h
    include/P7/P7_Trace.h

It turns out that these ports are identical, they are just different versions of the same library. The libp7-baical version supported more platforms and was simpler, so took that one and updated it to a current version.

========================================
[ignition-modularscripts, ignition-msgs1] Attempt to fix intermittent build failures by disabling parallel configure.

REGRESSION: ignition-msgs1:x64-windows-static. If expected, add ignition-msgs1:x64-windows-static=fail to .\scripts\ci.baseline.txt.
REGRESSION: ignition-msgs1:x64-windows. If expected, add ignition-msgs1:x64-windows=fail to .\scripts\ci.baseline.txt.
REGRESSION: ignition-msgs5:x64-windows-static. If expected, add ignition-msgs5:x64-windows-static=fail to .\scripts\ci.baseline.txt.
REGRESSION: ignition-msgs5:x64-windows. If expected, add ignition-msgs5:x64-windows=fail to .\scripts\ci.baseline.txt.

I don't know the cause of these but I know they are intermittent; going to try to workaround it with DISABLE_PARALLEL_CONFIGURE.

========================================
Removed several passing ports from the fail list.

PASSING, REMOVE FROM FAIL LIST: fastrtps:x64-osx (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: nanodbc:x64-osx (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: nettle:x64-osx (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: openvdb:x64-osx (.\scripts\ci.baseline.txt)

NOT ADDRESSED:
REGRESSION: qt5-imageformats:x64-windows. If expected, add qt5-imageformats:x64-windows=fail to .\scripts\ci.baseline.txt.
REGRESSION: qt5-tools:x64-windows-static. If expected, add qt5-tools:x64-windows-static=fail to .\scripts\ci.baseline.txt.
I don't know the cause of these but they are intermittent. Robert @ras0219 is investigating.

REGRESSION: ogre:x64-windows-static. If expected, add ogre:x64-windows-static=fail to .\scripts\ci.baseline.txt.
Components\Bites\include\moc_OgreApplicationContextQt.cpp(66): error C2491: 'OgreBites::ApplicationContextQt::staticMetaObject': definition of dllimport static data member not allowed
This looks like the same as the qt failures; probably started happening after https://github.com/microsoft/vcpkg/pull/14006

arm64-windows had a download failure in the pre-CI step for boost-build so I'm not including those results.

### CODE REVIEW

File: ports/libp7client/CMakeLists.txt [hunk 1]
```diff
@@ -1,24 +1,17 @@
...
+  "Sources/Client.cpp"
+  "Sources/ClNull.cpp"
+  "Sources/ClText.cpp"
+  "Sources/CRC32.cpp"
+  "Sources/Proxy.cpp"
+  "Sources/Telemetry.cpp"
+  "Sources/Trace.cpp")
 
-if(WIN32)
-  set(RESOURCES "Sources/P7Client.rc")
```
Comment (ras0219) [inline ports/libp7client/CMakeLists.txt:16]: Is this not needed?

**Review by ras0219 — APPROVED** [review]

File: ports/libp7client/CMakeLists.txt (hunk 1 above)
Comment (BillyONeal) [reply ports/libp7client/CMakeLists.txt:16]: This file doesn't exist in the current sources.

**Review by vicroms — APPROVED** [review]
LGTM
