### PR TITLE
[mygui] Support dynamic linking for MyGUI

### PR DESCRIPTION
**Pull request by AnyOldName3**
The new patch was accepted upstream as https://github.com/MyGUI/mygui/pull/270, but as other lines have changed in one of the affected files, we need a bespoke patch to work with the 3.4.3 release.

Intended to supersede https://github.com/microsoft/vcpkg/pull/41800 as that PR isn't useful without the other changes this one makes.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by AnyOldName3** [comment]
OpenMW's also been carrying 6f1c4b59b58d5663d43a2c82f31ba9340005bf93 in our fork, but that looks like it'd be sensible to upstream, too. Do you want it doing in this PR or a separate one?

**Review by WangWeiLin-MV — COMMENTED** [review]
Failed with `vcpkg install mygui[*]:x64-windows`

```log
BaseManager.cpp.obj : error LNK2019: unresolved external symbol IMG_Init referenced in function "public: virtual bool __cdecl base::BaseManager::createRender(int,int,bool)"
```

**Comment by AnyOldName3** [comment]
> Failed with `vcpkg install mygui[*]:x64-windows`
> 
> ```
> BaseManager.cpp.obj : error LNK2019: unresolved external symbol IMG_Init referenced in function "public: virtual bool __cdecl base::BaseManager::createRender(int,int,bool)"
> ```

This should now be resolved - I'd not built with the tools option enabled. The necessary patch is available upstream as https://github.com/MyGUI/mygui/pull/271, but not yet merged when I'm writing this. There's a good chance that it will be by the time you're reading this, though.

**Comment by AnyOldName3** [comment]
It's now merged upstream, so this PR should work properly, and only contain changes upstream is happy with.

The only remaining question is whether it's preferable to submit https://github.com/microsoft/vcpkg/commit/6f1c4b59b58d5663d43a2c82f31ba9340005bf93 as a standalone PR or part of this one.

**Comment by WangWeiLin-MV** [comment]
> The only remaining question is whether it's preferable to submit [6f1c4b5](https://github.com/microsoft/vcpkg/commit/6f1c4b59b58d5663d43a2c82f31ba9340005bf93) as a standalone PR or part of this one.

Small PRs follow best practices, I think it's better to separate, https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#make-separate-pull-requests-per-port.

**Review by WangWeiLin-MV — APPROVED** [review]
The port features installation tests pass with the following triplets:

* x64-linux
* x64-linux-static
* x64-windows
* x64-windows-static
