### ISSUE TITLE
vcpkg no longer builds on MSVC 2015

### ISSUE THREAD

**Issue by rouault** [microsoft/vcpkg#10011]
**Describe the bug**
vcpkg no longer builds on MSVC 2015, presumably due to a33044c18637d3df6de93128d33dae1fb5ba575c 

**Environment**
- OS: Windows
- Compiler: MSVC 2015 from AppVeyor

**To Reproduce**
- git clone https://github.com/microsoft/vcpkg
- cd vcpkg
- bootstrap-vcpkg.bat

**Failure logs** 
See https://ci.appveyor.com/project/OSGeo/gdal/builds/30695343/job/souj2w5dyjpldy1d
```
C:\projects\gdal\vcpkg\toolsrc\include\vcpkg/parse.h(114): error C2440: 'return': cannot convert from 'initializer list' to 'vcpkg::Parse::TextRowCol' (compiling source file ..\src\vcpkg\logicexpression.cpp) [C:\projects\gdal\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
  C:\projects\gdal\vcpkg\toolsrc\include\vcpkg/parse.h(114): note: No constructor could take the source type, or constructor overload resolution was ambiguous (compiling source file ..\src\vcpkg\logicexpression.cpp)
```

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by yamcenutzer** [comment]
this happens after commit:
a33044c18637d3df6de93128d33dae1fb5ba575c
