### PR TITLE
[behaviortree-cpp] Add new port

### PR DESCRIPTION
**Pull request by seanyen**
Add new port of behaviortree-cpp:  https://www.behaviortree.dev/

### CODE REVIEW

**Review by LilyWangL — APPROVED** [review]

**Comment by LilyWangL** [comment]
The change of lzokay is duplicate with PR #12766.

**Comment by seanyen** [comment]
Rebased.

File: ports/behaviortree-cpp/vcpkg.json [hunk 1]
```diff
@@ -0,0 +1,6 @@
+{
+  "name": "behaviortree-cpp",
+  "version-string": "3.5.1",
+  "description": "Behavior Trees Library in C++.",
+  "homepage": "https://www.behaviortree.dev"
```
Comment (strega-nil) [inline ports/behaviortree-cpp/vcpkg.json:5]:
```suggestion
  "homepage": "https://www.behaviortree.dev",
  "supports": "!uwp"
```

File: scripts/ci.baseline.txt [hunk 2]
```diff
@@ -112,6 +112,9 @@ bde:x64-uwp=fail
 bde:x64-windows=fail
 bde:x64-windows-static=fail
 bde:x86-windows=fail
+behaviortree-cpp:arm-uwp=fail
+behaviortree-cpp:x64-osx=fail
+behaviortree-cpp:x64-uwp=fail
```
Comment (strega-nil) [inline scripts/ci.baseline.txt:117]: Then, with the above change, you can get:

```suggestion
behaviortree-cpp:x64-osx=fail
```

**Review by strega-nil — APPROVED** [review]
Just a minor change, but this looks great 😄

File: ports/behaviortree-cpp/001_port_fixes.patch [hunk 3]
```diff
@@ -0,0 +1,13 @@
+diff --git a/CMakeLists.txt b/CMakeLists.txt
+index 75dea11..4eea781 100644
+--- a/CMakeLists.txt
++++ b/CMakeLists.txt
+@@ -229,7 +229,7 @@ if( ZMQ_FOUND )
+ endif()
+ 
+ if(MSVC)
+-    target_compile_options(${BEHAVIOR_TREE_LIBRARY} PRIVATE /W4 /WX)
++    target_compile_options(${BEHAVIOR_TREE_LIBRARY} PRIVATE /W4 /WX /wd4702)
```
Comment (traversaro) [inline ports/behaviortree-cpp/001_port_fixes.patch:10]: Personally, I would avoid to have a `/WX` option (or a general `-Werror` option for GCC/Clang) on project used in vcpkg. New compiler version typically add new  warning, and even if for the library developer it make sense to have `/WX` or similar enabled in its own CI to get a clear notice of the new warning, for the user using the library in vcpkg this just means that the port can break just because a new compiler version is used.

Comment (strega-nil) [reply ports/behaviortree-cpp/001_port_fixes.patch:10]:
```suggestion
+    target_compile_options(${BEHAVIOR_TREE_LIBRARY} PRIVATE /W4 /wd4702)
```

**Comment by LilyWangL** [comment]
@seanyen Now this port build failed with the following error:
`D:\buildtrees\behaviortree-cpp\src\haviorTree-95072d0cc8.clean\src\action_node.cpp(72): fatal error C1083: Cannot open include file: 'boost/coroutine2/all.hpp': No such file or directory`
It looks like need add dependency `boost-coroutine2`. Could you continue to fix it?

**Comment by seanyen** [comment]
@LilyWangL Added. Let's see how it goes.

**Comment by LilyWangL** [comment]
The CI fails is not related with this PR, it will be fixed by PR #12856.

File: scripts/ci.baseline.txt [hunk 4]
```diff
@@ -112,6 +112,7 @@ bde:x64-uwp=fail
 bde:x64-windows=fail
 bde:x64-windows-static=fail
 bde:x86-windows=fail
+behaviortree-cpp:x64-osx=fail
```
Comment (BillyONeal) [inline scripts/ci.baseline.txt:115]: If the port doesn't support osx perhaps it should be excluded in "Supports"?

Comment (BillyONeal) [reply scripts/ci.baseline.txt:115]: Yep, I think the supports should be changed to `!uwp&!osx` and this item be removed from the baseline.

Comment (seanyen) [reply scripts/ci.baseline.txt]: @BillyONeal I updated the "Supports" part. Let's see how the CI goes. :)
