### PR TITLE
[qt] update port to 6.4

### PR DESCRIPTION
**Pull request by Neumann-A**
test run

### CODE REVIEW

File: ports/opengl/vcpkg-cmake-wrapper.cmake [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+    if(DEFINED VCPKG_BACKUP_CMAKE_FIND_USE_CMAKE_SYSTEM_PATH)
+        set(CMAKE_FIND_USE_CMAKE_SYSTEM_PATH "${VCPKG_BACKUP_CMAKE_FIND_USE_CMAKE_SYSTEM_PATH}")
+    else()
+        unset(CMAKE_FIND_USE_CMAKE_SYSTEM_PATH)
+    endif()
+    if(DEFINED VCPKG_BACKUP_CMAKE_FIND_USE_CMAKE_PATH)
+        set(CMAKE_FIND_USE_CMAKE_PATH "${VCPKG_BACKUP_CMAKE_FIND_USE_CMAKE_PATH}")
+    else()
+        unset(CMAKE_FIND_USE_CMAKE_PATH)
+    endif()
```
Comment (Neumann-A) [inline ports/opengl/vcpkg-cmake-wrapper.cmake:23]:
```suggestion
    list(APPEND CMAKE_IGNORE_PREFIX_PATH "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}")
    list(APPEND CMAKE_SYSTEM_IGNORE_PREFIX_PATH "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}")
    list(APPEND CMAKE_IGNORE_PATH "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include" "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib" "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug/lib")
    list(APPEND CMAKE_SYSTEM_IGNORE_PATH "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include" "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib" "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug/lib")
    _find_package(${ARGS})
```

File: ports/gstreamer/vcpkg.json [hunk 2]
```diff
@@ -1,7 +1,7 @@
 {
   "name": "gstreamer",
```
Comment (Neumann-A) [inline ports/gstreamer/vcpkg.json:2]: Note here: There seems to be an optional dependency on egl/angle in gstreamer. I don't have time to find it so there might be spurious errors in static builds due to that.

**Comment by Neumann-A** [comment]
@cenit: Do you know what happened to opencv4 in x64-windows here? From the error it looks like it is missing an (optional?) dependency.

**Comment by Neumann-A** [comment]
OK seems related to Ogre

**Comment by Neumann-A** [comment]
@dg0yt I think the regressions in this PR are yours ;) (from  #27107 somehow)

**Comment by dg0yt** [comment]
> @dg0yt I think the regressions in this PR are yours ;) (from #27107 somehow)

Possibly yes. I can open a PR with `-DOGRE_BUILD_COMPONENT_BULLET=no`.

**Comment by Neumann-A** [comment]
What about the inconsistent DLL linkage?
`D:\buildtrees\ogre\src\v13.4.4-21d2109e8f.clean\Components\Bites\src\OgreApplicationContextQt.cpp(117): warning C4273: 'OgreBites::ApplicationContextQt::createWindow': inconsistent dll linkage`
which probably lead to 
`D:\buildtrees\ogre\x64-windows-static-dbg\Components\Bites\include\moc_OgreApplicationContextQt.cpp(59): error C2491: 'OgreBites::ApplicationContextQt::staticMetaObject': definition of dllimport static data member not allowed`

**Comment by dg0yt** [comment]
ogre doesn't even declare a Qt dependency...

**Comment by Neumann-A** [comment]
@dg0yt  you probably wanted to use `CMAKE_DISABLE_FIND_PACKAGE_Q[tT][56]` instead of setting a single variable to false.

File: ports/opengl/portfile.cmake [hunk 3]
```diff
@@ -1,4 +1,4 @@
-if(NOT VCPKG_CMAKE_SYSTEM_NAME OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
+if(VCPKG_TARGET_IS_WINDOWS)
     vcpkg_get_windows_sdk(WINDOWS_SDK)
```
Comment (dg0yt) [inline ports/opengl/portfile.cmake:2]: I think this change will start to pull in the Windows SDK for mingw, but mingw doesn't need it.
OTOH mingw (as installed in Ubuntu 18.04) doesn't come with these pc files, so we might need to generate them.

**Review by dg0yt — COMMENTED** [review]
Just looking over these changes while studying the wxwidgets libEGL installation order problem....

**Comment by JonLiu1993** [comment]
@Neumann-A , Thanks for your contribution, can this PR start a review?

**Comment by Neumann-A** [comment]
@JonLiu1993 Yes. Since like approx two weeks

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by JonLiu1993** [comment]
@Neumann-A, Please resolve this conflict file to merge.

**Comment by vserdyuk** [comment]
Looking forward for this to be merged.

BTW, thank you @Neumann-A for your great work!

**Comment by Neumann-A** [comment]
@JonLiu1993 Have you forgotten to tag this reviewed or are you still reviewing this PR?

**Comment by JonLiu1993** [comment]
> @JonLiu1993 Have you forgotten to tag this reviewed or are you still reviewing this PR?

@Neumann-A, I often read this pr, but you continue to revise this pr, so I want to take a good look at it after you finish.

**Comment by Neumann-A** [comment]
Since https://github.com/microsoft/vcpkg/pull/26693/commits/bcd624722bc81c624c953ff71d39e50a5b1e0082 I am mainly working out merge conflicts and issues due to that, not really revising stuff...

**Comment by JonLiu1993** [comment]
> Since [bcd6247](https://github.com/microsoft/vcpkg/commit/bcd624722bc81c624c953ff71d39e50a5b1e0082) I am mainly working out merge conflicts and issues due to that, not really revising stuff...

Tomorrow I will take a serious look at the revision and do a preliminary review.

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by Neumann-A** [comment]
@JonLiu1993: Can you confirm from the Cache or the config log that Qt6ShaderTools (and maybe also Qt6ShaderToolsTools) has been found? If not your Qt installation might be broken somehow.

**Comment by JonLiu1993** [comment]
> @JonLiu1993: Can you confirm from the Cache or the config log that Qt6ShaderTools (and maybe also Qt6ShaderToolsTools) has been found? If not your Qt installation might be broken somehow.

Looks like it can't be found：
````
  Configuring with --debug-find-pkg=Qt6ShaderTools might reveal details why
  the package was not found.
````

**Comment by Neumann-A** [comment]
@JonLiu1993 Should be fixed now. Found another bug with minimal qtbase builds while trying to repo your error.

**Comment by JonLiu1993** [comment]
@Neumann-A, Feature ffmpeg tested successfully in the following triplet:
- x86-windows
- x64-windows

but when I tested the feature `sql-mysql,sql-oci,opengl` by command "./vcpkg install qtbase[sql-mysql,sql-oci,opengl]:x64-windows" I got this error:
````
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: F:/Feature-test/qt/vcpkg/buildtrees/qtbase/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      F:\Feature-test\qt\vcpkg\buildtrees\qtbase\config-x64-windows-CMakeCache.txt.log
      F:\Feature-test\qt\vcpkg\buildtrees\qtbase\config-x64-windows-CMakeCache.txt.log
      F:\Feature-test\qt\vcpkg\buildtrees\qtbase\config-x64-windows-out.log
````
F:\Feature-test\qt\vcpkg\buildtrees\qtbase\config-x64-windows-out.log
````
QtCore: WARNING: F:/Feature-test/qt/vcpkg/buildtrees/qtbase/src/here-src-6-4c6096fa61.clean/src/corelib/tools/qatomicscopedvaluerollback_p.h does not have the "We mean it." warning
-- Could NOT find md4c (missing: md4c_DIR)
CMake Error at cmake/QtBuildInformation.cmake:490 (message):
  Feature "sql_oci": Forcing to "ON" breaks its condition:

      Oracle_FOUND

  Condition values dump:

      Oracle_FOUND = "FALSE"

Call Stack (most recent call first):
  cmake/QtFeature.cmake:281 (qt_configure_add_report_error)
  cmake/QtFeature.cmake:403 (qt_feature_check_and_save_internal_value)
  cmake/QtFeature.cmake:606 (qt_evaluate_feature)
  src/plugins/sqldrivers/CMakeLists.txt:36 (qt_feature_module_end)
````

**Comment by Neumann-A** [comment]
You need the oracle client library for that.    I currently assume that to be a system dependency

**Comment by JonLiu1993** [comment]
> You need the oracle client library for that. I currently assume that to be a system dependency

Ok, I think the preliminary review is satisfied so far.

**Comment by BillyONeal** [comment]
Thanks :)

File: ports/qtbase/vcpkg.json [hunk 4]
```diff
@@ -141,8 +140,9 @@
     },
     "egl": {
       "description": "EGL",
+      "supports": "linux",
```
Comment (dg0yt) [inline ports/qtbase/vcpkg.json:143]: This change broke (at least) android:
~~~
$ ./vcpkg install --dry-run qtbase:arm-android
Computing installation plan...
qtbase[egl]:arm-android is only supported on 'linux'
~~~
The current egl patching is pointless when windows isn't support.

Comment (Neumann-A) [reply ports/qtbase/vcpkg.json:143]: Maybe should have been `!windows & !osx` then. But this only applies in `qtbase` and not `qtmultimedia`. (The `FindEGL` is also used by `qtmultimedia`.)

Comment (Neumann-A) [reply ports/qtbase/vcpkg.json:143]: EGL is just a glue layer to call into GL/GLES. It could very well be that `qtmultimedia` assumes linux for gstreamer (and forgot to condition it correctly) and the real dispatch is done via WGL instead. Since opengl is always dynamically linked on windows it will actually ask the driver if it supports the functionality it wants.
