### PR TITLE
[vulkan-*] update components to version 1.4.313.0

### PR DESCRIPTION
**Pull request by sandercox**
While working on 1.4.309.0 #45844 we also got 313 so updating it again to have all versions in the repo.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by BillyONeal** [comment]
```console
D:\b\ggml\src\d5969d6f49-e3532476b4.clean\src\ggml-vulkan\ggml-vulkan.cpp(2497): error C2065: 'get_rows_iq1_m_len': undeclared identifier
D:\b\ggml\src\d5969d6f49-e3532476b4.clean\src\ggml-vulkan\ggml-vulkan.cpp(2497): error C2065: 'get_rows_iq1_m_data': undeclared identifier
D:\b\ggml\src\d5969d6f49-e3532476b4.clean\src\ggml-vulkan\ggml-vulkan.cpp(2515): error C2065: 'get_rows_iq1_m_f32_len': undeclared identifier
D:\b\ggml\src\d5969d6f49-e3532476b4.clean\src\ggml-vulkan\ggml-vulkan.cpp(2515): error C2065: 'get_rows_iq1_m_f32_data': undeclared identifier
```

These seem like legitimate failures.

**Comment by sandercox** [comment]
Yes this needs more work indeed. I hoped it would just be increasing the version number woudld work but alas no dice. I'll look into it next week.

**Comment by dg0yt** [comment]
ggml needs to be rolled together with llama-cpp and whisker-cpp, all from the same organization. I'm trying to upstream testing/cmake-config improvements, but it is not going fast.

**Comment by tophyr** [comment]
FYI: #46621 updates these as well, to 321

**Comment by vicroms** [comment]
We have [closed this PR due to inactivity](https://learn.microsoft.com/vcpkg/contributing/maintainer-guide#close-inactive-prs). Please create a new PR if you're still interested in getting these changes merged.
