### ISSUE TITLE
[libxml2] (OSX) Dependent ports fail due to missing iconv linkage

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#11001]
**Host Environment**
- OS: OSX
- Compiler: revision

**Failure logs** 
```
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _xmlNanoFTPCheckResponse in libxml2.a(nanoftp.c.o)
      _xmlNanoFTPCloseConnection in libxml2.a(nanoftp.c.o)
      _xmlNanoFTPList in libxml2.a(nanoftp.c.o)
      _xmlNanoFTPGet in libxml2.a(nanoftp.c.o)
  "_iconv", referenced from:
      _xmlIconvWrapper in libxml2.a(encoding.c.o)
  "_iconv_close", referenced from:
      _xmlFindCharEncodingHandler in libxml2.a(encoding.c.o)
      _xmlCharEncCloseFunc in libxml2.a(encoding.c.o)
  "_iconv_open", referenced from:
      _xmlFindCharEncodingHandler in libxml2.a(encoding.c.o)
ld: symbol(s) not found for architecture x86_64
```

**Additional context**
the vcpkg-cmake-wrapper.cmake in libxml2 must be changed to also add the required dependencies on OSX. Observed in build failure of on OSX CI in https://github.com/microsoft/vcpkg/pull/10770

Missing symbol `___darwin_check_fd_set_overflow` might be an infrastructure/XCode bug or requires a rebuild of libxml?

**Comment by NancyLi1013** [comment]
Hi @Neumann-A 
Thanks for posting this issue.
Could you please help confirm on which version of your compiler you encountered this?
It seems a [bug ](https://openradar.appspot.com/FB7647406)introduced by Xcode 11.4.

**Comment by Neumann-A** [comment]
> Could you please help confirm on which version of your compiler you encountered this?
 
This was on vcpkg CI so you should know which compiler you use/used there to build libxml2. Maybe just need to rebuild libxml2 once for CI (assuming you updated Xcode on CI to a version without the bug).

**Comment by NancyLi1013** [comment]
Thanks for your info.
But I didn't see this failure for libxml2 in the PR #10770.

`libxml2:x64-osx:       pass: 829f2a0dc6353fb46c06b4c3028eaf4bb6b9fb84`

It seems to be passed. 
Where did you see this?
If this is really on vcpkg CI, we will try to solve this.

**Comment by Neumann-A** [comment]
@NancyLi1013: It is in the log of the cmake port build failure. 
[install-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/4538669/install-x64-osx-dbg-out.log) @ Line 404

**Comment by NancyLi1013** [comment]
Thanks.  I have noticed this and will look into it.

**Comment by NancyLi1013** [comment]
It seems that there is no the following error in current log.
  ```
       ___darwin_check_fd_set_overflow", referenced from:
      _xmlNanoFTPCheckResponse in libxml2.a(nanoftp.c.o)
      _xmlNanoFTPCloseConnection in libxml2.a(nanoftp.c.o)
      _xmlNanoFTPList in libxml2.a(nanoftp.c.o)
      _xmlNanoFTPGet in libxml2.a(nanoftp.c.o)
```
But the issue caused by iconv still exists.
```
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _xmlIconvWrapper in libxml2.a(encoding.c.o)
  "_iconv_close", referenced from:
      _xmlFindCharEncodingHandler in libxml2.a(encoding.c.o)
      _xmlCharEncCloseFunc in libxml2.a(encoding.c.o)
  "_iconv_open", referenced from:
      _xmlFindCharEncodingHandler in libxml2.a(encoding.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I checked the CMakeLists.txt and iconv has been linked.

I plan to submitted a PR to test this and confirm if there is something wrong with `libxml2 `on osx pipeline.

**Comment by NancyLi1013** [comment]
@strega-nil 
Could you please help take a look about this issue?

It should not  a usage bug for libxml2. I try to create a project to build on osx without any error.
In addition, I also noticed that `iconv `is only added on Windows platform in  vcpkg-cmake-wrapper.cmake. But this issue only occured on osx instead of osx and linux.

So I'm not sure what happened on osx.

**Comment by Neumann-A** [comment]
turns out:

libiconv portfile:
```
if(NOT VCPKG_TARGET_IS_WINDOWS)
    set(VCPKG_POLICY_EMPTY_PACKAGE enabled)
    file(MAKE_DIRECTORY ${CURRENT_PACKAGES_DIR}/share/unofficial-iconv)
    file(COPY ${CMAKE_CURRENT_LIST_DIR}/unofficial-iconv-config.cmake DESTINATION ${CURRENT_PACKAGES_DIR}/share/unofficial-iconv)
    return()
endif()
```

So libxml2 is probably not linking iconv from within vcpkg but a system version. The linux machine seems to have a shared library of iconv installed while the osx version has iconv has a static library?
libiconv should probably be fixed to build iconv and charset on all platforms.
