### ISSUE TITLE
Vcpkg doesn't build on macOS 10.14

### ISSUE THREAD

**Issue by acgetchell** [microsoft/vcpkg#8627]
**Describe the bug**
vcpkg no longer builds on macOS 10.14

**Environment**
- OS: 10.14
- Compiler: Apple clang version 11.0.0 (clang-1100.0.33.9)

**To Reproduce**
- git clone https://github.com/Microsoft/vcpkg.git
- cd vcpkg
- ./bootstrap-vcpkg.sh

**Expected behavior**
Vcpkg to build

**Failure logs** 
https://travis-ci.com/acgetchell/CDT-test/jobs/246378376#L413

**Additional context**
https://github.com/acgetchell/CDT-test/blob/master/.travis.yml

**Comment by cenit** [comment]
Somehow the CMakeFiles.txt lost the clang allowance only if explicitly told so, replaced with a more generic “if clang version is greater/equal than 11”... which is ok for Catalina, but not for 10.14 with clang11.....

**Comment by cenit** [comment]
@cbezault shall we go back to allow clang++ only if explicitly allowed or do you prefer checking also os version to automatically select it?

**Comment by JackBoosY** [comment]
Same error, using Xcode 11.

**Comment by mschofie** [comment]
I was able to work-around with:
1. `brew install gcc@9`
2. Apply the workaround for #7585.

**Comment by acgetchell** [comment]
Even applying the workaround to install the headers:

https://github.com/acgetchell/CDT-plusplus/commit/2b9f0796f1b520e6060fe1844866ba570d36fb03

Building `vcpkg` on AppleClang generates the error `../include/vcpkg/base/files.h:67:41: error: 'file_status' is unavailable: introduced in macOS 10.15`

https://travis-ci.org/github/acgetchell/CDT-plusplus/jobs/682756958#L505

**Comment by strega-nil** [comment]
Did this get re-broken?

**Comment by cenit** [comment]
Btw, At the moment vcpkg is broken on any macOS older than latest due to ninja 10.0...

**Comment by strega-nil** [comment]
Is there a reason not to roll back ninja?

**Comment by cenit** [comment]
The other issue where it was discusses is 20 days old, almost, #10890. I was supposing that we were waiting for 10.1 now...

**Comment by strega-nil** [comment]
Well, could all of y'all try out #11205 ?

**Comment by cenit** [comment]
Sorry I don't have any mac available with older macOS versions to test easily this PR. We just suffered from it on continuous integration...

**Comment by strega-nil** [comment]
Closed as no-fix. If people really need this, please reopen the issue.

**Comment by Alvaroalloc** [comment]
I have succeded bootstraping it with gcc9 from homebrew but i can't use it anywhere. I've tried cmake from terminal but nothing with the toolchain
