### PR TITLE
[gtk3, gstreamer] Avoid multiple definition of the symbol `properties`.

### PR DESCRIPTION
**Pull request by BillyONeal**
Hopefully resolves build error on x64-linux: https://dev.azure.com/vcpkg/public/_build/results?buildId=126505

```console
/usr/bin/ld: /mnt/vcpkg-ci/installed/x64-linux/debug/lib/pkgconfig/../../lib/libgtk-3.a(inspector_size-groups.c.o):/mnt/vcpkg-ci/b/gtk3/x64-linux-dbg/../src/NOME-gtk-3-f64471d55d.clean/gtk/inspector/size-groups.c:47: multiple definition of `properties'; subprojects/gstreamer/plugins/elements/libgstcoreelements.a(gstqueue.c.o):/mnt/vcpkg-ci/b/gstreamer/x64-linux-dbg/../src/1.26.5-9c0ab21028.clean/subprojects/gstreamer/plugins/elements/gstqueue.c:130: first defined here
```

I am not sure how to submit these patches to either gtk3 or gstreamer.

This failure started happening between January 19 and January 21; probably caused by #49571

### CODE REVIEW

**Comment by BillyONeal** [comment]
The other failures here are also FFmpeg related. For example:

```cmake
   Creating library gstreamer-full-1.0.lib and object gstreamer-full-1.0.exp
chromaprint.lib(fft_lib_avtx.cpp.obj) : error LNK2019: unresolved external symbol av_tx_init referenced in function "public: __cdecl chromaprint::FFTLib::FFTLib(unsigned __int64)" (??0FFTLib@chromaprint@@QEAA@_K@Z)
chromaprint.lib(fft_lib_avtx.cpp.obj) : error LNK2019: unresolved external symbol av_tx_uninit referenced in function "public: __cdecl chromaprint::FFTLib::~FFTLib(void)" (??1FFTLib@chromaprint@@QEAA@XZ)
chromaprint.lib(fft_lib_avtx.cpp.obj) : error LNK2019: unresolved external symbol av_malloc referenced in function "public: __cdecl chromaprint::FFTLib::FFTLib(unsigned __int64)" (??0FFTLib@chromaprint@@QEAA@_K@Z)
chromaprint.lib(fft_lib_avtx.cpp.obj) : error LNK2019: unresolved external symbol av_free referenced in function "public: __cdecl chromaprint::FFTLib::~FFTLib(void)" (??1FFTLib@chromaprint@@QEAA@XZ)
```

This is caused by `chromaprint` doing:

```cmake
if(USE_AVTX)
  set(chromaprint_SOURCES fft_lib_avtx.cpp ${chromaprint_SOURCES})
  set(chromaprint_LINK_LIBS
    ${FFMPEG_LIBAVUTIL_LIBRARIES}
  )
  include_directories(
    ${FFMPEG_LIBAVUTIL_INCLUDE_DIRS}
  )
endif(USE_AVTX)
```

but the FFmpeg 8.x CMake bindings no longer set `FFMPEG_LIBAVUTIL_LIBRARIES` so this ends up setting `chromaprint_LINK_LIBS` to empty string.

It's not clear if the right fix is to try to change FFmpeg's bindings to set those again.

**Comment by BillyONeal** [comment]
@dg0yt @Neumann-A et al. Are you familiar with C++ default libraries etc. handling with Meson?

I want to fix this rather than baselining it but it's not clear to me what to do :(

```console
/usr/bin/ld: /vcpkg/installed/x64-linux/debug/lib/pkgconfig/../../lib/libfluidsynth.a(fluid_dls.cpp.o): in function `log_exception(int, std::exception const&, int)':
/vcpkg/buildtrees/fluidsynth/src/v2.5.2-8791e69fca.clean/src/sfloader/fluid_dls.cpp:78:(.text+0x48): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
/usr/bin/ld: /vcpkg/buildtrees/fluidsynth/src/v2.5.2-8791e69fca.clean/src/sfloader/fluid_dls.cpp:82:(.text+0x8f): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)'
/usr/bin/ld: /vcpkg/buildtrees/fluidsynth/src/v2.5.2-8791e69fca.clean/src/sfloader/fluid_dls.cpp:82:(.text+0x9b): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: /vcpkg/buildtrees/fluidsynth/src/v2.5.2-8791e69fca.clean/src/sfloader/fluid_dls.cpp:85:(.text+0xb3): undefined reference to `typeinfo for std::bad_alloc'
/usr/bin/ld: /vcpkg/buildtrees/fluidsynth/src/v2.5.2-8791e69fca.clean/src/sfloader/fluid_dls.cpp:87:(.text+0xee): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
/usr/bin/ld: /vcpkg/buildtrees/fluidsynth/src/v2.5.2-8791e69fca.clean/src/sfloader/fluid_dls.cpp:91:(.text+0x13b): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
/usr/bin/ld: /vcpkg/buildtrees/fluidsynth/src/v2.5.2-8791e69fca.clean/src/sfloader/fluid_dls.cpp:108:(.text+0x17a): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: /vcpkg/buildtrees/fluidsynth/src/v2.5.2-8791e69fca.clean/src/sfloader/fluid_dls.cpp:98:(.text+0x1c8): undefined reference to `__cxa_begin_catch'
/usr/bin/ld: /vcpkg/buildtrees/fluidsynth/src/v2.5.2-8791e69fca.clean/src/sfloader/fluid_dls.cpp:102:(.text+0x1e1): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
/usr/bin/ld: /vcpkg/buildtrees/fluidsynth/src/v2.5.2-8791e69fca.clean/src/sfloader/fluid_dls.cpp:107:(.text+0x22e): undefined reference to `__cxa_end_catch'
/usr/bin/ld: /vcpkg/buildtrees/fluidsynth/src/v2.5.2-8791e69fca.clean/src/sfloader/fluid_dls.cpp:107:(.text+0x24d): undefined reference to `__cxa_end_catch'
/usr/bin/ld: /vcpkg/buildtrees/fluidsynth/src/v2.5.2-8791e69fca.clean/src/sfloader/fluid_dls.cpp:108:(.text+0x262): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
```

**Comment by dg0yt** [comment]
A C++ source in a target should be enough to make it use the C++ linker. Strange if it doesn't work.
(Most trouble we dealt with in the past was optional transitive stuff, like lerc->tiff->whatever or icu->libxml2->whatever, and that's where I put implicit C++ link libs in leaf pkgconfig files.)

**Comment by dg0yt** [comment]
IIUC it is in gstreamer's use of fluidsynth. So it is the "transitives stuff" case. 
Either make fluidsynth export c++ link libs like we do elsewhere (solution for all reverse dependencies, can be coupled to fluidsynth features), or add an empty c++ source to the gstreamer target (specific fix, can be coupled to gstreamer features.)

**Comment by dg0yt** [comment]
I'm unable to reproduce the x64-linux issue, even with `vcpkg x-set-installed gstreamer[core,fluidsynth]`.
CI: `/usr/bin/cc -fPIC -g  -o libgstreamer-full-1.0.so ...` 
mine: `/usr/bin/c++ -fPIC -g  -o libgstreamer-full-1.0.so ...`

**Comment by BillyONeal** [comment]
> I'm unable to reproduce the x64-linux issue, even with `vcpkg x-set-installed gstreamer[core,fluidsynth]`.

It repros for me :( . But hopefully you fixed it anyway!

**Comment by Neumann-A** [comment]
> gstreamer target 

There is probably a way to modify the target without adding an empty cpp file. Yeah meson as a [link_language](https://mesonbuild.com/Reference-manual_functions_both_libraries.html#both_libraries_link_language) parameter.

**Comment by BillyONeal** [comment]
> There is probably a way to modify the target without adding an empty cpp file. Yeah meson as a [link_language](https://mesonbuild.com/Reference-manual_functions_both_libraries.html#both_libraries_link_language) parameter.

In this case I think it's fluidsynth's fault since they added the C++ to the situation.

**Comment by BillyONeal** [comment]
> The other failures here are also FFmpeg related. For example:
> 
> ```cmake
>    Creating library gstreamer-full-1.0.lib and object gstreamer-full-1.0.exp
> chromaprint.lib(fft_lib_avtx.cpp.obj) : error LNK2019: unresolved external symbol av_tx_init referenced in function "public: __cdecl chromaprint::FFTLib::FFTLib(unsigned __int64)" (??0FFTLib@chromaprint@@QEAA@_K@Z)
> chromaprint.lib(fft_lib_avtx.cpp.obj) : error LNK2019: unresolved external symbol av_tx_uninit referenced in function "public: __cdecl chromaprint::FFTLib::~FFTLib(void)" (??1FFTLib@chromaprint@@QEAA@XZ)
> chromaprint.lib(fft_lib_avtx.cpp.obj) : error LNK2019: unresolved external symbol av_malloc referenced in function "public: __cdecl chromaprint::FFTLib::FFTLib(unsigned __int64)" (??0FFTLib@chromaprint@@QEAA@_K@Z)
> chromaprint.lib(fft_lib_avtx.cpp.obj) : error LNK2019: unresolved external symbol av_free referenced in function "public: __cdecl chromaprint::FFTLib::~FFTLib(void)" (??1FFTLib@chromaprint@@QEAA@XZ)
> ```
> 
> This is caused by `chromaprint` doing:
> 
> ```cmake
> if(USE_AVTX)
>   set(chromaprint_SOURCES fft_lib_avtx.cpp ${chromaprint_SOURCES})
>   set(chromaprint_LINK_LIBS
>     ${FFMPEG_LIBAVUTIL_LIBRARIES}
>   )
>   include_directories(
>     ${FFMPEG_LIBAVUTIL_INCLUDE_DIRS}
>   )
> endif(USE_AVTX)
> ```
> 
> but the FFmpeg 8.x CMake bindings no longer set `FFMPEG_LIBAVUTIL_LIBRARIES` so this ends up setting `chromaprint_LINK_LIBS` to empty string.
> 
> It's not clear if the right fix is to try to change FFmpeg's bindings to set those again.

Actually this seems to be a typo in https://github.com/microsoft/vcpkg/pull/45133/ ; it needed to use `@`s

**Comment by dg0yt** [comment]
> Actually this seems to be a typo in #45133 ; it needed to use `@`s

No, this was broekn in #48567. (And the formatting, too.)

**Comment by BillyONeal** [comment]
> No, this was broekn in #48567. (And the formatting, too.)

Ah, agreed!

**Review by vicroms — APPROVED** [review]
LGTM

**Comment by BillyONeal** [comment]
I cherry-picked https://github.com/microsoft/vcpkg/pull/49918 here which hopefully fixes the gtk3[introspection] failures.
