### ISSUE TITLE
[curl] build failure

### ISSUE THREAD

**Issue by AenBleidd** [microsoft/vcpkg#21635]
Failed to link with openssl on armv6 after #20289
```
ssl/ssl_cert.c:60: error: undefined reference to '__atomic_store'
ssl/ssl_cert.c:84: error: undefined reference to '__atomic_store'
include/internal/refcount.h:50: error: undefined reference to '__atomic_fetch_sub_4'
ssl/ssl_lib.c:695: error: undefined reference to '__atomic_store'
include/internal/refcount.h:50: error: undefined reference to '__atomic_fetch_sub_4'
include/internal/refcount.h:50: error: undefined reference to '__atomic_fetch_sub_4'
ssl/ssl_lib.c:3042: error: undefined reference to '__atomic_store'
include/internal/refcount.h:50: error: undefined reference to '__atomic_fetch_sub_4'
crypto/bio/bio_lib.c:689: error: undefined reference to '__atomic_load'
crypto/bio/bio_lib.c:689: error: undefined reference to '__atomic_load'
crypto/engine/eng_ctrl.c:133: error: undefined reference to '__atomic_load'
crypto/threads_pthread.c:166: error: undefined reference to '__atomic_is_lock_free'
clang50++: error: linker command failed with exit code 1 (use -v to see invocation)
```
Reference: https://github.com/BOINC/boinc/runs/4305481171?check_suite_focus=true

**Comment by Osyotr** [comment]
It looks like you use ancient version of gcc.

**Comment by AenBleidd** [comment]
It's from Android NDK 15-c, the latest one that supports armv6.

**Comment by AenBleidd** [comment]
But there was nothing changed on openssl side, only port script was changed

**Comment by AenBleidd** [comment]
Ok, that's smth happened on my side, and that particular PR is valid. I'm closing this and will continue to look for an error locally.
Sorry for disturbing you.

**Comment by AenBleidd** [comment]
Ok, reopening this. This issue happens after this PR: #21554
Not sure what exactly is wrong, will try to debug it but maybe someone will have an idea about it.
P.S. when building my software with openssl + curl **without** vcpkg using the same versions of these dependent libraries - no issue happens, so it's definitely smth wrong with this port

**Comment by AenBleidd** [comment]
@dg0yt, do you have any idea what's wrong with this port?

**Comment by dg0yt** [comment]
Googling for this error with NDK points to `-latomic`.

**Comment by AenBleidd** [comment]
`-latomic` is correctly passed when linking. I assume there is an issue with exported targets, but I'm not sure. I plan to revert you changes and add them piece by piece to find a place that is not correct

**Comment by AenBleidd** [comment]
Additional logs are here: https://github.com/BOINC/boinc/pull/4587

**Comment by AenBleidd** [comment]
@dg0yt, after I reverted this patch only, everything works as expected:
https://github.com/dg0yt/vcpkg/blob/a6ffdfe2eea8f5495a742aa72e67d1cdb303be8c/ports/curl/0023-fix-static-libs-export.patch
Could you please fix it?

**Comment by AenBleidd** [comment]
@BillyONeal, could you please also take a look at this since you were the one who merged this ^^
I don't know what was the Intension of this commit https://github.com/microsoft/vcpkg/pull/21554/commits/0f7f6f48878fd11172e12e4556a01f610d83da3c but after I reverted it, I still have successful builds for linux and windows (and fixed android).

**Comment by dg0yt** [comment]
@AenBleidd IIUC you see a boinc build error, not a port curl build error?

> I don't know what was the Intension of this commit [0f7f6f4](https://github.com/microsoft/vcpkg/commit/0f7f6f48878fd11172e12e4556a01f610d83da3c) but after I reverted it, I still have successful builds for linux and windows (and fixed android).

It is documented in the PR #21554:
> Changes exported dependency '/.../libz.a' into '-lz' etc. (Fixes undesired inclusion of libz.a into libspatialite.a, breaking linking libspatialite-tools. (Similar to what is described for libintl.a in https://sourceware.org/bugzilla/show_bug.cgi?id=27297.) 

So reverting the change doesn't fail for you because you are using libcurl directly. But it won't pass vcpkg CI.

Now you observe an unexpected side effect of this change. The question is: what is broken? Is it curl at all, or does the change only uncover another problem?

I think I managed to find [the relevant build logs from your failed build](https://github.com/BOINC/boinc/suites/4446942956/artifacts/117966666), but I do not have access to similar logs from a successful build (before this change). You might provide more direct links if you want assistance.
I'm also unable to build in your environment, but *you* might modify the patch in the following ways
- to show the matched string and the substitution.
- to add `\$` to the end of the match pattern (it is really missing).

From your `config.log`:
~~~
LIBCURL='-L/home/runner/work/boinc/boinc/3rdParty/android/vcpkg/installed/armv6-android/lib/pkgconfig/../../lib -lcurl -lssl -lcrypto -ldl -pthread -lz -latomic'
~~~
`LIBCURL` looks healthy AFAICT.

My guess is that we there is a (valid) substition for libssl.a and libcrypto.a, and it is these libraries which need `-latomic` (for some platforms). Your configuration has ssl, crypto and atomic from curl (see above), and ssl+crypto from you configuration *after* `-latomic. From your `config.log`:
~~~
BOINC_EXTRA_LIBS=' -L/home/runner/work/boinc/boinc/3rdParty/android/vcpkg/installed/armv6-android/lib/pkgconfig/../../lib -lcurl -lssl -lcrypto -ldl -pthread -lz -latomic -lssl -lcrypto   -ldl -lz'
~~~

**Comment by AenBleidd** [comment]
@dg0yt,
>  IIUC you see a boinc build error, not a port curl build error?

exactly, it fails to build port that uses `curl` as a dependency, and fails on linking stage.

> The question is: what is broken? Is it curl at all, or does the change only uncover another problem?

I have no answer for this, but I assume, it just uncovers some other problem.

> but I do not have access to similar logs from a successful build (before this change)

I save no logs for successful builds, but I might provide one for you with the reverted change.

> I'm also unable to build in your environment, but you might modify the patch in the following ways

I'll try to patch as you suggested and show you the result. You can watch it in this test PR: https://github.com/BOINC/boinc/pull/4587

**Comment by AenBleidd** [comment]
Logs for failed (with patch): https://github.com/BOINC/boinc/suites/4457134694/artifacts/118386867

**Comment by AenBleidd** [comment]
```
-- Found: /home/runner/work/boinc/boinc/3rdParty/android/vcpkg/installed/armv6-android/lib/libssl.a
-- Matched: ssl
-- Found: /home/runner/work/boinc/boinc/3rdParty/android/vcpkg/installed/armv6-android/lib/libcrypto.a
-- Matched: crypto
-- Found: dl
-- Found: -pthread
-- Found: /home/runner/work/boinc/boinc/3rdParty/android/vcpkg/installed/armv6-android/lib/libz.a
-- Matched: z
```
Looks like full path is essential somehow in this case....

**Comment by AenBleidd** [comment]
Logs for successful build (still with patch bit `_lib` is not modified: https://github.com/BOINC/boinc/suites/4457432243/artifacts/118399050

**Comment by AenBleidd** [comment]
Ok, we fixed it with the next hack: https://github.com/BOINC/boinc/pull/4590.

Issue can be closed.
