### ISSUE TITLE
Error linking vcpkg cURLpp

### ISSUE THREAD

**Issue by Omegastick** [microsoft/vcpkg#9795]
**Describe the bug**
When linking cURLpp provided by vcpkg in Linux on Github Actions, there are errors.

There is a [known issue](https://stackoverflow.com/questions/33420631/link-errors-with-curlpp) with the apt provided version of cURLpp that has the same errors. Building with vcpkg shouldn't have these errors, though.

Building cURLpp from source normally (without vcpkg) doesn't have these errors.

**Environment**
- OS: Ubuntu 18.04 on Github Actions
- Compiler: g++-9

**To Reproduce**
1. ./vcpkg install curlpp
2. Add the following files to a folder:

`CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.15.0)
project(curlpp_test_project)

find_package(unofficial-curlpp CONFIG REQUIRED)
add_executable(curlpp_test curlpp_test.cpp)
target_link_libraries(curlpp_test PRIVATE unofficial::curlpp::curlpp)
```

`curlpp_test.cpp`:
```cpp
#include <list>
#include <string>

#include <curlpp/cURLpp.hpp>
#include <curlpp/Easy.hpp>
#include <curlpp/Options.hpp>

int main(int /*argc*/, char * /*argv*/ []) {
    cURLpp::initialize();
    curlpp::Easy request;
    request.setOpt(new curlpp::options::Url("http://asd.com"));
    std::list<std::string> header; 
    header.push_back("Content-Type: application/octet-stream"); 
    request.setOpt(new curlpp::options::HttpHeader(header));
    request.perform();
    cURLpp::terminate();
}
```

3. `mkdir build && cd build && cmake .. && cmake --build .`

**Expected behavior**
Executable builds without error.

**Failure logs** 
```
CMakeFiles/curlpp_test.dir/curlpp_test.cpp.o:curlpp_test.cpp:function curlpp::Option<std::list<std::string, std::allocator<std::string> > >::updateMeToOption(curlpp::OptionBase const&): error: undefined reference to 'curlpp::internal::SList::operator std::list<std::string, std::allocator<std::string> >()'
CMakeFiles/curlpp_test.dir/curlpp_test.cpp.o:curlpp_test.cpp:function curlpp::Option<std::list<std::string, std::allocator<std::string> > >::updateMeToOption(curlpp::OptionBase const&): error: undefined reference to 'curlpp::internal::SList::operator=(std::list<std::string, std::allocator<std::string> > const&)'
CMakeFiles/curlpp_test.dir/curlpp_test.cpp.o:curlpp_test.cpp:function curlpp::Option<std::list<std::string, std::allocator<std::string> > >::updateMeToOption(curlpp::OptionBase const&): error: undefined reference to 'curlpp::internal::SList::SList(std::list<std::string, std::allocator<std::string> > const&)'
CMakeFiles/curlpp_test.dir/curlpp_test.cpp.o:curlpp_test.cpp:function curlpp::OptionTrait<std::list<std::string, std::allocator<std::string> >, (CURLoption)10023>::clone() const: error: undefined reference to 'curlpp::internal::SList::operator std::list<std::string, std::allocator<std::string> >()'
CMakeFiles/curlpp_test.dir/curlpp_test.cpp.o:curlpp_test.cpp:function curlpp::OptionTrait<std::list<std::string, std::allocator<std::string> >, (CURLoption)10023>::clone() const: error: undefined reference to 'curlpp::internal::SList::SList(std::list<std::string, std::allocator<std::string> > const&)'
CMakeFiles/curlpp_test.dir/curlpp_test.cpp.o:curlpp_test.cpp:function main: error: undefined reference to 'curlpp::internal::SList::SList(std::list<std::string, std::allocator<std::string> > const&)'
```

**Additional context**
It's worth noting that it seems to build fine on a Ubuntu 16.04 development machine I have. That might have another cURLpp library lying around though.

**Comment by NancyLi1013** [comment]
Hi @Omegastick 

Thanks for posting this issue.
Sorry for the late reply first.

I try to build it on Ubuntu 18.04 with gcc 7.5.0 and I cannot reproduce it.
Could you help check if you installed these libs on your local machine?
```
apt-get install libcurl4-openssl-dev
apt-get install libcurlpp-dev
```

**Comment by Omegastick** [comment]
I also can't reproduce it anymore. Closing this.
