### ISSUE TITLE
[colmap] Build error on x64-windows

### ISSUE THREAD

**Issue by Samwise2310** [microsoft/vcpkg#46404]
` Copy issue body from C:/Users/samad/vcpkg/installed/vcpkg/issue_body.md `

I am receiving this error message when I run `C:\Users\samad\vcpkg>.\vcpkg install colmap[cuda,tests]:x64-windows`

```
error: building colmap:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle colmap:x64-windows: 4.8 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[colmap]+Build+error+on+x64-windows&body=Copy%20issue%20body%20from%20C%3A%2FUsers%2Fsamad%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
You can also submit an issue by running (GitHub CLI must be installed):
  "C:\Program Files\GitHub CLI\gh.exe" issue create -R microsoft/vcpkg --title "[colmap] Build failure on x64-windows" --body-file C:/Users/samad/vcpkg/installed/vcpkg/issue_body.md
Completed submission of sqlite3[core,json1]:x64-windows@3.50.2 to 1 binary cache(s) in 507 ms
```
Here's by log file: [install-x64-windows-dbg-out.log](https://github.com/user-attachments/files/21202776/install-x64-windows-dbg-out.log)

Here is everything my console spit out after running the command: [Samwise2310_colmap_vcpkg_error_consoleOutput.txt](https://github.com/user-attachments/files/21202802/Samwise2310_colmap_vcpkg_error_consoleOutput.txt)

I have updated to the latest version of CUDA (12.9.1), I made sure everything was up to date with `git pull` and `vcpkg update`, 

Any suggestions would be greatly appreciated!!

**Comment by autoantwort** [comment]
From your log output: C:\Users\samad\vcpkg\installed\x64-windows\include\gtest/internal/gtest-port.h(273): fatal error C1189: #error:  C++ versions less than C++17 are not supported.

**Comment by aphungng** [comment]
> From your log output: C:\Users\samad\vcpkg\installed\x64-windows\include\gtest/internal/gtest-port.h(273): fatal error C1189: #error: C++ versions less than C++17 are not supported.

Hi, I don't know if the author solved this issue, but I have the exaxct same one. I noticed the error you listed from the log output, but can't seem to find out how to solve it. Tried downgrading MSVC to 14.32.31326, to run it with MSVC 14.44.35112, but both of these options throw out this error. Tried to force the use of C++17 via environment variables, but it isn't taken into account. Would you have any idea of what would be a solution/workaround ?

**Comment by vigneshrk29** [comment]
Hi, sorry, I am getting the same error. Has anyone found a fix for it? I am using MSVC 14.44.35207

**Comment by trancenoid** [comment]
Same issue, please advice

**Comment by vigneshrk29** [comment]
Hi, I got it working with CUDA 12.8, Python 3.10, and MSVC version 14.44.35207. I followed the instructions in the nerfstudio website (https://docs.nerf.studio/quickstart/custom_dataset.html), specifically running the bat. There are pre-compiled versions of COLMAP which can also be used. Other issues I had was having a space in my folder directory (with the error identifying as laplace compilation error).

**Comment by trancenoid** [comment]
Thanks for the link, solved my issue. But its not MSVC or the bootstrap.bat but the build modifier flags. The problem if you notice is the GTest build fails if we use `.\vcpkg install colmap[cuda,tests]:x64-windows` because we are also building the tests. But the one in nerfstudio only compiles cuda. That is why it works. 
So the solution is to just build using `.\vcpkg install colmap[cuda]:x64-windows`
