### ISSUE TITLE
How do i install vtk 8.2.0 via vcpkg 

### ISSUE THREAD

**Issue by e-sauvage** [microsoft/vcpkg#14040]
Hey guys, 

i need help with installing vtk v8.2.0 via vcpkg. I don't know how to get the 8.2.0 version installed. 
Can someone explain it step by step for me? (for newbies please)

**Comment by PhoebeHui** [comment]
@e-sauvage, you can try following steps?

1. git clone https://github.com/microsoft/vcpkg
2. cd ./vcpkg
3. git checkout f2e9ef7f259843e116453bbabb7bcc2b13246f13
4. ./bootstrap-vcpkg.bat
5. ./vcpkg install vtk:x64-windows

**Comment by e-sauvage** [comment]
@PhoebeHui 

no i am getting this:

`Computing installation plan...
Error: while parsing the Binary Paragraph for boost-vcpkg-helpers:x64-windows
Error: There are invalid fields in the control file of boost-vcpkg-helpers:x64-windows
The following fields were not expected:

    Port-Version

This is the list of valid fields (case-sensitive):

    Source
    Version
    Description
    Maintainer
    Build-Depends
    Homepage
    Type
    Supports

Different source may be available for vcpkg. Use .\bootstrap-vcpkg.bat to update.
`

**Comment by PhoebeHui** [comment]
@e-sauvage, do you create a new clone? if not, please create a new one instead.

**Comment by e-sauvage** [comment]
> @e-sauvage, do you create a new clone? if not, please create a new one instead.

ok i used the same directory. I will create a new one and let you know.

**Comment by e-sauvage** [comment]
> @e-sauvage, do you create a new clone? if not, please create a new one instead.

I am getting still the same error. Its not working.

**Comment by PhoebeHui** [comment]
Could do you also clean the archives? it may use the one you built for previous vcpkg instance.

I tried it locally, I can't repro this issue.

**Comment by e-sauvage** [comment]
> Could do you also clean the archives? it may use the one you built for previous vcpkg instance.
> 
> I tried it locally, I can't repro this issue.

Which archives do you mean? I've created a new folder in C: vcpkg-2 cloned vcpkg into it and than i did the steps you listed up.
Is there any problem with vs version or python or something?

The main problem is, that i am getting errors with cmake `fatal error C1083: Datei (Include) kann nicht geöffnet werden: "vtkObject.h":`

I read somewhere, that the 9er Version of vtk causes problems like that with pcl. So i need the 8.2er Version. On my other system its working with vtk 8.2

**Comment by PhoebeHui** [comment]
Could you attach the output after execute ./vcpkg install vtk:x64-windows here?

**Comment by e-sauvage** [comment]
> Could you attach the output after execute ./vcpkg install vtk:x64-windows here?

Ok i think i solved the problem. I created an env var for the vcpkg-root. I didn't know that it uses this also for installing something.

**Comment by PhoebeHui** [comment]
I see, you can try again, it should has no issue to build the vtk, it already built successfully in my local machine.
