### PR TITLE
[libxml2] Add iconv and charset linkage in vcpkg-cmake-wrapper on osx

### LINKED ISSUE #11001: [libxml2] (OSX) Dependent ports fail due to missing iconv linkage
**Host Environment**
- OS: OSX
- Compiler: revision

**Failure logs** 
```
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _xmlNanoFTPCheckResponse in libxml2.a(nanoftp.c.o)
      _xmlNanoFTPCloseConnection in libxml2.a(nanoftp.c.o)
      _xmlNanoFTPList in libxml2.a(nanoftp.c.o)
      _xmlNanoFTPGet in libxml2.a(nanoftp.c.o)
  "_iconv", referenced from:
      _xmlIconvWrapper in libxml2.a(encoding.c.o)
  "_iconv_close", referenced from:
      _xmlFindCharEncodingHandler in libxml2.a(encoding.c.o)
      _xmlCharEncCloseFunc in libxml2.a(encoding.c.o)
  "_iconv_open", referenced from:
      _xmlFindCharEncodingHandler in libxml2.a(encoding.c.o)
ld: symbol(s) not found for architecture x86_64
```

**Additional context**
the vcpkg-cmake-wrapper.cmake in libxml2 must be changed to also add the required dependencies on OSX. Observed in build failure of on OSX CI in https://github.com/microsoft/vcpkg/pull/10770

Missing symbol `___darwin_check_fd_set_overflow` might be an infrastructure/XCode bug or requires a rebuild of libxml?

### PR DESCRIPTION
**Pull request by Neumann-A**
closes #11001
makes #10770 work on osx

### CODE REVIEW

File: ports/libxml2/vcpkg-cmake-wrapper.cmake [hunk 1]
```diff
@@ -2,24 +2,25 @@ _find_package(${ARGS})
...
-        list(APPEND LIBXML2_LIBRARIES
-            debug ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug/lib/libiconv.lib
-            optimized ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libiconv.lib
-            debug ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug/lib/libcharset.lib
-            optimized ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libcharset.lib
-            ws2_32)
+    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
+        list(APPEND LIBXML2_LIBRARIES m)
+    else()
+        list(APPEND LIBXML2_LIBRARIES ${ICONV_LIBRARIES} ${CHARSET_LIBRARIES})
```
Comment (NancyLi1013) [inline ports/libxml2/vcpkg-cmake-wrapper.cmake:18]: Is `iconv `only required on Windows and osx platform?

**Review by NancyLi1013 — CHANGES_REQUESTED** [review]

File: ports/libxml2/vcpkg-cmake-wrapper.cmake [hunk 2]
```diff
@@ -2,24 +2,25 @@ _find_package(${ARGS})
...
-
+    include(SelectLibraryConfigurations)
+    find_library(ICONV_LIBRARY_DEBUG NAMES iconvd libiconvd iconv libiconv NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug" NO_DEFAULT_PATH)
+    find_library(ICONV_LIBRARY_RELEASE NAMES iconv libiconv NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" NO_DEFAULT_PATH)
+    find_library(ICONV_LIBRARY_RELEASE NAMES iconv libiconv NAMES_PER_DIR PATH_SUFFIXES lib)
+    find_library(CHARSET_LIBRARY_DEBUG NAMES charsetd libcharsetd charset libcharset NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug" NO_DEFAULT_PATH)
+    find_library(CHARSET_LIBRARY_RELEASE NAMES charset libcharset NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" NO_DEFAULT_PATH)
+    find_library(CHARSET_LIBRARY_RELEASE NAMES charset libcharset NAMES_PER_DIR PATH_SUFFIXES lib)
+    select_library_configurations(ICONV)
+    select_library_configurations(CHARSET)
```
[the remark this answers is not in the document]
Comment (Neumann-A) [reply ports/libxml2/vcpkg-cmake-wrapper.cmake:13]: I try to avoid unofficial packages. The correct way would probably be to have pkg-config for iconv here but thats not yet integrated into vcpkg.

File: ports/libxml2/vcpkg-cmake-wrapper.cmake (hunk 1 above)
Comment (Neumann-A) [reply ports/libxml2/vcpkg-cmake-wrapper.cmake:18]: At least it looks like libxml is not linking against iconv on Linux or is linking against a shared version which does not require propagation. The correct fix would probably to make iconv build on all platforms and linking correctly against that.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
@Neumann-A 
Could you please resolve the conflict?

**Comment by strega-nil** [comment]
This looks great! Thanks @Neumann-A :)
