### ISSUE TITLE
[geographiclib] build failure

### ISSUE THREAD

**Issue by johnco3** [microsoft/vcpkg#25195]
**Host Environment**
- OS: Windows 11 x64
- Compiler: Visual Studio 2022 - 17.2.3

**To Reproduce**
`./vcpkg install geographiclib:x64-windows`

I believe the reason the compile fails is due to the version of the compiler.  The author of this library verified that version `17.1.1` does not exhibit this failure and builds successfully.  The normal log output from the `./vcpkg install geographiclib:x64-windows` command is shown below and I also include the log from the `./vcpkg install geographiclib:x64-windows --debug` as an attachment (build.log).

The failure in the debug log (shown as the first log snippet below) seems to indicate insufficient memory - however this machine has 16G of ram and another machine that also shows this error has 32G of ram - so I doubt ram is the problem.  All my machines are using 17.2.3 of Vs 2022 and I do not have access to a machine with an earlier version of the compiler to verify that this is the issue
[build.log](https://github.com/microsoft/vcpkg/files/8885110/build.log)
.

**Failure logs**

```
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:60 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/geographiclib/portfile.cmake:35 (vcpkg_cmake_install)
  scripts/ports.cmake:146 (include)
```

```
[build.log](https://github.com/microsoft/vcpkg/files/8885108/build.log)

PS C:\temp\vcpkg> .\vcpkg.exe install geographiclib:x64-windows
Computing installation plan...
A suitable version of cmake was not found (required v3.22.2). Downloading portable cmake v3.22.2...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-windows-i386.zip -> C:\temp\vcpkg\downloads\cmake-3.22.2-windows-i386.zip
Extracting cmake...
The following packages will be built and installed:
    geographiclib[core]:x64-windows -> 2.1
  * vcpkg-cmake[core]:x64-windows -> 2022-05-10#1
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.2.3). Downloading portable powershell-core v7.2.3...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.2.3/PowerShell-7.2.3-win-x86.zip -> C:\temp\vcpkg\downloads\PowerShell-7.2.3-win-x86.zip
Extracting powershell-core...
Restored 0 packages from C:\Users\jcoffey\AppData\Local\vcpkg\archives in 520.7 us. Use --debug to see more details.
Installing 1/3 vcpkg-cmake:x64-windows...
Building vcpkg-cmake[core]:x64-windows...
-- Installing: C:/temp/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: C:/temp/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: C:/temp/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: C:/temp/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg-port-config.cmake
-- Installing: C:/temp/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/copyright
-- Performing post-build validation
-- Performing post-build validation done
A suitable version of 7zip was not found (required v21.7.0). Downloading portable 7zip v21.7.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z2107-extra.7z -> C:\temp\vcpkg\downloads\7z2107-extra.7z
Extracting 7zip...
Stored binary cache: C:\Users\jcoffey\AppData\Local\vcpkg\archives\b9\b9c5cc0c396dcb1f72445cad3fefa70631ad25593055e3d93c73bfda26591ef9.zip
Elapsed time to handle vcpkg-cmake:x64-windows: 2.677 s
Installing 2/3 vcpkg-cmake-config:x64-windows...
Building vcpkg-cmake-config[core]:x64-windows...
-- Installing: C:/temp/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake
-- Installing: C:/temp/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/vcpkg-port-config.cmake
-- Installing: C:/temp/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\jcoffey\AppData\Local\vcpkg\archives\48\48f6e850b103b8a001ffaa65f9d9aceed645c5f222abd14fd13fc68de95daf4a.zip
Elapsed time to handle vcpkg-cmake-config:x64-windows: 432.4 ms
Installing 3/3 geographiclib:x64-windows...
Building geographiclib[core]:x64-windows...
-- Downloading https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=cfhcable;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=pilotfiber;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=gigenet;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=versaweb;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=ayera;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=netactuate;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=phoenixnap;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=astuteinternet;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=freefr;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=netcologne;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=deac-riga;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=excellmedia;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=iweb;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=jaist;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=jztkft;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=managedway;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=nchc;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=netix;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=ufpr;https://sourceforge.net/projects/geographiclib/files//distrib-C++/GeographicLib-2.1.tar.gz/download?use_mirror=tenet -> GeographicLib-2.1.tar.gz...
-- Extracting source C:/temp/vcpkg/downloads/GeographicLib-2.1.tar.gz
-- Using source at C:/temp/vcpkg/buildtrees/geographiclib/src/efa3bad6a4-8b721f0729.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: C:/temp/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j9
    Working Directory: C:/temp/vcpkg/buildtrees/geographiclib/x64-windows-rel
    See logs for more information:
      C:\temp\vcpkg\buildtrees\geographiclib\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/geographiclib/portfile.cmake:35 (vcpkg_cmake_install)
  scripts/ports.cmake:146 (include)


error: building geographiclib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+geographiclib
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[geographiclib]+Build+error
Include '[geographiclib] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 8e1f46de1 2022-06-10 (30 hours ago)

```

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by dg0yt** [comment]
> ~~~
> See logs for more information:
>       C:\temp\vcpkg\buildtrees\geographiclib\install-x64-windows-rel-out.log

**Comment by johnco3** [comment]
Here is the log you requested - looks like the error indicates:

`mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "bin\TransverseMercatorProj.exe". Access is denied.
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/8885362/install-x64-windows-rel-out.log)
`

**Comment by dg0yt** [comment]
Usually an Anti-Virus thing.

**Comment by johnco3** [comment]
BTW I updated the compiler to Version 17.3.0 Preview 1.1 and the problem seemed to go away.  Unfortunately I am not in a position to test an earlier non-preview version of the compiler to definitively prove that the issue is associated with 17.2.3 however the author of the library sent me his log indicating a successful build using Visual Studio 17.1.1.  The logs below were generated via

```
.\vcpkg\bootstrap-vcpkg.bat
.\vcpkg\vcpkg.exe install geographiclib:x64-windows --debug > build.log
```

[build-success.log](https://github.com/microsoft/vcpkg/files/8891895/build-success.log)
[build-failed.log](https://github.com/microsoft/vcpkg/files/8891907/build-failed.log)

**Comment by Adela0814** [comment]
It looks a file access problem, it seems `bin\TransverseMercatorProj.exe` file locked, antivirus software is often the cause of this problem. If you have this problem again, please disable your antivirus software and try again.
