### ISSUE TITLE
OpenSSL: enable EXPORT_VAR_AS_FN build option for static Windows builds?

### ISSUE THREAD

**Issue by madig** [Microsoft/vcpkg#6098]
I'm building `openssl-windows[core]:x64-windows-static` and am being bitten by by the issue described in https://github.com/openssl/openssl/blob/master/CHANGES#L7808-L7817. VC 2017.something sees this line:

```C
auth_attr_buffer_length = ASN1_item_i2d(
      (ASN1_VALUE *)signer_info->auth_attr, &auth_attr_buffer, &PKCS7_ATTR_SIGN_it);
```
and spits out
```
error C2664: 'int ASN1_item_i2d(ASN1_VALUE *,unsigned char **,const ASN1_ITEM *)': cannot convert argument 3 from 'const ASN1_ITEM *(__cdecl *)(void)' to 'const ASN1_ITEM *'
```
The variable in question is defined globally in crypto/pkcs7/pkcs7.h, as `DECLARE_ASN1_ITEM(PKCS7_ATTR_SIGN)`.

What's weird is that this is an old change and as far as I can tell, all VC targets get the option already. The code compiles fine on Linux (gcc 7.3) and macOS (some clang). Anyone know what's up?

**Comment by madig** [comment]
Oh wait, I got it the wrong way around. The build option is actually on, so I have to say `PKCS7_ATTR_SIGN_it()` instead of `&PKCS7_ATTR_SIGN_it`.
