### PR TITLE
[plplot] Correct control of wxwidgets

### PR DESCRIPTION
**Pull request by BillyONeal**
probably broken by https://github.com/microsoft/vcpkg/pull/21303/

This caused wxwidgets to get set on as far as the upstream build system cares if wxwidgets was built first regardless of the feature setting, which broke in CI with unresolved external symbol errors in wxwidgets' internals.

### CODE REVIEW

**Comment by BillyONeal** [comment]
After this change the wxwidgets feature is still broken, that problem looks like what https://github.com/microsoft/vcpkg/pull/17111 is trying to fix
