### PR TITLE
[date] Update to 3.0.0

### LINKED ISSUE #9082: [date] link/build failure
**Host Environment**
- OS: Windows, Linux, macOS
- Compiler: clang-7, gcc-9, AppleClang 11.0.0 (clang-1100.0.33.8)

**To Reproduce**
`./vcpkg install date`

Add appropriate entries in CMakeLists, e.g.

https://github.com/acgetchell/CDT-plusplus/commit/170f7c36e80daf78ddc89309e90fceb4f470ccb2

**Failure logs** 

Windows:
https://ci.appveyor.com/project/acgetchell/cdt-plusplus/builds/29066845#L1214

Linux:
https://travis-ci.org/acgetchell/CDT-plusplus/jobs/615883747#L3777

macOS:
```
╭─adam@hapkido ~/CDT-plusplus/tools ‹feature/date› 
╰─$ ./build.sh 
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: /Users/adam/vcpkg/installed/x64-osx/include (found version "1.71.0")  
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /Library/Developer/CommandLineTools/usr/bin/c++ compiler.
-- DARWIN_VERSION=19
-- Mac Leopard detected
-- Found GMP: /Users/adam/vcpkg/installed/x64-osx/debug/lib/libgmp.a  
-- Found MPFR: /Users/adam/vcpkg/installed/x64-osx/debug/lib/libmpfr.a  
-- Found Boost: /Users/adam/vcpkg/installed/x64-osx/include (found suitable version "1.71.0", minimum required is "1.48")  
-- Boost include dirs: /Users/adam/vcpkg/installed/x64-osx/include
-- Boost libraries:    
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/adam/CDT-plusplus/build
Scanning dependencies of target initialize
[  6%] Building CXX object CMakeFiles/initialize.dir/src/initialize.cpp.o
[ 13%] Linking CXX executable initialize
[ 13%] Built target initialize
Scanning dependencies of target CDT_test
[ 20%] Building CXX object tests/CMakeFiles/CDT_test.dir/main.cpp.o
[ 26%] Building CXX object tests/CMakeFiles/CDT_test.dir/Ergodic_moves_3_test.cpp.o
[ 33%] Building CXX object tests/CMakeFiles/CDT_test.dir/Foliated_triangulation_test.cpp.o
[ 40%] Building CXX object tests/CMakeFiles/CDT_test.dir/Geometry_test.cpp.o
[ 46%] Building CXX object tests/CMakeFiles/CDT_test.dir/Manifold_test.cpp.o
[ 53%] Building CXX object tests/CMakeFiles/CDT_test.dir/Move_command_test.cpp.o
[ 60%] Building CXX object tests/CMakeFiles/CDT_test.dir/S3ActionTest.cpp.o
[ 66%] Building CXX object tests/CMakeFiles/CDT_test.dir/SphereTest.cpp.o
[ 73%] Building CXX object tests/CMakeFiles/CDT_test.dir/Tetrahedron_test.cpp.o
[ 80%] Building CXX object tests/CMakeFiles/CDT_test.dir/Torus_test.cpp.o
[ 86%] Building CXX object tests/CMakeFiles/CDT_test.dir/Utilities_test.cpp.o
[ 93%] Building CXX object tests/CMakeFiles/CDT_test.dir/VertexTest.cpp.o
[100%] Linking CXX executable CDT_test
Undefined symbols for architecture x86_64:
  "date::current_zone()", referenced from:
      currentDateTime() in Utilities_test.cpp.o
  "date::time_zone::get_info_impl(std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> > >) const", referenced from:
      date::sys_info date::time_zone::get_info<std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >(std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >) const in Utilities_test.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tests/CDT_test] Error 1
make[1]: *** [tests/CMakeFiles/CDT_test.dir/all] Error 2
make: *** [all] Error 2
```

**Additional context**
https://github.com/microsoft/vcpkg/pull/9006

### PR DESCRIPTION
**Pull request by JackBoosY**
Update to version 3.0.0 to fix issue #9082.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Hi @acgetchell, could you test this PR?

Thanks.

**Review by PhoebeHui — APPROVED** [review]

**Comment by yamcenutzer** [comment]
Question:
after updating to 3.0  date offers to use date::tz in cmake as link_library, but that doesn't work. You need to use date::date-tz.
Is that another cmake bug (aliases broken) or is there another way continuing to use date::tz in a cosuming cmake project ?

Thx,

**Comment by JackBoosY** [comment]
@yamcenutzer I think that because the official changed the target name, we should use the new name.

**Comment by yamcenutzer** [comment]
yes, ok,
I was just curious about thuis ALIAS feature of cmake. seems kinda useless to me now

**Comment by acgetchell** [comment]
When I try to use this, with the suggested date::date-tz I get:

```
CMake Error at /Users/adam/vcpkg/scripts/buildsystems/vcpkg.cmake:333 (_add_executable):
  Target "initialize" links to target "Threads::Threads" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:80 (add_executable)
```

This goes away if I remove `date::date-tz`
