### PR TITLE
[wxwidgets] Update to 3.2

### LINKED ISSUE #25741: [wxWidgets] update to 3.2.0
Library name: wxWidgets

New version number: 3.2.0

This new version of wxWidgets include a brand new CMake build system that should make integrating it into the vcpkg build system easier than previous versions.

### PR DESCRIPTION
**Pull request by dg0yt**
Continues #25717. Alternative to #25931. Thanks to @talregev and @DragonJoker.

- #### What does your PR fix?
  Updates wxWidgets to 3.2.0. Resolves #25741.
  Updates the CMake wrapper to make CMake's `FindwxWidgets.cmake` work with 3.2.
  Adds a test for the new exported CMake config to `vcpkg-ci-wxwidgets`.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged, no.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Comment by talregev** [comment]
I will test it with our opensource. Also I will check this issue:
https://github.com/microsoft/vcpkg/issues/25786

Thank you for this PR!

**Comment by talregev** [comment]
Windows is working:
image


Linux we have compilation issue: 
```
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libgtk-3.so: undefined reference to symbol 'XGetWindowAttributes'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libX11.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
https://github.com/BOINC/boinc/pull/4852

Not sure how to solve it.

**Comment by dg0yt** [comment]
> Linux we have compilation issue

The Linux build depends on system libs and pc files.
There is no issue with the `vcpkg-ci-wxwidgets` test port on Ubuntu 18.04. It uses both libs to link an executable.

**Comment by talregev** [comment]
> > Linux we have compilation issue
> 
> The Linux build depends on system libs and pc files. There is no issue with the `vcpkg-ci-wxwidgets` test port on Ubuntu 18.04. It uses both libs to link an executable.

I think it missing -lX11 flag. Also when compile with webview it missing the flags for webview that I add manually. We are using `wx-config --libs`

**Comment by talregev** [comment]
It mean the flags that produce in upstream `wx-config --libs` and vcpkg `wx-config --libs` are different.

**Comment by talregev** [comment]
> > > Linux we have compilation issue
> > 
> > 
> > The Linux build depends on system libs and pc files. There is no issue with the `vcpkg-ci-wxwidgets` test port on Ubuntu 18.04. It uses both libs to link an executable.
> 
> I think it missing -lX11 flag. Also when compile with webview it missing the flags for webview that I add manually. We are using `wx-config --libs`

@dg0yt I solve this problem by adding the `-lX11` flag manually. This is not a blocking issue for this PR. (also this PR make it). 
And should fix it in a different PR. I will open an issue about this.

**Comment by talregev** [comment]
Works on ubuntu 20.04

image

**Comment by talregev** [comment]
This issue remain: "Cannot run wxwidgets on ubuntu 22.04":
https://github.com/microsoft/vcpkg/issues/25786

**Comment by dg0yt** [comment]
> It mean the flags that produce in upstream `wx-config --libs` and vcpkg `wx-config --libs` are different.

Sure. Mostly due to the change in FindGTK3. It is turning `-lX11` into `/usr/lib/x86_64-linux-gnu/libX11.so`. 
This change ensures that libs search paths from the pc files are actually used, not lost.

**Comment by dg0yt** [comment]
> This issue remain: "Cannot run wxwidgets on ubuntu 22.04".

I'm not surprised, as long as the system gtk3 is used.

**Comment by talregev** [comment]
> > It mean the flags that produce in upstream `wx-config --libs` and vcpkg `wx-config --libs` are different.
> 
> Sure. Mostly due to the change in FindGTK3. It is turning `-lX11` into `/usr/lib/x86_64-linux-gnu/libX11.so`. This change ensures that libs search paths from the pc files are actually used, not lost.

So it should also reflected in wx-config. 
I will print both versions in the issue (upstream and vcpkg).

**Comment by talregev** [comment]
> > This issue remain: "Cannot run wxwidgets on ubuntu 22.04".
> 
> I'm not surprised, as long as the system gtk3 is used.

Can you elaborate?

**Comment by talregev** [comment]
Also I want to say thank you for your hard work and continue my PR.

**Comment by dg0yt** [comment]
> > > This issue remain: "Cannot run wxwidgets on ubuntu 22.04".
> > 
> > I'm not surprised, as long as the system gtk3 is used.
> 
> Can you elaborate?

Take libpng and x64-linux (static):
 - Vcpkg wxwidgets (static lib) itself is built against vcpkg libpng (static lib).
 - System gtk (dynamic lib) was built against system libpng (dynamic lib).
 - When linking a program, it is only vcpkg libpng (static lib) which makes it to the link editor command line, and code from this library will end up in the executable.
 - When running the program, the dynamic linker will still load the system libpng (dynamic lib). Now your running process has code from system libpng and from vcpkg libpng, possibly different versions and configurations. When data is passed around between these world, can you be sure that they share the same interpretation of the data?

After looking at `ldd buildtrees/vcpkg-ci-wxwidgets/x64-linux-dbg/main` output, there are more such libs:
z, expat, lzma
Your app itself may add more.

Disclaimer: I have only very basic knowledge on linking and symbols.

**Comment by talregev** [comment]
> > > > This issue remain: "Cannot run wxwidgets on ubuntu 22.04".
> > > 
> > > 
> > > I'm not surprised, as long as the system gtk3 is used.
> > 
> > 
> > Can you elaborate?
> 
> Take libpng and x64-linux (static):
> 
> * Vcpkg wxwidgets (static lib) itself is built against vcpkg libpng (static lib).
> * System gtk (dynamic lib) was built against system libpng (dynamic lib).
> * When linking a program, it is only vcpkg libpng (static lib) which makes it to the link editor command line, and code from this library will end up in the executable.
> * When running the program, the dynamic linker will still load the system libpng (dynamic lib). Now your running process has code from system libpng and from vcpkg libpng, possibly different versions and configurations. When data is passed around between these world, can you be sure that they share the same interpretation of the data?
> 
> After looking at `ldd buildtrees/vcpkg-ci-wxwidgets/x64-linux-dbg/main` output, there are more such libs: z, expat, lzma Your app itself may add more.
> 
> Disclaimer: I have only very basic knowledge on linking and symbols.

Thank you for your detail explanations!
You have more knowledge on linking and symbols than I do.

**Comment by talregev** [comment]
@JackBoosY Can you review?

File: ports/wxwidgets/portfile.cmake [hunk 1]
```diff
@@ -61,17 +56,20 @@ else()
...
     find_program(system_pkg_config NAMES pkg-config)
     if(system_pkg_config)
-        set(ENV{PKG_CONFIG} "${system_pkg_config}")
+        set(PKGCONFIG "${system_pkg_config}")
     endif()
     if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
         list(APPEND OPTIONS -DPKG_CONFIG_ARGN=--static)
     endif()
 endif()
+vcpkg_find_acquire_program(PKGCONFIG)
```
Comment (JackBoosY) [inline ports/wxwidgets/portfile.cmake:72]:
```suggestion
else()
    vcpkg_find_acquire_program(PKGCONFIG)
endif()
```

**Review by JackBoosY — CHANGES_REQUESTED** [review]

File: ports/wxwidgets/portfile.cmake (hunk 1 above)
Comment (dg0yt) [reply ports/wxwidgets/portfile.cmake:72]: Pointless. If `PKGCONFIG` is set, `vcpkg_find_acquire_program(PKGCONFIG)` is a no-op.
And wrong. Because it may be needed if there is no system `pkg-config`.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
No need to test all the features since we have the test port.

**Comment by BillyONeal** [comment]
> The Linux build depends on system libs and pc files. There is no issue with the `vcpkg-ci-wxwidgets` test port on Ubuntu 18.04. It uses both libs to link an executable.

22.04*

**Comment by BillyONeal** [comment]
Yikes! What a mess, thanks for fighting it!
