### ISSUE TITLE
[curl] build failure x86-windows-static after f12d986e6a06e0d761089d672df42511fa2dfe0d

### ISSUE THREAD

**Issue by AenBleidd** [microsoft/vcpkg#12431]
**Host Environment**
- OS: [Windows]
- Compiler: cl.exe 19.26.28806

**To Reproduce**
`./vcpkg install curl[core]:x86-windows-static`

**Failure logs** 
LOCAL_PATH_TO_VCPKG\vcpkg\buildtrees\curl\src\7ff07b0670-12eb9d7696.clean\lib\nonblock.c(89): fatal error C1189: #error:  "no non-blocking method was found/used/set"

**Additional context**
Reverting f12d986e6a06e0d761089d672df42511fa2dfe0d commit solves the issue

**Comment by AenBleidd** [comment]
[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/4921827/config-x64-windows-static-out.log)
[config-x86-windows-static-out.log](https://github.com/microsoft/vcpkg/files/4921828/config-x86-windows-static-out.log)

Looks like the issue is next: 
`-- Performing Curl Test HAVE_IOCTLSOCKET_FIONBIO - Failed`

**Comment by AenBleidd** [comment]
@LilyWangL, were you able to reproduce this issue? I could provide any information you might need

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Sorry I am late. I can't reproduce this issue locally, I cloned a new VCPKG and installed `curl[core]:x86-windows-static` and `curl[core]:x64-windows-static` successfully, I check the config log, and all test `HAVE_IOCTLSOCKET_FIONBIO` is success.

**Comment by AenBleidd** [comment]
@LilyWangL, for me all configurations works except x86-windows-static. Do you have any clue why my log is different from yours?

**Comment by AenBleidd** [comment]
Uploaded all logs
[curl-x86-windows-static-err.zip](https://github.com/microsoft/vcpkg/files/4955440/curl-x86-windows-static-err.zip)

**Comment by AenBleidd** [comment]
It was an antivirus false positive. Closing this
