### ISSUE TITLE
Could not compile vcpkg using Visual Studio 2015 Update 3

### ISSUE THREAD

**Issue by mserg71** [microsoft/vcpkg#10085]
Compilation errors (in parse.h) raised during compilation of vcpkg from master branch

**Environment**
- OS: Windows 10
- Compiler: Microsoft Visual C++ 2015 (Microsoft Visual Studio Community 2015 Version 14.0.25425.01 Update 3)

**Steps to reproduce**
1. git clone https://github.com/Microsoft/vcpkg
2. cd vcpkg
3. bootstrap-vcpkg.bat

**Expected behavior**
vcpkg should be built successfully

**Failure logs** 
j:\>git clone https://github.com/Microsoft/vcpkg
Cloning into 'vcpkg'...
remote: Enumerating objects: 75604, done.
remote: Total 75604 (delta 0), reused 0 (delta 0), pack-reused 75604
Receiving objects: 100% (75604/75604), 20.64 MiB | 1.13 MiB/s, done.
Resolving deltas: 100% (46536/46536), done.
Updating files: 100% (4502/4502), done.

j:\>cd vcpkg

j:\vcpkg>bootstrap-vcpkg.bat

Building vcpkg.exe ...

  pch.cpp
  archives.cpp
  checks.cpp
  chrono.cpp
  cofffilereader.cpp
  downloads.cpp
  enums.cpp
  files.cpp
  hash.cpp
  machinetype.cpp
  strings.cpp
  stringview.cpp
  system.cpp
  system.print.cpp
  system.process.cpp
  binaryparagraph.cpp
  build.cpp
  cmakevars.cpp
  commands.autocomplete.cpp
  commands.buildexternal.cpp
  commands.cache.cpp
  commands.ci.cpp
  commands.contact.cpp
  commands.cpp
  commands.create.cpp
  commands.dependinfo.cpp
  commands.edit.cpp
  commands.env.cpp
  commands.exportifw.cpp
  commands.import.cpp
  commands.integrate.cpp
  commands.list.cpp
  commands.owns.cpp
  commands.porthistory.cpp
  commands.portsdiff.cpp
  commands.search.cpp
  commands.upgrade.cpp
  commands.version.cpp
  commands.xvsinstances.cpp
  dependencies.cpp
  export.cpp
  export.chocolatey.cpp
  globalstate.cpp
  help.cpp
  input.cpp
  install.cpp
  logicexpression.cpp
  metrics.cpp
J:\vcpkg\toolsrc\include\vcpkg/parse.h(114): error C2440: 'return': cannot conv
ert from 'initializer list' to 'vcpkg::Parse::TextRowCol' (compiling source fil
e ..\src\vcpkg\logicexpression.cpp) [J:\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj
]
  J:\vcpkg\toolsrc\include\vcpkg/parse.h(114): note: No constructor could take
  the source type, or constructor overload resolution was ambiguous (compiling
  source file ..\src\vcpkg\logicexpression.cpp)
  packagespec.cpp
J:\vcpkg\toolsrc\include\vcpkg/parse.h(114): error C2440: 'return': cannot conv
ert from 'initializer list' to 'vcpkg::Parse::TextRowCol' (compiling source fil
e ..\src\vcpkg\packagespec.cpp) [J:\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
  J:\vcpkg\toolsrc\include\vcpkg/parse.h(114): note: No constructor could take
  the source type, or constructor overload resolution was ambiguous (compiling
  source file ..\src\vcpkg\packagespec.cpp)
  paragraphparseresult.cpp
  paragraphs.cpp
J:\vcpkg\toolsrc\include\vcpkg/parse.h(114): error C2440: 'return': cannot conv
ert from 'initializer list' to 'vcpkg::Parse::TextRowCol' (compiling source fil
e ..\src\vcpkg\paragraphs.cpp) [J:\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
  J:\vcpkg\toolsrc\include\vcpkg/parse.h(114): note: No constructor could take
  the source type, or constructor overload resolution was ambiguous (compiling
  source file ..\src\vcpkg\paragraphs.cpp)
  parse.cpp
  portfileprovider.cpp
J:\vcpkg\toolsrc\include\vcpkg/parse.h(114): error C2440: 'return': cannot conv
ert from 'initializer list' to 'vcpkg::Parse::TextRowCol' (compiling source fil
e ..\src\vcpkg\parse.cpp) [J:\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
  J:\vcpkg\toolsrc\include\vcpkg/parse.h(114): note: No constructor could take
  the source type, or constructor overload resolution was ambiguous (compiling
  source file ..\src\vcpkg\parse.cpp)
  postbuildlint.buildtype.cpp
  postbuildlint.cpp
  remove.cpp
  sourceparagraph.cpp
  statusparagraph.cpp
  statusparagraphs.cpp
  tools.cpp
  triplet.cpp
  update.cpp
  userconfig.cpp
  vcpkgcmdarguments.cpp
  vcpkglib.cpp
  vcpkgpaths.cpp
  versiont.cpp
  visualstudio.cpp
J:\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you h
ave installed Visual Studio with the Desktop C++ workload and the Windows SDK f
or Desktop C++.
строка:1 знак:4
+ & {& 'j:\vcpkg\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,bootstrap.ps1

**Additional context**
I can successfully compile using the version tagged "2020.01" in github

**Comment by linquize** [comment]
See #10011

**Comment by marcospy** [comment]
Same issue here, I've successfully compiled with VS2015 using the latest (2020.01) release.

**Comment by vicroms** [comment]
I opened a PR to solve this issue, the code changes required are actually quite simple but we are experiencing problems with our CI infrastructure which will delay merging the PR.

You can manually edit the sources to replicate the changes in PR #10126. Just add the missing constructors for TextRowCol:

https://github.com/microsoft/vcpkg/blob/e130ff1c69407c79832db2ee538f13c093679b52/toolsrc/include/vcpkg/textrowcol.h#L5-L13
