### ISSUE TITLE
[curl] link error since 8.20.0

### ISSUE THREAD

**Issue by jackpoz** [microsoft/vcpkg#51543]
### Operating system

Windows 11

### Compiler

MSVC v145 (VS 2026 18.5.2)

### Steps to reproduce the behavior

```Shell
- create a cmake project that depends on curl
- build using VS 2026

Check the "Additional context" section for more detail. Let me know if it's necessary to submit a test project.
```

### Failure logs

1>libcurl-d.lib(rand.c.obj) : error LNK2019: unresolved external symbol BCryptGenRandom referenced in function Curl_win32_random

### Additional context

vcpkg.json configuration for curl
```json
"dependencies": [
          {
            "name": "curl",
            "default-features": false,
            "features": [
              "non-http",
              "openssl"
            ]
          }
        ]
```

curl is referenced in the cmake project like this:
```
find_package(CURL REQUIRED)
target_link_libraries(${PROJECT_NAME} PUBLIC CURL::libcurl)
```

The link error is most likely caused by https://github.com/curl/curl/commit/70a159527c4e0312c556e1e42bc0c98626f276fb , where the code below has been removed
```cpp
#ifdef _MSC_VER
#  pragma comment(lib, "bcrypt.lib")
#endif
```
from `rand.c` , which is the file that throws the link error.

I imagine vcpkg portfile needs to account for this change and link bcrypt.lib

**Comment by dg0yt** [comment]
Thanks for reporting. I will look at bcrypt when I continue https://github.com/microsoft/vcpkg/pull/51597.

**Comment by dg0yt** [comment]
The bcrypt lib is handled by the CMake build system and exported to CMake config, pkg-config, curl-config *for static library linkage*. (Verified with mingw.)
~~~
set_target_properties(CURL::libcurl_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "CURL_STATICLIB"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ZLIB::ZLIB>;\$<LINK_ONLY:bcrypt>;\$<LINK_ONLY:advapi32>;\$<LINK_ONLY:crypt32>;\$<LINK_ONLY:secur32>;\$<LINK_ONLY:ws2_32>;\$<LINK_ONLY:iphlpapi>;\$<LINK_ONLY:CURL::ZLIB>;\$<LINK_ONLY:CURL::win32_winsock>"
)

**Comment by jackpoz** [comment]
Then maybe this happens only when using a vcxproj not built by cmake, with curl as vcpkg dependency in vcpkg.json.

Thanks for the reply, I'll just manually add the lib to the local vcxproj.
