### ISSUE TITLE
vcpkg broken build due to unused variable syntax

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#13094]
**Describe the bug**
vcpkg broken build since 5e164e3dd2b9fbbd68782f4c3c73242918b3c688

 ../src/vcpkg/commands.xvsinstances.cpp:31:16: error: left operand of comma operator has no effect [-Werror=unused-value]
    31 |         (void)(args, paths);
       |                ^~~~
 cc1plus: all warnings being treated as errors

**Environment**
- OS: Ubuntu 20.04
- Compiler: gcc 9.3

**To Reproduce**
cmake -B build -G Ninja
cmake --build build

**Expected behavior**
No error
