### ISSUE TITLE
[libarchive] Missing ZSTD linkage in wrapper for dependent ports

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#11002]
**Failure logs** 
shortened log:
```
archive.lib(archive_write_add_filter_zstd.c.obj) : error LNK2019: unresolved external symbol ZSTD_isError referenced in function archive_compressor_zstd_open
archive.lib(archive_read_support_filter_zstd.c.obj) : error LNK2001: unresolved external symbol ZSTD_isError
archive.lib(archive_write_add_filter_zstd.c.obj) : error LNK2019: unresolved external symbol ZSTD_getErrorName referenced in function drive_compressor
```

**Additional context**
Dependency not correctly handled by port. There seems to be an ENABLE_ZSTD option which is not exposed in the portfile (only checked the fix-zstd.patch for that conclusion -> TODO check CMakeLists.txt). 
Reason for build failure in #10770 (x64-windows-static) https://dev.azure.com/vcpkg/public/_build/results?buildId=34965&view=logs&j=e1398d9f-ede2-5462-d45c-fe1632336682&t=8673dc57-1f38-5bfb-1f77-5a72c5f983aa&l=21
