### ISSUE TITLE
[pcl] _qh_qh symbol unresolved when using pcl::ConcaveHull

### ISSUE THREAD

**Issue by cbuchart** [microsoft/vcpkg#13881]
**Host Environment**
- OS: Windows 10
- Compiler: VS 15.9.27
- vcpkg's tag: 2020.7

**To Reproduce**
`./vcpkg install pcl`

Compile following code

```
#include <pcl/point_types.h>
#include <pcl/pcl_base.h>
#include <pcl/surface/concave_hull.h>

int main()
{
  pcl::PointCloud<PointT>::Ptr points_input(new pcl::PointCloud<PointT>);

  pcl::PointCloud<PointT>::Ptr points_output(new pcl::PointCloud<PointT>);
  pcl::ConcaveHull<PointT> chull;
  chull.setInputCloud (points_input);
  chull.reconstruct(*points_output);
}
```

**Failure logs** 

Following linker error occurs: `error LNK2001: unresolved external symbol _qh_qh`

**Additional context**

I was migrating from manually compiled PCL + QHull an such error never happened.

**Workaround**

I'm able to get the code compiling correctly by disabling the `PCL_NO_PRECOMPILE`:

```
#ifdef PCL_NO_PRECOMPILE
#undef PCL_NO_PRECOMPILE
#endif
#include <pcl/surface/concave_hull.h>
```

**Comment by NancyLi1013** [comment]
Hi @cbuchart 
Thanks for posting this issue.
It seems that `#include <pcl/surface/concave_hull.h>`has not been installed in vcpkg.
I used the project case you provided above and found the errors like this:

```
1>ConsoleApplication5.cpp
1>c:\consoleapplication5\consoleapplication5\consoleapplication5.cpp(11): error C2065: 'PointT': undeclared identifier
1>c:\consoleapplication5\consoleapplication5\consoleapplication5.cpp(11): error C2923: 'pcl::PointCloud': 'PointT' is not a valid template type argument for parameter 'PointT'
1>c:\consoleapplication5\consoleapplication5\consoleapplication5.cpp(11): error C2955: 'pcl::PointCloud': use of class template requires template argument list
1>f:\new\vcpkg\installed\x86-windows\include\pcl\point_cloud.h(180): note: see declaration of 'pcl::PointCloud'
1>c:\consoleapplication5\consoleapplication5\consoleapplication5.cpp(11): error C2512: 'pcl::PointCloud': no appropriate default constructor available
1>c:\consoleapplication5\consoleapplication5\consoleapplication5.cpp(11): error C2514: 'std::shared_ptr<pcl::PointCloud<PointT>>': class has no constructors
1>f:\new\vcpkg\installed\x86-windows\include\pcl\point_cloud.h(428): note: see declaration of 'std::shared_ptr<pcl::PointCloud<PointT>>'
1>c:\consoleapplication5\consoleapplication5\consoleapplication5.cpp(13): error C2065: 'PointT': undeclared identifier
1>c:\consoleapplication5\consoleapplication5\consoleapplication5.cpp(13): error C2923: 'pcl::PointCloud': 'PointT' is not a valid template type argument for parameter 'PointT'
1>c:\consoleapplication5\consoleapplication5\consoleapplication5.cpp(13): error C2955: 'pcl::PointCloud': use of class template requires template argument list
1>f:\new\vcpkg\installed\x86-windows\include\pcl\point_cloud.h(180): note: see declaration of 'pcl::PointCloud'
1>c:\consoleapplication5\consoleapplication5\consoleapplication5.cpp(13): error C2512: 'pcl::PointCloud': no appropriate default constructor available
1>c:\consoleapplication5\consoleapplication5\consoleapplication5.cpp(13): error C2514: 'std::shared_ptr<pcl::PointCloud<PointT>>': class has no constructors
1>f:\new\vcpkg\installed\x86-windows\include\pcl\point_cloud.h(428): note: see declaration of 'std::shared_ptr<pcl::PointCloud<PointT>>'
1>c:\consoleapplication5\consoleapplication5.cpp(14): error C2039: 'ConcaveHull': is not a member of 'pcl'
1>f:\new\vcpkg\installed\x86-windows\include\pcl\pcl_base.h(58): note: see declaration of 'pcl'
1>c:\consoleapplication5.cpp(14): error C2065: 'ConcaveHull': undeclared identifier
1>c:\consoleapplication5\consoleapplication5\consoleapplication5.cpp(14): error C2065: 'PointT': undeclared identifier
1>c:\consoleapplication5\consoleapplication5\consoleapplication5.cpp(14): error C2065: 'chull': undeclared identifier
1>c:\consoleapplication5\consoleapplication5\consoleapplication5.cpp(15): error C2065: 'chull': undeclared identifier
1>c:\consoleapplication5\consoleapplication5\consoleapplication5.cpp(16): error C2065: 'chull': undeclared identifier
1>c:\consoleapplication5\consoleapplication5\consoleapplication5.cpp(16): error C2100: illegal indirection
```

**Comment by cbuchart** [comment]
I'll answer your points:

1. I'm working with the latest tag (2020.07), and PCL does include QHull.
2. Sorry, I forgot to include the typedef `using PointT = pcl::PointXYZ;`.
3. Once applied that I had to solve a couple of extra errors (some `fopen` is unsecure, and an issue where flann doesn't define `pop_t`.

The whole example is:

```
#define _CRT_SECURE_NO_WARNINGS
typedef unsigned long long pop_t;

#include <pcl/point_types.h>
#include <pcl/pcl_base.h>
#include <pcl/surface/concave_hull.h>

int main()
{
  using PointT = pcl::PointXYZ;

  pcl::PointCloud<PointT>::Ptr points_input(new pcl::PointCloud<PointT>);

  pcl::PointCloud<PointT>::Ptr points_output(new pcl::PointCloud<PointT>);

  pcl::ConcaveHull<PointT> chull;
  chull.setInputCloud (points_input);
  chull.reconstruct(*points_output);
}
```

Nevertheless, it seems to be compiling correctly though in my larger codebase is not. I'll check back so it seems there is any other package conflicting.

**Comment by NancyLi1013** [comment]
Thanks for your above details. 
I will try to build the example again to see the new results.

**Comment by NancyLi1013** [comment]
`pcl::ConcaveHull<PointT> chull;`

Seems to be incorrect. 

1>c:\users\source\repos\consoleapplication5\consoleapplication5\consoleapplication5.cpp(19): error C2039: 'ConcaveHull': is not a member of 'pcl'
1>f:\new\vcpkg\installed\x86-windows\include\pcl\pcl_base.h(58): note: see declaration of 'pcl'
1>c:\users\source\repos\consoleapplication5\consoleapplication5\consoleapplication5.cpp(19): error C2065: 'ConcaveHull': undeclared identifier
1>c:\users\v-ruil\source\repos\consoleapplication5\consoleapplication5\consoleapplication5.cpp(19): error C2275: 'PointT': illegal use of this type as an expression
1>c:\users\source\repos\consoleapplication5\consoleapplication5\consoleapplication5.cpp(14): note: see declaration of 'PointT'
1>c:\users\source\repos\consoleapplication5\consoleapplication5\consoleapplication5.cpp(19): error C2065: 'chull': undeclared identifier
1>c:\users\source\repos\consoleapplication5\consoleapplication5\consoleapplication5.cpp(20): error C2065: 'chull': undeclared identifier
1>c:\users\source\repos\consoleapplication5\consoleapplication5\consoleapplication5.cpp(21): error C2065: 'chull': undeclared identifier
1>Done building project "ConsoleApplication5.vcxproj" -- FAILED.

The project like this:

```
#define _CRT_SECURE_NO_WARNINGS
typedef unsigned long long pop_t;

#include <pcl/point_types.h>
#include <pcl/pcl_base.h>
#include <pcl/surface/concave_hull.h>

int main()
{
	using PointT = pcl::PointXYZ;

	pcl::PointCloud<PointT>::Ptr points_input(new pcl::PointCloud<PointT>);

	pcl::PointCloud<PointT>::Ptr points_output(new pcl::PointCloud<PointT>);
	pcl::ConcaveHull<PointT> chull;
	chull.setInputCloud(points_input);
	chull.reconstruct(*points_output);
}
```

**Comment by RisingMichael** [comment]
I've encountered this problem too. Somehow concave_hull.h is not installed with the rest of the pcl library. 
Any news on this?

**Comment by NancyLi1013** [comment]
Hi @cbuchart and @RisingMichael 

Sorry for the long delay.

The installing of `concave_hull.h` requires `qhull`. Currently, there seems something wrong with finding `qhull`. I will look into this issue in these days. Also will update the status here.

**Comment by WangZP10969** [comment]
@NancyLi1013 Are there any new developments? I also tried to install PCL and Qhull, but I did not find pcl\surface\convex_hull.h, which is the header file used by PCL to call Qhull. it doesn’t seem to be installed.

**Comment by NancyLi1013** [comment]
@WangZP10969 

Since the usage of `Qhull `is not correct in `pcl`. You still cannot find `pcl\surface\convex_hull.h` even though you have installed `PCL `and `Qhull `on your machine. Factually, you can see the result that Qhull cannot be found in config log.

I will try to look into this and fix it soon.

**Comment by NancyLi1013** [comment]
Hi all, 
I have submitted a PR #17437 to fix the problem that `qhull ` cannot be found in `pcl`. In this PR, `pcl\surface\convex_hull.h` can be installed in `pcl`.

Can anyone help test if this can work fine for you?

Thanks.

**Comment by WangZP10969** [comment]
@NancyLi1013  I tried your branch and built pcl:x64-windows with it. convex_hull.h do exist in the built file.
![image](https://user-images.githubusercontent.com/47802547/115744785-744cb100-a3c5-11eb-9009-55f0258e9f16.png)

**Comment by RDCH106** [comment]
⚠️ Still broken in release  [2021.05.12](https://github.com/microsoft/vcpkg/releases/tag/2021.05.12)
👀 Proposed [workaround solution](https://github.com/microsoft/vcpkg/pull/18855#issuecomment-961480058) in #17662

**Comment by RDCH106** [comment]
> > ⚠️ Still broken in release
> 
> vcpkg "releases" are not meaningful, particularly now that the tool part is no longer in this repo.

Sorry, I don't understand you... What does it mean?

**Comment by BillyONeal** [comment]
> Sorry, I don't understand you... What does it mean?

It means vcpkg does not really do 'releases'. The entries on the releases page are arbitrary and we don't expect people to use them in normal operation.

Releases may have made sense as a thing when the vcpkg binary (e.g. vcpkg.exe) had its code here, but that code now lives in https://github.com/microsoft/vcpkg-tool
