### PR TITLE
[linux toolchain] Add -latomic for x86 targets

### PR DESCRIPTION
**Pull request by aurora250**
## Summary
  
  On 32-bit x86 Linux, 64-bit atomic operations (std::atomic<uint64_t>)
  require linking against libatomic. The Linux toolchain already appends
  -m32 for x86 targets but omits -latomic, causing link failures.
  
  Example failure (OpenSSL x86-linux):
    undefined reference to `__atomic_compare_exchange'
    undefined reference to `__atomic_load'
  
  ## Root cause
  
  x86 (i686) lacks native 64-bit CAS instructions. The compiler generates
  calls to libatomic helpers, which aren't linked without -latomic.
  
  ## Change
  
  scripts/toolchains/linux.cmake: added -latomic alongside the existing -m32
  in VCPKG_LINKER_FLAGS for the x86 branch (line 31).
  
  ## Verification
  
  - [x] OpenSSL x86-linux builds successfully with this change
  - [x] `gcc -m32 -latomic` linking confirmed working on Ubuntu 24.04

### CODE REVIEW

**Comment by MichalPetryka** [comment]
> x86 (i686) lacks native 64-bit CAS instructions.

That's not correct, x86 has CMPXCHG8B since i586.

**Comment by aurora250** [comment]
> > x86 (i686) lacks native 64-bit CAS instructions.
> 
> That's not correct, x86 has CMPXCHG8B since i586.

Yes, you are right in theory, but OpenSSL can not find __atomic_compare_exchange in ubuntu 22.04 when vcpkg try to compile x86-linux version without link atomic library, and also some warnings shows than atomic operation alignment mismatch in x86.



And this is the full openssl compilation log.

[build-x86-linux-dbg-err.log](https://github.com/user-attachments/files/27586848/build-x86-linux-dbg-err.log)

Full vcpkg manifist log is as follows.

[vcpkg-manifest-install.log](https://github.com/user-attachments/files/27586898/vcpkg-manifest-install.log)

I just rollback my vcpkg to version 99a97de2cb371449d4fb9dc970f2ac562d689ec2 which is the version before I make this change and try to compile it again and failed with the same error. I think it is not a coincidence.

It reminds me of this issue in openssl repo: https://github.com/openssl/openssl/issues/26537

**Comment by aurora250** [comment]
I just think this change place is not good, but this is the temp change for quick fix.

**Comment by dg0yt** [comment]
IMO a global toolchain change is not the right solution for a specific openssl problem, and the exe linker flags are not the right place for an additional link library.

**Comment by aurora250** [comment]
> IMO a global toolchain change is not the right solution for a specific openssl problem, and the exe linker flags are not the right place for an additional link library.

You are right, I just want to comfirm this prblem is not caused by my environment. Does this problem occured in your environment?

**Comment by vicroms** [comment]
We have [closed this PR due to inactivity](https://learn.microsoft.com/vcpkg/contributing/maintainer-guide#close-inactive-prs). Please create a new PR if you're still interested in getting these changes merged.

This action was performed automatically.
