### ISSUE TITLE
Poco[MySQL] does not build with MySQL 8.0+

### ISSUE THREAD

**Issue by nnmm79** [microsoft/vcpkg#6740]
From quick google search it appers that the problem is that in new version of mySQL they removed my_bool tape and MYSQL_SECURE_AUTH option, but Poco is still refereencing both of them.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3247745/install-x64-windows-dbg-out.log)

-------------------------------
  Package: poco:x64-windows
  Vcpkg version: 2018.11.23-nohash
Error:
C:\Lib2017\vcpkgn\buildtrees\poco\src\e82f9efd5e-994c9296b6\SQL\MySQL\include\Poco/SQL/MySQL/ResultMetadata.h(62,14): error C2065:  'my_bool': undeclared identifier (compiling source file C:\Lib2017\vcpkgn\buildtrees\poco\src\e82f9efd5e-994c9296b6\SQL\MySQL\src\ResultMetadata.cpp) [C:\Lib2017\vcpkgn\buildtrees\poco\x64-windows-dbg\SQL\MySQL\SQLMySQL.vcxproj]

**Comment by PhoebeHui** [comment]
@nnmm79, thanks for posting this issue!

MySQL header included by Poco, see 
https://github.com/pocoproject/poco/blob/develop/SQL/MySQL/include/Poco/SQL/MySQL/ResultMetadata.h#L62, so I think Poco need to update the header to new version.

I got vcpkg latest revision and build poco with vs2019 16.2.0 preview 2.0, it installed successfully, from you log, I noticed it compile source file C:\Lib2017\vcpkgn\buildtrees\poco\src\e82f9efd5e-994c9296b6\SQL\MySQL\src\ResultMetadata.cpp, but in my outpult log, I didn't find this file compiled, you might need to pull the source from master, could you have a try?

**Comment by PhoebeHui** [comment]
@nnmm79, please reopen this if it still be an issue for you.
