### PR TITLE
[ngspice] Update to rev 34

### PR DESCRIPTION
**Pull request by marekr**
Just released 2 days ago after updating the vcpkg port to rev 33 only recently :/

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@marekr ,Can you take a look
[build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/5924055/build-x86-windows-rel-out.log)

**Comment by marekr** [comment]
> @marekr ,Can you take a look
> [build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/5924055/build-x86-windows-rel-out.log)

It appears `fatal error C1090: PDB API call failed, error code '23':` is a MSVC failure rather than code error

I cannot reproduce the failure locally on a x86-windows triplet build with MSVC 16.8.3

**Review by JonLiu1993 — APPROVED** [review]

**Comment by ras0219-msft** [comment]
LGTM, thanks!
