### ISSUE TITLE
vcpkg build failed after #12049

### ISSUE THREAD

**Issue by mitza-oci** [microsoft/vcpkg#12131]
**Describe the bug**
vcpkg\toolsrc\src\vcpkg\binarycaching.cpp(515,23): error C3668: '`anonymous-namespace'::NugetBinaryProvider
::precheck': method with override specifier 'override' did not override any base class methods

**Environment**
- OS: Windows
- Compiler: VS2019

**To Reproduce**
bootstrap-vcpkg

**Expected behavior**
vcpkg.exe exists

**Comment by mitza-oci** [comment]
Fixed by #12130
