### ISSUE TITLE
[protobuf][grpc] Build error

### ISSUE THREAD

**Issue by Sand2Silicon** [microsoft/vcpkg#25235]
**Host Environment**
- OS: Windows 10 Pro for Workstations
- Compiler: MS Visual Studio Pro 2022 17.2.3

**To Reproduce**

1. Apply manifest file.
2. `./vcpkg install` 

**Manifest File: vcpkg.json**
```{
    "name": "projectFoo",
    "version":  "0.2",
    "dependencies": [
        {
            "name": "protobuf",
            "default-features": true,
            "features": [ "zlib" ]
        },
        {
            "name": "grpc",
            "default-features": true,
            "features": [ "codegen" ]
        }
    ],
    "builtin-baseline": "4ffe8b020f04c3acbd5883566672c19a022c4394",
    "overrides": [
        {
            "name": "protobuf",
            "version": "3.18.0"
        },
                {
            "name": "grpc",
            "version-string": "1.41.0"            
        }
    ]
}
```

**Failure logs**
```
-- Building x64-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: C:/source/workspace/src/ProjectFOO/ExternalDependencies/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j45
    Working Directory: C:/source/workspace/src/ProjectFOO/ExternalDependencies/vcpkg/buildtrees/protobuf/x64-windows-static-dbg
    See logs for more information:
      C:\source\workspace\src\ProjectFOO\ExternalDependencies\vcpkg\buildtrees\protobuf\install-x64-windows-static-dbg-out.log
      C:\source\workspace\src\ProjectFOO\ExternalDependencies\vcpkg\buildtrees\protobuf\install-x64-windows-static-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:106 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  buildtrees/versioning_/versions/protobuf/19c2bf45c235e6126161bae36aa7ff7e1fcda479/portfile.cmake:47 (vcpkg_install_cmake)
  scripts/ports.cmake:145 (include)


Error: Building package protobuf:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+protobuf
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[protobuf]+Build+error
including:
  package: protobuf[core,zlib]:x64-windows-static -> 3.18.0
    vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
    vcpkg-scripts version: fad0644ad 2022-03-14 (3 months ago)
```

_install-x64-windows-static-dbg-out.log_
```
ninja: build stopped: .
```

_install-x64-windows-static-dbg-err.log_
```
ninja: error: mkdir(CMakeFiles/libprotobuf-lite.dir/C_/source/workspace/src/ProjectFOO/ExternalDependencies): No such file or directory
```

**Additional context**
VCPKG Manifest project that relies on pinned-versions of protobuf and grpc. The build has been working for weeks without issue. Unexpectedly started getting 'unresolved external symbol' linking errors related to protobuf yesterday, after hitting 'build' or 'rebuild' in VS. Shelved/Reverted my recent changes but the error persisted. Then tried re-running cmake and vcpkg fails.
- VS linking errors started a few hours after upgrading VS2022 from 17.1.x to 17.2.3. (but it worked for a few hours).
- However I re-opened the project in "VS2022 Preview" that was previously working and hasn't been used in a few months and got the same error.
- Then deleted my project's cmake generated ./build/ folder and ran our `invoke-cmake` powershell script (basically it ensures vcpkg is available and then runs cmake). 
   - Invoke-Cmake was using cmake 3.15.5, and was reporting the Visual Studio 16 (2019) generator
   - I tried re-pointing the script to cmake 3.22.0, and noticed the generator changed to Visual Studio 17, errors messages were the same.
- Next deleted the vcpkg install in a .\ExternalDependencies\ sub-folder of my project. Re-ran invoke-cmake, which would install vcpkg from git, then run cmake for the project. 
- Finally tried running `vcpkg install --debug` and got a very long output. 

Two log files attached, one has output from several runs, one has the long debug output. 
The 'debug' log is the only one I've seen that reported the error being in GRPC instead of Protobuf.
[vcpkg_install_logs.log](https://github.com/microsoft/vcpkg/files/8902967/vcpkg_install_logs.log)
[vcpkg_installdebug-grpc-fail.log](https://github.com/microsoft/vcpkg/files/8902968/vcpkg_installdebug-grpc-fail.log)

**Comment by Sand2Silicon** [comment]
After looking at this issue: https://github.com/microsoft/vcpkg/issues/15399 , and comparing the pathname from @[JackBoosY](https://github.com/JackBoosY) response to my pathnames, I got the same 261 characters; it's possible the real pathnames are too long. (Unfortunately, I had to redact the project name from the logs). **However** it's been working in the current location for over 3 months. There has been no notable change in my directory structure for some time.

I copied the project to a top-level folder `c:\src_test\` and after almost an hour, it succeeded, and then the project then built successfully in Visual Studio. This exists as part of a larger enterprise project though and I can't just change the real path significantly. If it was working, why did it break and how do we fix it the way it was?

It seems I encountered the same error in the same place on March 9, and it mysteriously resolved itself after a few days. We can't just have this transient build-break coming and going though. This is a problem I need to resolve. https://github.com/microsoft/vcpkg/issues/23462

Suggestions? How can I fix or investigate further?

**Comment by JackBoosY** [comment]
Error occurs if the total path exceeds 260 characters, which can be resolved in one of two ways:
1. https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later
2. Add install option `--x-buildtrees-root=<SHORTER_PATH>`

**Comment by Sand2Silicon** [comment]
Thanks for the solution, adding the following to the top of my CMake (before the first project() statement) seems to have worked. I'm going to test this as a long-term fix.
```
# Prevent VCPKG "paths too long"
set (VCPKG_INSTALL_OPTIONS "--x-buildtrees-root=../../vcpkg_buildtrees/")
```

As I said, when I tested running cmake/vcpkg in c:\src_test\ it took nearly an hour, I think it was fully updating my `AppData\Local\vcpkg\archives\`. When I came in today, and went back to my original project directory and ran `.\Invoke-Cmake` it decided to restore packages from there (which it wasn't trying yesterday) and everything magically worked again.

What I surmise is once the `AppData\Local\vcpkg\archives\` is updated somehow, I might be safe for months and only when vcpkg decides to update that archive again and actually builds the ports does it encounter the path-to-long error. Would you agree?

**Comment by JackBoosY** [comment]
@Sand2Silicon Any update involving this port may cause cmake to create several more levels in the binary dir, causing the path length to exceed the limit.
Feel free to close this issue if it's resolved.

**Comment by Sand2Silicon** [comment]
Feature Request: What I wish the error message said: 
> Attempted to create a generated path resolving to: 
> c:\Too\long\path\  ((as you describe here: https://github.com/microsoft/vcpkg/issues/15399#issuecomment-752822241)) 
>
>Path to long error occurs if the total path exceeds 260 characters, which can be resolved in one of two ways:
>https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later
>Add install option --x-buildtrees-root=<SHORTER_PATH> or in CMakeLists.txt before the project statement:
> set (VCPKG_INSTALL_OPTIONS "--x-buildtrees-root=<SHORTER_PATH> ")

None of the logs actually print the full path it is trying to create, so there is no reason a user would suspect a "path to long" error is the problem. I'm not sure if vcpkg has an opportunity to catch this and print a better error than the Ninja log, but it would be nice if it did.

Thank you for the help!!!

**Comment by JackBoosY** [comment]
@Sand2Silicon Not likely now. Sorry.
