### ISSUE TITLE
cannot bootstrap: The module 'scripts' could not be loaded.

### ISSUE THREAD

**Issue by yamcenutzer** [microsoft/vcpkg#584]
powershell -exec bypass scripts\bootstrap.ps1  result:

scripts\bootstrap.ps1 : The module 'scripts' could not be loaded. For more information, run 'Import-Module scripts'.
At line:1 char:1
+ scripts\bootstrap.ps1
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (scripts\bootstrap.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule

**Comment by ras0219-msft** [comment]
Hi yamcenutzer,

Did you run that command from the root of the git clone? "scripts" is intended to refer to the directory `scripts\` in the repository.

**Comment by yamcenutzer** [comment]
Yes I did.

 

I think in the meantime I found that I needed a newer version of nuget.exe The one in the folder wasn’t good enough. Deleting it and starting over helps.

I believe, the same I strue for cmake. I had a fairly recent 3.7.xx installed, but that wasn’t good enough, had to get 3.7.2.

**Comment by alexkaratarakis** [comment]
d5e7a501e907f06ad1e8bb4ffdebce9a29179d2d improves the situation regarding `nuget.exe` by placing it in a folder with the version including in the folder name.
As for `cmake`, the required version was bumped to 3.7.2 because of VS2017 support.

**Comment by alexkaratarakis** [comment]
My understanding is that you managed to get it working. If not, please reopen!

**Comment by yamcenutzer** [comment]
not sure what you did, but now bootstrap fails for something else:
Build FAILED.

       "C:\robinmi\vcpkg\toolsrc\vcpkg.sln" (default target) (1) ->
       "C:\robinmi\vcpkg\toolsrc\vcpkgtest\vcpkgtest.vcxproj" (default target) (7) ->
       (ClCompile target) ->
         c:\robinmi\vcpkg\toolsrc\src\tests_dependencies.cpp(1): fatal error C1083: Cannot open include file: 'CppUnitTest.h': No such file
        or directory [C:\robinmi\vcpkg\toolsrc\vcpkgtest\vcpkgtest.vcxproj]
         c:\robinmi\vcpkg\toolsrc\src\tests_paragraph.cpp(1): fatal error C1083: Cannot open include file: 'CppUnitTest.h': No such file or
        directory [C:\robinmi\vcpkg\toolsrc\vcpkgtest\vcpkgtest.vcxproj]

    0 Warning(s)
    2 Error(s)


The sln file does build in vs2015 though

**Comment by OlafvdSpek** [comment]
> If not, please reopen!

I don't think we can reopen issues..

**Comment by alexkaratarakis** [comment]
@OlafvdSpek You are right, my bad.
@yamcenutzer Can you check the version of VS2017 you have in Help->About?

**Comment by alexkaratarakis** [comment]
After d04e78815a82b52af8b36d14fd68703936199ce3 the test project is not being built as part of `bootstrap.ps1` any more. This should remove this error.

**Comment by yamcenutzer** [comment]
I had completely forgotten about that...

Microsoft Visual Studio Enterprise 2017 RC
Version 15.0.26014.0 D15REL
Microsoft .NET Framework
Version 4.6.01055

I just noticed , it has an update available...
trying now after updating to 15.0.26014.0 D15REL..
nope, still the same error, 
Build FAILED.

       "C:\robinmi\vcpkg\toolsrc\vcpkg.sln" (default target) (1) ->
       "C:\robinmi\vcpkg\toolsrc\vcpkgtest\vcpkgtest.vcxproj" (default target) (6) ->
       (ClCompile target) ->
         c:\robinmi\vcpkg\toolsrc\src\tests_dependencies.cpp(1): fatal error C1083: Cannot open include file: 'CppUnitTest.h': No such file
        or directory [C:\robinmi\vcpkg\toolsrc\vcpkgtest\vcpkgtest.vcxproj]
         c:\robinmi\vcpkg\toolsrc\src\tests_paragraph.cpp(1): fatal error C1083: Cannot open include file: 'CppUnitTest.h': No such file or
        directory [C:\robinmi\vcpkg\toolsrc\vcpkgtest\vcpkgtest.vcxproj]

    0 Warning(s)
    2 Error(s)


git pulled vcpkg again again ..
Updating a4bcf67..d04e788

now it builds also via bootstrap.

**Comment by 4creators** [comment]
Unfortunately latest version not working on my machine both in VS2015 Update 3 and VS2017RC [Microsoft Visual Studio Enterprise 2017 RC, Version 15.0.26020.0 D15REL, Microsoft .NET Framework, Version 4.6.01586] - 

scripts\bootstrap.ps1 : The module 'scripts' could not be loaded. For more information, run 'Import-Module scripts'.
At line:1 char:1

scripts\bootstrap.ps1
  + CategoryInfo          : ObjectNotFound: (scripts\bootstrap.ps1:String) [], CommandNotFoundException
  + FullyQualifiedErrorId : CouldNotAutoLoadModule

**Comment by adam4813** [comment]
This also happens on [appveyor](https://ci.appveyor.com/) when restoring from cache.

**Comment by NancyLi1013** [comment]
@yamcenutzer , does this issue happen on your machine now?
I can't repro it.

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in a year, if it is still an issue, please reopen.
