### PR TITLE
[libpq] Add Secur32.lib and openssl to libpq cmake wrapper

### PR DESCRIPTION
**Pull request by Neumann-A**
Why?
See failed CI `qttools` runs on windows in #18320 
```

FAILED: bin/assistant.exe 
cmd.exe /C "cd . && D:\downloads\tools\cmake-3.20.2-windows\cmake-3.20.2-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=src\assistant\assistant\CMakeFiles\assistant.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1428~1.299\bin\Hostx64\x64\link.exe  @CMakeFiles\assistant.rsp  /out:bin\assistant.exe /implib:src\assistant\assistant\assistant.lib /pdb:bin\assistant.pdb /version:0.0 /machine:x64 /nologo    /debug /subsystem:windows  -DYNAMICBASE -NXCOMPAT  && cd ."
LINK: command "C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1428~1.299\bin\Hostx64\x64\link.exe @CMakeFiles\assistant.rsp /out:bin\assistant.exe /implib:src\assistant\assistant\assistant.lib /pdb:bin\assistant.pdb /version:0.0 /machine:x64 /nologo /debug /subsystem:windows -DYNAMICBASE -NXCOMPAT /MANIFEST /MANIFESTFILE:bin\assistant.exe.manifest" failed (exit code 1120) with the following output:
   Creating library src\assistant\assistant\assistant.lib and object src\assistant\assistant\assistant.exp
libpq.lib(fe-connect.obj) : error LNK2019: unresolved external symbol __imp_FreeCredentialsHandle referenced in function pqDropConnection
libpq.lib(fe-connect.obj) : error LNK2019: unresolved external symbol __imp_DeleteSecurityContext referenced in function pqDropConnection
libpq.lib(fe-auth.obj) : error LNK2019: unresolved external symbol AcquireCredentialsHandleA referenced in function pg_SSPI_startup
libpq.lib(fe-auth.obj) : error LNK2019: unresolved external symbol InitializeSecurityContextA referenced in function pg_SSPI_continue
libpq.lib(fe-auth.obj) : error LNK2019: unresolved external symbol FreeContextBuffer referenced in function pg_SSPI_continue
```

On linux:
See failed CI `qttools` runs on linux in #18320 

```
FAILED: bin/qhelpgenerator 
: && /usr/bin/c++ -fPIC -g -Wl,--gc-sections -Wl,--enable-new-dtags /mnt/vcpkg-ci/installed/x64-linux/debug/lib/objects-Debug/Gui_resources_1/.rcc/qrc_qpdf.cpp.o /mnt/vcpkg-ci/installed/x64-linux/debug/lib/objects-Debug/EglFSDeviceIntegration_resources_1/.rcc/qrc_cursor.cpp.o src/assistant/help/CMakeFiles/Help_resources_1.dir/.rcc/qrc_helpsystem.cpp.o /mnt/vcpkg-ci/installed/x64-linux/debug/lib/objects-Debug/Widgets_resources_1/.rcc/qrc_qstyle.cpp.o /mnt/vcpkg-ci/installed/x64-linux/debug/lib/objects-Debug/Widgets_resources_2/.rcc/qrc_qstyle1.cpp.o /mnt/vcpkg-ci/installed/x64-linux/debug/lib/objects-Debug/Widgets_resources_3/.rcc/qrc_qmessagebox.cpp.o src/assistant/qhelpgenerator/CMakeFiles/qhelpgenerator.dir/qhelpgenerator_autogen/mocs_compilation.cpp.o src/assistant/qhelpgenerator/CMakeFiles/qhelpgenerator.dir/__/shared/collectionconfiguration.cpp.o src/assistant/qhelpgenerator/CMakeFiles/qhelpgenerator.dir/collectionconfigreader.cpp.o src/assistant/qhelpgenerator/CMakeFiles/qhelpgenerator.dir/helpgenerator.cpp.o src/assistant/qhelpgenerator/CMakeFiles/qhelpgenerator.dir/main.cpp.o src/assistant/qhelpgenerator/CMakeFiles/qhelpgenerator.dir/qhelpdatainterface.cpp.o src/assistant/qhelpgenerator/CMakeFiles/qhelpgenerator.dir/qhelpprojectdata.cpp.o src/assistant/qhelpgenerator/CMakeFiles/qhelpgenerator.dir/__/__/__/qt_Gui_QEglFSEmulatorIntegrationPlugin.cpp.o src/assistant/qhelpgenerator/CMakeFiles/qhelpgenerator.dir/__/__/__/qt_Gui_QEglFSX11IntegrationPlugin.cpp.o src/assistant/qhelpgenerator/CMakeFiles/qhelpgenerator.dir/__/__/__/qt_Gui_QGifPlugin.cpp.o src/assistant/qhelpgenerator/CMakeFiles/qhelpgenerator.dir/__/__/__/qt_Gui_QICOPlugin.cpp.o src/assistant/qhelpgenerator/CMakeFiles/qhelpgenerator.dir/__/__/__/qt_Gui_QJpegPlugin.cpp.o src/assistant/qhelpgenerator/CMakeFiles/qhelpgenerator.dir/__/__/__/qt_Gui_QXcbEglIntegrationPlugin.cpp.o src/assistant/qhelpgenerator/CMakeFiles/qhelpgenerator.dir/__/__/__/qt_Gui_QXcbGlxIntegrationPlugin.cpp.o src/assistant/qhelpgenerator/CMakeFiles/qhelpgenerator.dir/__/__/__/qt_Gui_QXcbIntegrationPlugin.cpp.o src/assistant/qhelpgenerator/CMakeFiles/qhelpgenerator.dir/__/__/__/qt_Sql_QPSQLDriverPlugin.cpp.o src/assistant/qhelpgenerator/CMakeFiles/qhelpgenerator.dir/__/__/__/qt_Sql_QSQLiteDriverPlugin.cpp.o -o bin/qhelpgenerator  -Wl,-rpath,::::::::::::::  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6Core.a  lib/libQt6Help.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6Network.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libbrotlidec-static.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libbrotlicommon-static.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libssl.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libcrypto.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6Sql.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/sqldrivers/libqsqlpsql.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/sqldrivers/libqsqlite.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6Sql.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/sqldrivers/libqsqlpsql.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/sqldrivers/libqsqlite.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6Sql.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/sqldrivers/libqsqlpsql.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/sqldrivers/libqsqlite.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libpq.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libpgport.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libpgcommon.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libsqlite3.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6Widgets.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6Gui.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/egldeviceintegrations/libqeglfs-emu-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/egldeviceintegrations/libqeglfs-x11-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/imageformats/libqgif.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/imageformats/libqico.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/imageformats/libqjpeg.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/xcbglintegrations/libqxcb-egl-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/xcbglintegrations/libqxcb-glx-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/platforms/libqxcb.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6EglFSDeviceIntegration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6XcbQpa.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6FbSupport.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6InputSupport.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6OpenGL.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6Gui.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/egldeviceintegrations/libqeglfs-emu-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/egldeviceintegrations/libqeglfs-x11-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/imageformats/libqgif.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/imageformats/libqico.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/imageformats/libqjpeg.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/xcbglintegrations/libqxcb-egl-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/xcbglintegrations/libqxcb-glx-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/platforms/libqxcb.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6EglFSDeviceIntegration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6XcbQpa.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6FbSupport.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6InputSupport.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6OpenGL.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6Gui.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/egldeviceintegrations/libqeglfs-emu-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/egldeviceintegrations/libqeglfs-x11-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/imageformats/libqgif.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/imageformats/libqico.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/imageformats/libqjpeg.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/xcbglintegrations/libqxcb-egl-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/xcbglintegrations/libqxcb-glx-integration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/Qt6/plugins/platforms/libqxcb.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6EglFSDeviceIntegration.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6XcbQpa.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6FbSupport.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6InputSupport.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6OpenGL.a  /usr/lib/x86_64-linux-gnu/libGLX.so  /usr/lib/x86_64-linux-gnu/libOpenGL.so  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libharfbuzz.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libfreetyped.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libbz2d.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libpng16d.a  /mnt/vcpkg-ci/installed/x64-linux/lib/libz.a  /mnt/vcpkg-ci/installed/x64-linux/lib/libbrotlidec-static.a  /mnt/vcpkg-ci/installed/x64-linux/lib/libbrotlicommon-static.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libfontconfig.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libfreetyped.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libpng16d.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libbz2d.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libbrotlidec-static.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libbrotlicommon-static.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libexpat.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libuuid.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6DBus.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libjpeg.a  /usr/lib/x86_64-linux-gnu/libxcb-glx.so  /usr/lib/x86_64-linux-gnu/libEGL.so  /usr/lib/x86_64-linux-gnu/libX11.so  /usr/lib/x86_64-linux-gnu/libxkbcommon.so  /usr/lib/x86_64-linux-gnu/libX11-xcb.so  /usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so  /usr/lib/x86_64-linux-gnu/libxkbcommon.so  /usr/lib/x86_64-linux-gnu/libxcb-icccm.so  /usr/lib/x86_64-linux-gnu/libxcb-image.so  /usr/lib/x86_64-linux-gnu/libxcb-keysyms.so  /usr/lib/x86_64-linux-gnu/libxcb-randr.so  /usr/lib/x86_64-linux-gnu/libxcb-render-util.so  /usr/lib/x86_64-linux-gnu/libxcb-shm.so  /usr/lib/x86_64-linux-gnu/libxcb-sync.so  /usr/lib/x86_64-linux-gnu/libxcb-xfixes.so  /usr/lib/x86_64-linux-gnu/libxcb-render.so  /usr/lib/x86_64-linux-gnu/libxcb-shape.so  /usr/lib/x86_64-linux-gnu/libxcb-xkb.so  /usr/lib/x86_64-linux-gnu/libSM.so  /usr/lib/x86_64-linux-gnu/libICE.so  /usr/lib/x86_64-linux-gnu/libxcb-xinput.so  /usr/lib/x86_64-linux-gnu/libxcb.so  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6DeviceDiscoverySupport.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libQt6Core.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libz.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libdouble-conversion.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libb2.a  -lm  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libicui18n.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libicuuc.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libicudata.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libpcre2-16.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libzstdd.a  -ldl  /usr/lib/x86_64-linux-gnu/librt.so  -pthread && :
/mnt/vcpkg-ci/installed/x64-linux/debug/lib/libpq.a(fe-secure-openssl.o): In function `sk_GENERAL_NAME_num':
/mnt/vcpkg-ci/installed/x64-linux/include/openssl/x509v3.h:166: undefined reference to `OPENSSL_sk_num'
/mnt/vcpkg-ci/installed/x64-linux/debug/lib/libpq.a(fe-secure-openssl.o): In function `sk_GENERAL_NAME_value':
/mnt/vcpkg-ci/installed/x64-linux/include/openssl/x509v3.h:166: undefined reference to `OPENSSL_sk_value'
/mnt/vcpkg-ci/installed/x64-linux/debug/lib/libpq.a(fe-secure-openssl.o): In function `sk_GENERAL_NAME_free':
/mnt/vcpkg-ci/installed/x64-linux/include/openssl/x509v3.h:166: undefined reference to `OPENSSL_sk_free'
/mnt/vcpkg-ci/installed/x64-linux/debug/lib/libpq.a(fe-secure-openssl.o): In function `pgtls_read':
/mnt/vcpkg-ci/buildtrees/libpq/x64-linux-dbg/src/interfaces/libpq/fe-secure-openssl.c:161: undefined reference to `ERR_clear_error'
/mnt/vcpkg-ci/buildtrees/libpq/x64-linux-dbg/src/interfaces/libpq/fe-secure-openssl.c:162: undefined reference to `SSL_read'
```

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by ras0219-msft** [comment]
This LGTM, thanks for the fix!

File: ports/libpq/vcpkg-cmake-wrapper.cmake [hunk 1]
```diff
@@ -45,4 +45,22 @@ if(PostgreSQL_FOUND AND "@VCPKG_LIBRARY_LINKAGE@" STREQUAL "static")
...
+    if(WIN32)
+        if(TARGET PostgreSQL::PostgreSQL)
+            set_property(TARGET PostgreSQL::PostgreSQL APPEND PROPERTY INTERFACE_LINK_LIBRARIES "Secur32.lib")
+        endif()
+        list(APPEND PostgreSQL_LIBRARIES Secur32.lib)
+    endif()
+    cmake_policy(PUSH)
+    cmake_policy(SET CMP0057 NEW)
+    set(Z_VCPKG_PORT_FEATURES "@FEATURES@")
+    if("openssl" IN_LIST Z_VCPKG_PORT_FEATURES)
```
Comment (cenit) [inline ports/libpq/vcpkg-cmake-wrapper.cmake:57]: shouldn't this be made as a cmake-configured file and the if(... Z_VCPKG_PORT_FEATURES ) be changed to an @-symbol? otherwise this is bound to fail during normal usage...
