### PR TITLE
[Curl] Upgrades 2019.05.08

### PR DESCRIPTION
**Pull request by PhoebeHui**
Related PR https://github.com/microsoft/vcpkg/pull/6382
1. Update the patch 
2. Update the name of share/curl/curl-target-release.cmake to share/curl/CURLTargets-release.cmake
3. Case sensitive in Linux, the name(curl -> CURL) changed in curl by commit 6932849.
4. Fix same case value issue in cpr.

The new upgrade in Curl, it moved deprecated #define CURLE_SSL_CACERT CURLE_PEER_FAILED_VERIFICATION to ifndef block in commit 0fd4427f, we didn’t define CURL_NO_OLDIES, so the following code enabled:
#define CURLE_SSL_CACERT CURLE_PEER_FAILED_VERIFICATION

In cpr\error.cpp reference 2 cases that both have same case value, so it failed with ‘error C2196: case value '60' already used’.

case CURLE_PEER_FAILED_VERIFICATION:
            return ErrorCode::SSL_REMOTE_CERTIFICATE_ERROR;
case CURLE_SSL_CACERT:
           return ErrorCode::SSL_CACERT_ERROR;

So I removed one of them to fix it.

### CODE REVIEW

**Comment by wangli28** [comment]
Related issue: #4691 and #5845.

File: ports/curl/0002_fix_uwp.patch [hunk 1]
```diff
@@ -1,92 +1,90 @@
...
++++ b/lib/curl_ntlm_core.c
+@@ -726,10 +726,10 @@ CURLcode Curl_ntlm_core_mk_ntlmv2_resp(unsigned char *ntlmv2hash,
+ 
+   /* Calculate the timestamp */
+ #ifdef DEBUGBUILD
+-  char *force_timestamp = getenv("CURL_FORCETIME");
++  char *force_timestamp = curl_getenv("CURL_FORCETIME");
+   if(force_timestamp)
+     tw = CURL_OFF_T_C(11644473600) * 10000000;
+-  else
```
Comment (ras0219-msft) [inline ports/curl/0002_fix_uwp.patch]: This needs to be enclosed in brackets -- otherwise the `if()` only applies to the following line (`tw = ...`) and the `free(force_timestamp)` will _always_ be called even if it `force_timestamp` was null.

File: ports/curl/portfile.cmake [hunk 2]
```diff
@@ -113,8 +113,8 @@ vcpkg_configure_cmake(
 
 vcpkg_install_cmake()
 
-if(EXISTS ${CURRENT_PACKAGES_DIR}/lib/cmake/curl)
-    vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/curl)
+if(EXISTS ${CURRENT_PACKAGES_DIR}/lib/cmake/CURL)
+    vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/CURL)
 elseif(EXISTS ${CURRENT_PACKAGES_DIR}/share/curl)
     vcpkg_fixup_cmake_targets(CONFIG_PATH share/curl)
 endif()
```
Comment (ras0219-msft) [inline ports/curl/portfile.cmake]: We should add:
```
else()
    message(FATAL_ERROR "Could not locate the curl config files")
```

to ensure we aren't missing something here accidentally.

**Review by ras0219-msft — CHANGES_REQUESTED** [review]

**Comment by past-due** [comment]
@ras0219-msft: A heads-up: CURL 7.64.1 [breaks the `darwinssl` feature](https://github.com/curl/curl/issues/3733) - and, hence, will break `curl[ssl]` on macOS.

This is [fixed in the next version of CURL](https://github.com/curl/curl/pull/3769), which is [scheduled for release 22nd of May 2019](https://curl.haxx.se/dev/release-notes.html). (Note: This will require renaming the `USE_DARWINSSL` option to `USE_SECTRANSP` in `ports/curl/portfile.cmake`, with that new version of CURL.)

**Comment by past-due** [comment]
CURL 7.65 is [now available](https://curl.haxx.se/changes.html#7_65_0).

**Comment by ras0219-msft** [comment]
Thanks a bunch for the heads-up, @past-due!

File: ports/curl/portfile.cmake [hunk 3]
```diff
@@ -104,6 +100,7 @@ vcpkg_configure_cmake(
         -DCMAKE_USE_DARWINSSL=${USE_DARWINSSL}
```
Comment (past-due) [inline ports/curl/portfile.cmake]: @ras0219-msft: With CURL 7.65+, `CMAKE_USE_DARWINSSL` should be renamed to `CMAKE_USE_SECTRANSP` to properly specify Apple's Secure Transport (formerly: "DarwinSSL") backend for CURL's CMake build script. See: https://github.com/curl/curl/pull/3769

```diff
-        -DCMAKE_USE_DARWINSSL=${USE_DARWINSSL}
+        -DCMAKE_USE_SECTRANSP=${USE_DARWINSSL}
```

File: ports/curl/0002_fix_uwp.patch (hunk 1 above)
Comment (PhoebeHui) [reply ports/curl/0002_fix_uwp.patch]: Resolved, thanks!

File: ports/curl/portfile.cmake (hunk 2 above)
Comment (PhoebeHui) [reply ports/curl/portfile.cmake]: Resolved, thanks!

File: ports/curl/portfile.cmake (hunk 3 above)
Comment (PhoebeHui) [reply ports/curl/portfile.cmake]: I have renamed darwinssl to sectransp, since the name changed in curl, I think we should update it as well. thank you Robert and past-due for helping review!

**Comment by vicroms** [comment]
ping @ras0219-msft 

Something holding this PR from merging?

**Comment by ras0219-msft** [comment]
No, LGTM. Thanks for the great work @PhoebeHui and the review @past-due!
