### PR TITLE
[vcpkg-tool-meson] Update meson to a more recent version

### LINKED ISSUE #32966: [vcpkg-tool-meson] vcpkg-tool-meson tool is too old
### Library name

vcpkg-tool-meson 

### New version number

 1.2

### Other information that may be useful (release notes, etc...)

_No response_

### LINKED ISSUE #35332: [fontconfig] build failure - python 3.12 distutils removal meson problem
### Operating system

MacSOX 12 Github runner but all affected

### Compiler

_No response_

### Steps to reproduce the behavior

```Shell
try to install fontconfig having python 3.12
```

### Failure logs

Traceback (most recent call last):
  File "/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmpbzagqcow.py", line 5, in <module>
    import distutils.command.install
ModuleNotFoundError: No module named 'distutils'

../src/2.14.2-7f52ee670b.clean/meson.build:47:0: ERROR: <PythonExternalProgram 'python' -> ['/usr/local/bin/python3']> is not a valid python or it is missing distutils

### Additional context

Python 3.12 removes deprecated distutils. Old Meson 0.63 available in vcpkg requires it. Needs probably to be updated to newest version 1.3.0.

### PR DESCRIPTION
**Pull request by Neumann-A**
~~blocked by https://github.com/mesonbuild/meson/issues/11143~~
Fixes https://github.com/microsoft/vcpkg/issues/32966

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@Neumann-A, Thanks for your pr, This is ci error log,
Please take a view:
````
Compiler stderr:
 testfile.c
D:\buildtrees\gobject-introspection\x64-windows-dbg\meson-private\tmpp52iajuj\testfile.c(4): fatal error C1189: #error:  "Header 'unistd.h' could not be found"

Has header "unistd.h" : NO 
Could not find Python3 library 'D:\\downloads\\tools\\python\\python-3.10.7-x64\\libs\\python310.lib'

..\src\spection-1-c68dee862a.clean\giscanner\meson.build:112:0: ERROR: Python dependency not found
````

**Comment by Neumann-A** [comment]
Yeah. I probably need to replace mesons python module with the one from 0.63.0.

File: ports/vcpkg-tool-meson/portfile.cmake [hunk 1]
```diff
@@ -33,6 +33,12 @@ vcpkg_find_acquire_program(PYTHON3)
 # )
 
 if(NOT "${program}")
+    vcpkg_download_distfile(
+        python_module_path
+        URLS https://raw.githubusercontent.com/mesonbuild/meson/9c6dab2cfd310ef2d840a2a7a479ce6b9e563b1d/mesonbuild/modules/python.py
+        FILENAME python-meson-module-9c6dab.py
+        SHA512 6e93dad2d12929757a37b97c44f697413504e7238ff7bb4e87925a3b5ba6d9eae7c25ae4d1a022ee836747fac760662a33d1ea88c7c74712673ce64e538eb691
+    )
```
Comment (Neumann-A) [inline ports/vcpkg-tool-meson/portfile.cmake:41]:
```suggestion
```

File: ports/vcpkg-tool-meson/portfile.cmake [hunk 2]
```diff
@@ -48,9 +54,11 @@ if(NOT "${program}")
         SOURCE_PATH "${CURRENT_PACKAGES_DIR}"
         PATCHES
             meson-intl.patch
+            python-lib-dep.patch
     )
     file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/tools/meson/test cases")
     configure_file("${CMAKE_CURRENT_LIST_DIR}/vcpkg-port-config.cmake" "${CURRENT_PACKAGES_DIR}/share/${PORT}/vcpkg-port-config.cmake" @ONLY)
+    file(INSTALL "${python_module_path}" DESTINATION "${CURRENT_PACKAGES_DIR}/tools/meson/mesonbuild/modules" RENAME "python.py")
```
Comment (Neumann-A) [inline ports/vcpkg-tool-meson/portfile.cmake:61]:
```suggestion
```

**Comment by JonLiu1993** [comment]
@Neumann-A, Thanks for your PR, could you please fix the conflict files?

**Comment by JackBoosY** [comment]
https://github.com/microsoft/vcpkg/pull/29879 was merged, try to merge to master?

**Comment by JackBoosY** [comment]
nghttp2 regression:
```
CMake Error:
  Running

   'C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe' '-C' 'D:/buildtrees/nghttp2/arm-uwp-dbg' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:607: multiple rules generate lib/nghttp2.lib
```

**Comment by Neumann-A** [comment]
> No idea why it happened.

This happens if you have two targets with the same output name since ninja uses output names to name its build targets.

**Comment by JackBoosY** [comment]
> > No idea why it happened.
> 
> This happens if you have two targets with the same output name since ninja uses output names to name its build targets.

Yeah I know that, but I didn't find any 2 targets which have the same target name / same target output name except the static library. However, this is dynamic.

**Comment by JackBoosY** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/29924

**Comment by JackBoosY** [comment]
mnn:x64-osx:
```
[13/263] /Library/Developer/CommandLineTools/usr/bin/c++ -DDEBUG -DMNN_DEBUG -DMNN_DEBUG_MEMORY -DMNN_DEBUG_TENSOR_SIZE -DMNN_SUPPORT_TFLITE_QUAN -DMNN_USE_SSE -DMNN_USE_THREAD_POOL -DMNN_VERSION=\"1.1.0.0-d6795ad\" -DMNN_VERSION_MAJOR=1 -DMNN_VERSION_MINOR=1 -DMNN_VERSION_PATCH=0 -I/Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/include -I/Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/source -I/Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/express -I/Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/tools -I/Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/schema/current -I/Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/3rd_party/half -I/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include -isystem /Users/vagrant/Data/installed/x64-osx/include -fPIC -std=c++11 -g -fstrict-aliasing -ffunction-sections -fdata-sections -ffast-math -fno-rtti -fno-exceptions  -g -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk   -fno-stack-check -std=gnu++11 -MD -MT CMakeFiles/MNNTransform.dir/source/shape/ShapeQuantizedAvgPool.cpp.o -MF CMakeFiles/MNNTransform.dir/source/shape/ShapeQuantizedAvgPool.cpp.o.d -o CMakeFiles/MNNTransform.dir/source/shape/ShapeQuantizedAvgPool.cpp.o -c /Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/source/shape/ShapeQuantizedAvgPool.cpp
FAILED: CMakeFiles/MNNTransform.dir/source/shape/ShapeQuantizedAvgPool.cpp.o 
/Library/Developer/CommandLineTools/usr/bin/c++ -DDEBUG -DMNN_DEBUG -DMNN_DEBUG_MEMORY -DMNN_DEBUG_TENSOR_SIZE -DMNN_SUPPORT_TFLITE_QUAN -DMNN_USE_SSE -DMNN_USE_THREAD_POOL -DMNN_VERSION=\"1.1.0.0-d6795ad\" -DMNN_VERSION_MAJOR=1 -DMNN_VERSION_MINOR=1 -DMNN_VERSION_PATCH=0 -I/Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/include -I/Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/source -I/Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/express -I/Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/tools -I/Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/schema/current -I/Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/3rd_party/half -I/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include -isystem /Users/vagrant/Data/installed/x64-osx/include -fPIC -std=c++11 -g -fstrict-aliasing -ffunction-sections -fdata-sections -ffast-math -fno-rtti -fno-exceptions  -g -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk   -fno-stack-check -std=gnu++11 -MD -MT CMakeFiles/MNNTransform.dir/source/shape/ShapeQuantizedAvgPool.cpp.o -MF CMakeFiles/MNNTransform.dir/source/shape/ShapeQuantizedAvgPool.cpp.o.d -o CMakeFiles/MNNTransform.dir/source/shape/ShapeQuantizedAvgPool.cpp.o -c /Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/source/shape/ShapeQuantizedAvgPool.cpp
In file included from /Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/source/shape/ShapeQuantizedAvgPool.cpp:10:
In file included from /Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/source/shape/SizeComputer.hpp:16:
In file included from /Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/schema/current/MNN_generated.h:7:
In file included from /Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/flatbuffers/flatbuffers.h:24:
In file included from /Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/flatbuffers/array.h:22:
In file included from /Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/flatbuffers/base.h:237:
In file included from /Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/absl/strings/string_view.h:39:
In file included from /Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/absl/base/attributes.h:37:
In file included from /Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/absl/base/config.h:86:
/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/absl/base/policy_checks.h:79:2: error: "C++ versions less than C++14 are not supported."
#error "C++ versions less than C++14 are not supported."
 ^
In file included from /Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/source/shape/ShapeQuantizedAvgPool.cpp:10:
In file included from /Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/source/shape/SizeComputer.hpp:16:
In file included from /Users/vagrant/Data/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/schema/current/MNN_generated.h:7:
In file included from /Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/flatbuffers/flatbuffers.h:24:
In file included from /Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/flatbuffers/array.h:22:
In file included from /Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/flatbuffers/base.h:237:
/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/absl/strings/string_view.h:340:10: error: cannot assign to non-static data member within const member function 'remove_prefix'
    ptr_ += n;
    ~~~~ ^
/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/absl/strings/string_view.h:338:18: note: member function 'absl::string_view::remove_prefix' is declared const here
  constexpr void remove_prefix(size_type n) {
  ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/absl/strings/string_view.h:341:13: error: cannot assign to non-static data member within const member function 'remove_prefix'
    length_ -= n;
    ~~~~~~~ ^
/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/absl/strings/string_view.h:338:18: note: member function 'absl::string_view::remove_prefix' is declared const here
  constexpr void remove_prefix(size_type n) {
  ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/absl/strings/string_view.h:338:18: error: constexpr function's return type 'void' is not a literal type
  constexpr void remove_prefix(size_type n) {
                 ^
/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/absl/strings/string_view.h:350:13: error: cannot assign to non-static data member within const member function 'remove_suffix'
    length_ -= n;
    ~~~~~~~ ^
/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/absl/strings/string_view.h:348:18: note: member function 'absl::string_view::remove_suffix' is declared const here
  constexpr void remove_suffix(size_type n) {
  ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/absl/strings/string_view.h:348:18: error: constexpr function's return type 'void' is not a literal type
  constexpr void remove_suffix(size_type n) {
                 ^
/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/absl/strings/string_view.h:358:11: error: no viable overloaded '='
    *this = s;
    ~~~~~ ^ ~
/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/absl/strings/string_view.h:161:7: note: candidate function (the implicit copy assignment operator) not viable: 'this' argument has type 'const absl::string_view', but method is not marked const
class string_view {
      ^
/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/absl/strings/string_view.h:161:7: note: candidate function (the implicit move assignment operator) not viable: 'this' argument has type 'const absl::string_view', but method is not marked const
/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/absl/strings/string_view.h:356:18: error: constexpr function's return type 'void' is not a literal type
  constexpr void swap(string_view& s) noexcept {
                 ^
8 errors generated.
ninja: build stopped: subcommand failed.
```
Baseline issue?

**Comment by dg0yt** [comment]
> Baseline issue?

@JackBoosY yes, from #29692. Cf. https://github.com/microsoft/vcpkg/pull/29792#issuecomment-1443704002

**Comment by dg0yt** [comment]
> > Baseline issue?
> 
> @JackBoosY yes, from #29692. Cf. [#29792 (comment)](https://github.com/microsoft/vcpkg/pull/29792#issuecomment-1443704002)

PR: https://github.com/microsoft/vcpkg/pull/29974

**Comment by JackBoosY** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/29974.

**Comment by JackBoosY** [comment]
Ready for review now?

**Comment by Neumann-A** [comment]
@JackBoosY Yes.

**Comment by JackBoosY** [comment]
ping @JonLiu1993 for review.

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by talregev** [comment]
I can confirm that with this PR/branch I was able to compile on ubuntu 22.04 (GitHub action Linux ci) 
With all it dependencies: (including glib, cairo and more)
wxwidgets --triplet x64-linux
cross compiler:
wxwidgets --triplet arm64-linux --host x64-linux
wxwidgets --triplet arm-linux --host x64-linux

**Comment by JackBoosY** [comment]
Can anyone merge this PR quickly?

File: ports/vcpkg-tool-meson/vcpkg_configure_meson.cmake
Comment (dan-shaw) [inline ports/vcpkg-tool-meson/vcpkg_configure_meson.cmake:1]: The `vcpkg_*_meson` scripts should be decoupled from the `meson` tool (moved into its own port). One reason for that is the versions between the tool and the scripts can be different. Additionally, the naming of the scripts should follow the convention used in other script ports, something like `vcpkg_meson_configure`

Comment (Neumann-A) [reply ports/vcpkg-tool-meson/vcpkg_configure_meson.cmake:1]: a) https://github.com/microsoft/vcpkg/discussions/28808
b) This PR does not aim to do a script audit. (so no `vcpkg-meson` port with `vcpkg_meson_configure`)

The only thing this PR aims to do is
1. tightly couple the `script/cmake/vcpkg_(configure|install)_meson` stuff to `vcpkg-tool-meson` so that it is guaranteed to work together. Otherwise older versions might get wrecked in the future. 
2. remove the need for full world rebuilds if the script needs to be edited.

> the tool and the scripts can be different

That means it is never guaranteed that script and tool actually work together.

**Comment by JackBoosY** [comment]
@JonLiu1993 Drop label `author-response`, the author replied 5 days ago.

**Comment by JackBoosY** [comment]
@Neumann-A Please resolve the file conflicts?

**Comment by JackBoosY** [comment]
Since this PR can't be landed quickly, can I reopen my PR https://github.com/microsoft/vcpkg/pull/29916 ?

**Comment by talregev** [comment]
> Since this PR can't be landed quickly, can I reopen my PR #29916 ?

Do you mean split your PR? I think you should do it, and you can. You don't need a permission to change your own PRs.

**Comment by dg0yt** [comment]
> Since this PR can't be landed quickly, can I reopen my PR #29916 ?

Does it help? It will rebuild the world and probably hit baseline regressions, too.

**Comment by talregev** [comment]
> > Since this PR can't be landed quickly, can I reopen my PR #29916 ?
> 
> Does it help? It will rebuild the world and probably hit baseline regressions, too.

What is missing for world build work smoothly? any waited PRs?

**Comment by talregev** [comment]
> Since this PR can't be landed quickly, can I reopen my PR #29916 ?

I think you need to open your PR and create your fix even if this PR include your fix.
This PR will take time to review, and better to have changes in small parts. 
Your PR is depends on chains of important PRs that is waist for waiting. 
Thank you @JackBoosY for your hard work.

**Comment by talregev** [comment]
@Neumann-A What holding this PR?

**Comment by talregev** [comment]
@Neumann-A Why not split this PR? for update the mason and the other stuff you did? More easy to other to review and merge with the master with a smaller PRs.

File: versions/v-/vcpkg-tool-meson.json [hunk 3]
```diff
@@ -1,5 +1,15 @@
...
+    {
+      "git-tree": "a8a41ebcf685add9ae9b8dc353af07573a196b1e",
+      "version": "1.1.0",
+      "port-version": 0
+    },
+    {
+      "git-tree": "f96ae6f3c73df752191575a05e258ea8475a1078",
+      "version": "1.0.0",
+      "port-version": 0
+    },
```
Comment (JonLiu1993) [inline versions/v-/vcpkg-tool-meson.json:12]: There should be only one record here.

**Comment by JonLiu1993** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by JavierMatosD** [comment]
Hi @Neumann-A, do all of the changes in this PR need to happen simultaneously? It would be very appreciated if you could split apart the PR into smaller chunks. It makes it easier to review. 

Moving to Draft while you respond. Mark "ready for review" once you've responded.

**Comment by Neumann-A** [comment]
> Hi @Neumann-A, do all of the changes in this PR need to happen simultaneously? It would be very appreciated if you could split apart the PR into smaller chunks. It makes it easier to review.

What do you want to have separated?
- the meson update + the required port & script changes 
- the movement of meson into downloads
- the movement of the meson scripts into the meson port
- libnice-gst: fix for single config builds and Z7 (required due to the script changes)

currently for review you might want to diff `ports/vcpkg-tool-meson/vcpkg_configure_meson.cmake` vs `scripts/cmake/vcpkg_configure_meson.cmake`

`ports/vcpkg-tool-meson/vcpkg_install_meson.cmake` is just a copy of the original in `scripts/cmake`

File: ports/vcpkg-tool-meson/vcpkg_configure_meson.cmake [hunk 4]
```diff
@@ -0,0 +1,456 @@
...
+    string(APPEND host "cpu = '${host_cpu}'")
+    if(NOT host_unkown)
+        set(${host_system} "${host}" PARENT_SCOPE)
+    endif()
+
+    if(NOT build_cpu_fam MATCHES "${host_cpu_fam}"
+       OR VCPKG_TARGET_IS_ANDROID OR VCPKG_TARGET_IS_IOS OR VCPKG_TARGET_IS_UWP
+       OR (VCPKG_TARGET_IS_MINGW AND NOT WIN32))
+        set(${is_cross} TRUE PARENT_SCOPE)
+    endif()
```
Comment (dg0yt) [inline ports/vcpkg-tool-meson/vcpkg_configure_meson.cmake:258]: There should be an option to really follow `VCPKG_CROSSCOMPILING`. I looked into `gobject-introspection`, and I found this to be one blocker for x64-linux-dynamic on x64-line.

**Comment by BillyONeal** [comment]
Sorry, I broke the macos machine :(

**Comment by nlogozzo** [comment]
glib got updated to 2.78.4

You'll have to pull and merge from main

**Comment by dg0yt** [comment]
Time to refresh?

**Comment by robUx4** [comment]
This PR has been going on for a more than a year. Is there an actual plan to get it merged at some point? Looking at the names of some of the commits, it doesn't look like.

**Comment by dg0yt** [comment]
> This PR has been going on for a more than a year. Is there an actual plan to get it merged at some point? Looking at the names of some of the commits, it doesn't look like.

When it comes to the work of volunteers, I would suggest a more positive wording to ask for details or progress.

**Comment by Neumann-A** [comment]
I just read white noise here. No signal from the MS team. @JonLiu1993 can you mark this reviewed so that the main team has to look at it again or at least give advice how to move it forward since it is activly blocking progress.

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by vicroms** [comment]
@Neumann-A 

Thanks for the patience! We are aware that this has been on a holding pattern for way too long. Given that this PR is not introducing a new method of acquiring Meson and is only updating what we already have, we feel that it makes no sense to keep delaying it in wait of a tools RFC.

We will be merging this PR after reviewing all the changes and patches.

**Comment by nlogozzo** [comment]
Hi, any update?

File: ports/vcpkg-tool-meson/vcpkg_configure_meson.cmake (hunk 4 above)
Comment (vicroms) [reply ports/vcpkg-tool-meson/vcpkg_configure_meson.cmake:258]: @Neumann-A 

Sorry if this has been discussed before, you mention in other file that `VCPKG_CROSSCOMPILING` causes multiple regressions. Can you elaborate a bit on what is wrong with `VCPKG_CROSSCOMPILING`?

**Review by vicroms — DISMISSED** [review]

File: ports/vcpkg-tool-meson/vcpkg_configure_meson.cmake (hunk 4 above)
Comment (Neumann-A) [reply ports/vcpkg-tool-meson/vcpkg_configure_meson.cmake:258]: > Can you elaborate a bit on what is wrong with VCPKG_CROSSCOMPILING?

Same reason why you don't correctly setup x64 toolchains with `CMAKE_CROSSCOMPILING` (e.g. in hdf5). Sometimes a configure check requires actually running an executable and that isn't allowed in a pure cross builds. So instead of making a x64-windows <-> x64-windows-static build a cross build it is better to keep it to being native.

File: scripts/cmake/vcpkg_find_acquire_program(MESON).cmake [hunk 5]
```diff
@@ -7,7 +7,7 @@ set(version_command --version)
 set(extra_search_args EXACT_VERSION_MATCH)
 if(EXISTS "${CURRENT_HOST_INSTALLED_DIR}/share/meson/version.txt")
     file(READ "${CURRENT_HOST_INSTALLED_DIR}/share/meson/version.txt" program_version)
-    set(paths_to_search "${CURRENT_HOST_INSTALLED_DIR}/tools/meson")
+    set(paths_to_search "${DOWNLOADS}/tools/meson-${program_version};${CURRENT_HOST_INSTALLED_DIR}/tools/meson")
```
Comment (BillyONeal) [inline scripts/cmake/vcpkg_find_acquire_program(MESON).cmake:10]: I note that we would not be OK with hijacking vcpkg_find_acquire_program like this in the future but it is OK in this PR. No change requested here, just noting it for any potential future arguments :)

File: ports/vcpkg-tool-meson/vcpkg_configure_meson.cmake
Comment (BillyONeal) [reply ports/vcpkg-tool-meson/vcpkg_configure_meson.cmake:1]: Confirming that this is more or less identical to the one in `scripts`.  
image

I am concerned about trying to use the same function name; when the other functions were moved into ports world we reordered the names (`vcpkg_configure_cmake` -> `vcpkg_cmake_configure`). Should we do that renaming here as well?

File: scripts/buildsystems/meson/meson.template.in [hunk 6]
```diff
@@ -1,6 +1,5 @@
 [binaries]
 cmake = ['@CMAKE_COMMAND@']
-python = ['@PYTHON3@']
```
Comment (BillyONeal) [inline scripts/buildsystems/meson/meson.template.in:3]: Can you explain the effect of this change? I'm worried because it affects old port versions, being in scripts/. It also seems unnecessary now that you've moved the 'active' one of these into the port?

**Review by BillyONeal — DISMISSED** [review]
LGTM as long as we are OK with taking the same function name like that.

File: scripts/buildsystems/meson/meson.template.in (hunk 6 above)
Comment (Neumann-A) [reply scripts/buildsystems/meson/meson.template.in]: reverted

File: ports/vcpkg-tool-meson/vcpkg_configure_meson.cmake
Comment (Neumann-A) [reply ports/vcpkg-tool-meson/vcpkg_configure_meson.cmake:1]: Renaming would break overlays etc. 
The reason this has been moved with the same name is due to meson requiring a completely different setup. So if you use `vcpkg-tool-meson` you can no longer use the normal `vcpkg_configure_meson`. However, if you use `vcpkg_find_acquire_program(MESON)` you still need the old script for the old meson. 
So the only way to not break downstream horribly is to do it this way which keeps the old way working and makes the new way also work without having to touch every depending port.

File: ports/xcb-proto/portfile.cmake [hunk 7]
```diff
@@ -36,12 +36,14 @@ vcpkg_configure_make(
...
-        am_cv_python_pyexecdir=\\\${prefix}/tools/python3/site-packages
-        am_cv_python_pythondir=\\\${prefix}/tools/python3/site-packages
+        am_cv_python_pyexecdir=\\\${prefix}/${PYTHON3_SITE}
+        am_cv_python_pythondir=\\\${prefix}/${PYTHON3_SITE}
         )
 
 vcpkg_install_make()
 vcpkg_fixup_pkgconfig()
+vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/lib/pkgconfig/xcb-proto.pc" "\${pc_sysrootdir}" "")
+vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/debug/lib/pkgconfig/xcb-proto.pc" "\${pc_sysrootdir}" "")
```
Comment (dg0yt) [inline ports/xcb-proto/portfile.cmake:46]: FTR this change is obsolete since https://github.com/microsoft/vcpkg/pull/36843.

Comment (Neumann-A) [reply ports/xcb-proto/portfile.cmake]: I'll remove this but keep the PYTHON3_SITE change

**Comment by vipcxj** [comment]
I think vcpkg should provide a mechanism to globally set the meson version to be used, and each port can individually specify the meson version it needs, so that when a port needs a higher version of meson, it only needs to add this version of meson and specify the port to use it, which won't affect any of the older port

**Comment by BillyONeal** [comment]
@vipcxj This is a downside of managing tools like this with ports but we don't have a technical solution that allows it right now. As a port is still an improvement over how vcpkg_find_acquire_program works, where you get the version you get and you don't get upset.

**Comment by cenit** [comment]
all meson ports that are using a manifest and an older baseline now fail. 
The error is always along the lines of

..\src\conf-2.1.0-7b1cf1fe7f.clean\meson.build:1:0: ERROR: Value "plain" (of type "string") for combo option "Optimization level" is not one of the choices. Possible choices are (as string): "0", "g", "1", "2", "3", "s".

it errors out quite early. 

Updating the baseline to the latest vcpkg commit after this merge fixes things, but this is quite undesirable. Note that in the config-triplet-meson-log.txt.log the version is still
The Meson build system
Version: 0.62.1

**Comment by cenit** [comment]
@BillyONeal @Neumann-A

**Comment by cenit** [comment]
an easy test would be to build just the very basic port "pkgconf" using vcpkg baseline c9140a3b500812ad3206317885860d9553b93f13 but vcpkg base repo fully up to date

**Comment by Neumann-A** [comment]
That means that the meson in vcpkg_find_acquire_program needs an update to 0.63.

**Comment by Neumann-A** [comment]
@cenit try #37396

**Comment by petersteneteg** [comment]
#37396 worked for me
