### ISSUE TITLE
Failed build after Visual Studio update

### ISSUE THREAD

**Issue by Const-me** [microsoft/vcpkg#51947]
**Describe the bug**
Unable to compile C++ projects which use vcpkg packages after Visual Studio update

**Environment**
Windows 10

**To Reproduce**
Install Visual Studio 2026 community edition version 18.5.3.

Create a project which consumes a vcpkg package integrated using the recommended way i.e. `vcpkg.json` and `vcpkg-configuration.json` files in the project folder, and “Use Vcpkg manifest = Yes” in the project properties.

Build the project.

Use Visual Studio Installer application to upgrade IDE to the latest version 18.6.1

Build that project

**Expected behavior**
Should build

**Failure logs**
LINK : fatal error C1047: The object or library file .. was created by a different version of the compiler than other objects ..; rebuild all objects and libraries with the same compiler
Neither Clean nor Rebuild commands fix the issue.

**Additional context**
Thanks to claude.ai I was able to workaround by deleting two folders on disk, `vcpkg_installed` in the project and `%LOCALAPPDATA%\vcpkg\archives\` outside of it. On the next build Visual Studio rebuilt the entire dependency tree and things started to work again.

Still, vcpkg and visual studio are all Microsoft’s product, and I in the IDE stands for integrated. I expected the toolset to handle compiler upgrades better than just failing with cryptic error messages.

**Comment by Vultraz** [comment]
I had a similar issue after updating to 18.6.1 and attempting to build a CMake-based project. It seems related to the build tools update from 14.50 to 14.51 that’s included with VS 18.6.x. I was able to fix it by nuking everything in the build output path *except* the `vcpkg-installed` folder, which leads me to believe some intermediate build files weren’t being properly invalidated after the toolchain update.

**Comment by UMU618** [comment]
I had a warning after updating to 18.6.1:

```
C:\v\scripts\buildsystems\msbuild\vcpkg.targets(182,3): warning MSB4011: "C:\v\scripts\buildsystems\msbuild\support\GetGlobalProperties.task" cannot be imported again. It was already imported at "C:\v\scripts\buildsystems\msbuild\support\Bootstrap.targets (2,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\w\h\UMU618\sdl3vk\src\umutech\Sdl3VkTriangle++\Sdl3VkTriangle++.vcxproj]
```

If I delete the 2nd line in `Bootstrap.targets`, warning gone!

```
  <Import Project="$(MSBuildThisFileDirectory)\GetGlobalProperties.task" />
```

**Comment by JackBoosY** [comment]
cc @BillyONeal 
no idea whether the latest version fixed this issue.

**Comment by jeremy-visionaid** [comment]
I'm also seeing this with vcpkg 2026.06.01 and VS Build Tools 18.7.2

**Comment by jeremy-visionaid** [comment]
FWIW, the last working vcpkg version is 2026.04.27
