### ISSUE TITLE
ace: Missing installed header ace/Intrusive_List.cpp

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#11707]
**Describe the bug**
With the latest vcpkg, I have a failure in a library that is using the `ace` port. 

**Environment**
- OS: Windows
- Compiler: Visual Studio 16.6

**To Reproduce**
1. ./vcpkg install ace:x64-windows eigen3:x64-windows
2. Compile yarp https://github.com/robotology/yarp

Or in any case, build some code that includes the `ace/Intrusive_List.h` installed header.

**Expected behavior**
I would expect the library to compile correctly.

**Failure logs** 
~~~
C:\src\vcpkg_yarp\installed\x64-windows\include\ace/Intrusive_List.h(128,10): fatal error C1083: Cannot open include file: 'ace/Intrusive_List.cpp': No such file or directory [C:\src\yarp\build\src\libYARP_os\src\YARP_os.vcxproj]
  Terminal.cpp
C:\src\vcpkg_yarp\installed\x64-windows\include\ace/Intrusive_List.h(128,10): fatal error C1083: Cannot open include file: 'ace/Intrusive_List.cpp': No such file or directory [C:\src\yarp\build\src\libYARP_os\src\YARP_os.vcxproj]
  TextCarrier.cpp
  ThreadImpl.cpp
C:\src\vcpkg_yarp\installed\x64-windows\include\ace/Intrusive_List.h(128,10): fatal error C1083: Cannot open include file: 'ace/Intrusive_List.cpp': No such file or directory [C:\src\yarp\build\src\libYARP_os\src\YARP_os.vcxproj]
  UdpCarrier.cpp
C:\src\vcpkg_yarp\installed\x64-windows\include\ace/Intrusive_List.h(128,10): fatal error C1083: Cannot open include file: 'ace/Intrusive_List.cpp': No such file or directory [C:\src\yarp\build\src\libYARP_os\src\YARP_os.vcxproj]
~~~

**Additional context**
I saw a few PR related to ACE recently, I do not know if they are related.

**Comment by traversaro** [comment]
cc @jwillemsen

**Comment by traversaro** [comment]
At least in my case, the missing includes are: 
* `ace/Intrusive_List.cpp`
* `ace/Intrusive_List_Node.cpp`
* `ace/String_Base.cpp`
and it seems like a regression due to https://github.com/microsoft/vcpkg/pull/11464 .
