### ISSUE TITLE
pcl:x64-linux install fails on ubuntu 16.04. 

### ISSUE THREAD

**Issue by faultfactory** [microsoft/vcpkg#8998]
Running Ubuntu 16.04.
Dell Latitude 7490
From terminal error:
'Package: pcl:x64-linux
Vcpkg version: 2019.09.12-unknownhash'
Pulled latest version of vcpkg and built with boostrap-sh. 

ran "./vcpkg install pcl:x64-linux'

-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /home/jesse/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /home/jesse/vcpkg/buildtrees/pcl/x64-linux-dbg
    See logs for more information:
      /home/jesse/vcpkg/buildtrees/pcl/install-x64-linux-dbg-out.log

The log file is provided here. 

https://pastebin.com/BpmiUxg7

I got an error directing me to install libxt-dev for one of the dependencies but it appeared to already be installed.  After verifying installation, the pcl build still fails with the same message. 

FYI, I am also attempting to build on a separate 18.04 computer. That appears to be working but is not concluded.

**Comment by NancyLi1013** [comment]
Hi @faultfactory thnaks for posting this issue.
I saw these info from your log:

> /usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
>  #error This file requires compiler and library support \

Could you please try to add this line to CMakeLists.txt file?
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")`

**Comment by faultfactory** [comment]
I was able to get this to build by updating the compiler on my computer to g++-9. 

Perhaps the newer compilers don't need that flag set?

**Comment by JackBoosY** [comment]
@faultfactory Confirmed, use `std::random_device` and `std::mt19937` below gcc 6.0 needs to add compile options `-std=c++17`.

**Comment by NancyLi1013** [comment]
@faultfactory  Is this issue solved now?

**Comment by faultfactory** [comment]
With gcc 9, everything works okay. it seems like JackBoosY's information is
correct.

**Comment by NancyLi1013** [comment]
Closing this issue since it has been solved via PR #9231.
