### PR TITLE
[mpg123] Upgrade to 1.28.1

### PR DESCRIPTION
**Pull request by evpobr**
* Upgrade to 1.28.1
* Remove patches accepted by upstream

### CODE REVIEW

**Review by ras0219-msft — APPROVED** [review]

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
The failures cause by `libopenmpt` may be fixed by PR #18933.

```
D:\buildtrees\libopenmpt\src\2d346efba4-15feadd66e.clean\soundlib\SampleFormatMP3.cpp(60): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\buildtrees\libopenmpt\src\2d346efba4-15feadd66e.clean\soundlib\SampleFormatMP3.cpp(60): error C2146: syntax error: missing ';' before identifier 'mpg123_ssize_t'
```

Seems there is another version 1.28.2 released. https://sourceforge.net/projects/mpg123/files/mpg123/1.28.2/
Why do you not upgrade to 1.28.2 here?

**Comment by evpobr** [comment]
> The failures cause by `libopenmpt` may be fixed by PR #18933.
> 
> ```
> D:\buildtrees\libopenmpt\src\2d346efba4-15feadd66e.clean\soundlib\SampleFormatMP3.cpp(60): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
> D:\buildtrees\libopenmpt\src\2d346efba4-15feadd66e.clean\soundlib\SampleFormatMP3.cpp(60): error C2146: syntax error: missing ';' before identifier 'mpg123_ssize_t'
> ```
> 
> Seems there is another version 1.28.2 released. https://sourceforge.net/projects/mpg123/files/mpg123/1.28.2/
> Why do you not upgrade to 1.28.2 here?

I know about 1.28.2.  Why not keep 1.28.1 in versions history?

**Comment by NancyLi1013** [comment]
> > Why do you not upgrade to 1.28.2 here?
> 
> I know about 1.28.2. Why not keep 1.28.1 in versions history?

It's unnecessary to keep every version for the ports in vcpkg. We prefer to update to the latest release if no specific reason.

**Comment by evpobr** [comment]
@NancyLi1013 #18949.

**Comment by BillyONeal** [comment]
> I know about 1.28.2. Why not keep 1.28.1 in versions history?

It only matters to be in version history if there's some customer out there who would want to install that version, which does seem unlikely in this case. But if you think customers would be likely to want both doing this one first sounds OK.

Like in https://github.com/microsoft/vcpkg/pull/18949 there's a downstream build failure you can either patch yourself or wait to see if https://github.com/microsoft/vcpkg/pull/18933 fixes it.

**Comment by evpobr** [comment]
> Like in #18949 there's a downstream build failure you can either patch yourself or wait to see if #18933 fixes it.

@BillyONeal , sorry, I will be very busy in the near future. I hope #18933 will fix bugs.

**Comment by evpobr** [comment]
> It only matters to be in version history if there's some customer out there who would want to install that version, which does seem unlikely in this case. But if you think customers would be likely to want both doing this one first sounds OK.

Ok, i close this pull request in favor of #18949.
