### PR TITLE
[Qt] Update to 6.2.2 and add missing modules

### LINKED ISSUE #21804: [Qt] update Qt6 to <6.2.2>
Library name: **Qt**

New version number: **6.2.2**

Other information that may be useful (release notes, etc...)
https://www.qt.io/blog/qt-6.2.2-released
https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.2/release-note.md
https://download.qt.io/official_releases/qt/6.2/
https://wiki.qt.io/Qt_6.2_Release#Qt_6.2_release_plan

### PR DESCRIPTION
**Pull request by Neumann-A**
closes #21804
letting CI test stuff

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Comment by daschuer** [comment]
The pipeline of qtapplicationmanager failes now in https://github.com/microsoft/vcpkg/pull/21790
```
/mnt/vcpkg-ci/buildtrees/qtapplicationmanager/src/ad43fc4b04-cc8e3e67d5.clean/src/common-lib/qtyaml.cpp:39:10: fatal error: yaml.h: No such file or directory
```
Is this related to this PR? How can we fix it?

**Comment by Neumann-A** [comment]
could be an interaction with #21829

**Comment by JackBoosY** [comment]
I will check this regression now.

**Comment by JackBoosY** [comment]
For qtinterfaceframework:x64-windows:
```
error: Server does not allow request for unadvertised object 118fa138186144cf2d802405255f08662ed76d43
```
For qtinterfaceframework:x64-linux:
```
[26/280] /usr/bin/c++ -DQT_ASCII_CAST_WARNINGS -DQT_BUILDING_QT -DQT_BUILD_APPMAN_COMMON_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_DEPRECATED_WARNINGS -DQT_DEPRECATED_WARNINGS_SINCE=0x060000 -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_MOC_COMPAT -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_QML_LIB -DQT_STRICT_ITERATORS -DQT_USE_QSTRINGBUILDER -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/mnt/vcpkg-ci/buildtrees/qtapplicationmanager/x64-linux-dbg/src/common-lib/AppManCommonPrivate_autogen/include -I/mnt/vcpkg-ci/buildtrees/qtapplicationmanager/x64-linux-dbg/include -I/mnt/vcpkg-ci/buildtrees/qtapplicationmanager/x64-linux-dbg/include/QtAppManCommon -I/mnt/vcpkg-ci/buildtrees/qtapplicationmanager/src/ad43fc4b04-cc8e3e67d5.clean/src/common-lib -I/mnt/vcpkg-ci/buildtrees/qtapplicationmanager/x64-linux-dbg/src/common-lib -I/mnt/vcpkg-ci/buildtrees/qtapplicationmanager/x64-linux-dbg/include/QtAppManCommon/6.2.2 -I/mnt/vcpkg-ci/buildtrees/qtapplicationmanager/x64-linux-dbg/include/QtAppManCommon/6.2.2/QtAppManCommon -I/mnt/vcpkg-ci/buildtrees/qtapplicationmanager/src/ad43fc4b04-cc8e3e67d5.clean/src/3rdparty/libbacktrace -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6/QtConcurrent -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6 -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6/QtCore -isystem /mnt/vcpkg-ci/installed/x64-linux/share/Qt6/mkspecs/linux-g++ -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6/QtCore/6.2.2 -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6/QtCore/6.2.2/QtCore -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6/QtNetwork -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6/QtQml -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6/QtQml/6.2.2 -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6/QtQml/6.2.2/QtQml -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6/QtDBus -fPIC -g -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -fPIC -ffunction-sections -fdata-sections -pthread -Wsuggest-override -std=c++17 -MD -MT src/common-lib/CMakeFiles/AppManCommonPrivate.dir/qtyaml.cpp.o -MF src/common-lib/CMakeFiles/AppManCommonPrivate.dir/qtyaml.cpp.o.d -o src/common-lib/CMakeFiles/AppManCommonPrivate.dir/qtyaml.cpp.o -c /mnt/vcpkg-ci/buildtrees/qtapplicationmanager/src/ad43fc4b04-cc8e3e67d5.clean/src/common-lib/qtyaml.cpp
FAILED: src/common-lib/CMakeFiles/AppManCommonPrivate.dir/qtyaml.cpp.o 
/usr/bin/c++ -DQT_ASCII_CAST_WARNINGS -DQT_BUILDING_QT -DQT_BUILD_APPMAN_COMMON_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_DEPRECATED_WARNINGS -DQT_DEPRECATED_WARNINGS_SINCE=0x060000 -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_MOC_COMPAT -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_QML_LIB -DQT_STRICT_ITERATORS -DQT_USE_QSTRINGBUILDER -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/mnt/vcpkg-ci/buildtrees/qtapplicationmanager/x64-linux-dbg/src/common-lib/AppManCommonPrivate_autogen/include -I/mnt/vcpkg-ci/buildtrees/qtapplicationmanager/x64-linux-dbg/include -I/mnt/vcpkg-ci/buildtrees/qtapplicationmanager/x64-linux-dbg/include/QtAppManCommon -I/mnt/vcpkg-ci/buildtrees/qtapplicationmanager/src/ad43fc4b04-cc8e3e67d5.clean/src/common-lib -I/mnt/vcpkg-ci/buildtrees/qtapplicationmanager/x64-linux-dbg/src/common-lib -I/mnt/vcpkg-ci/buildtrees/qtapplicationmanager/x64-linux-dbg/include/QtAppManCommon/6.2.2 -I/mnt/vcpkg-ci/buildtrees/qtapplicationmanager/x64-linux-dbg/include/QtAppManCommon/6.2.2/QtAppManCommon -I/mnt/vcpkg-ci/buildtrees/qtapplicationmanager/src/ad43fc4b04-cc8e3e67d5.clean/src/3rdparty/libbacktrace -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6/QtConcurrent -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6 -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6/QtCore -isystem /mnt/vcpkg-ci/installed/x64-linux/share/Qt6/mkspecs/linux-g++ -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6/QtCore/6.2.2 -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6/QtCore/6.2.2/QtCore -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6/QtNetwork -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6/QtQml -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6/QtQml/6.2.2 -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6/QtQml/6.2.2/QtQml -isystem /mnt/vcpkg-ci/installed/x64-linux/include/Qt6/QtDBus -fPIC -g -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -fPIC -ffunction-sections -fdata-sections -pthread -Wsuggest-override -std=c++17 -MD -MT src/common-lib/CMakeFiles/AppManCommonPrivate.dir/qtyaml.cpp.o -MF src/common-lib/CMakeFiles/AppManCommonPrivate.dir/qtyaml.cpp.o.d -o src/common-lib/CMakeFiles/AppManCommonPrivate.dir/qtyaml.cpp.o -c /mnt/vcpkg-ci/buildtrees/qtapplicationmanager/src/ad43fc4b04-cc8e3e67d5.clean/src/common-lib/qtyaml.cpp
/mnt/vcpkg-ci/buildtrees/qtapplicationmanager/src/ad43fc4b04-cc8e3e67d5.clean/src/common-lib/qtyaml.cpp:39:10: fatal error: yaml.h: No such file or directory
   39 | #include <yaml.h>
      |          ^~~~~~~~
compilation terminated.
```
configure log:
```
...
-- Checking for module 'yaml-0.1'
--   Found yaml-0.1, version 
...
-- The following packages have been found:

 * Qt6BuildInternals (required version >= 6.2.2)
...
 * WrapLibYaml
...
