### ISSUE TITLE
[cpprestsdk]: linker error using -static-md for x86

### ISSUE THREAD

**Issue by danyhm** [microsoft/vcpkg#32708]
**Describe the bug**
I'm getting a linker error at compile time in my project when using cpprestsdk:x86-windows-static with vcpkg in VS2022

**Environment**
- OS: [Windows 10]
- Compiler: revision

**To Reproduce**
1. ./vcpkg install cpprestsdk:x86-windows-static
2. add to project and compile

**Expected behavior**
should compile and link fine.

**Failure logs**
```
LNK2019	unresolved external symbol ___std_init_once_link_alternate_names_and_abort@0 referenced in function "public: __thiscall std::_Init_once_completer::~_Init_once_completer(void)" (??1_Init_once_completer@std@@QAE@XZ)	***	[path to]\cpprest_2_10d.lib(asyncrt_utils.cpp.obj)
```

**Additional context**
I've already tried adding different libs to project to no avail.

**Comment by danyhm** [comment]
problem solved. the issue was toolset version mismatch. i was compiling with v142 on VS2022. after upgrading the toolset to v143 the linker now correctly recognizes the library
