### PR TITLE
Add google ceres-solver port

### PR DESCRIPTION
**Pull request by mmazat**
I was only able to compile it with VS 2017 preview (3) 15.3. An internal compiler error happens with VS 15.2, on one of the Eigen 3.3.3 files.

### CODE REVIEW

**Comment by KindDragon** [comment]
Fixes issue #318

File: ports/ceres-solver/portfile.cmake [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+#   VCPKG_ROOT_DIR            = <C:\path\to\current\vcpkg>
+#   VCPKG_TARGET_ARCHITECTURE = target architecture (x64, x86, arm)
+#
+
+include(vcpkg_common_functions)
+
+set (CERES_VER 1.12.0) #update SHA512 checksum w.r.t to verison
+set(SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/ceres-solver-${CERES_VER})
+
+vcpkg_download_distfile(ARCHIVE
```
Comment (KindDragon) [inline ports/ceres-solver/portfile.cmake]: You can use  `vcpkg_from_github` instead https://github.com/Microsoft/vcpkg/blob/fbf406083ea34a8b090d7bc0e94180ff091b52de/ports/cpprestsdk/portfile.cmake#L3-L9

File: ports/ceres-solver/portfile.cmake [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+#   VCPKG_CRT_LINKAGE         = C runtime linkage type (static, dynamic)
+#   VCPKG_LIBRARY_LINKAGE     = target library linkage type (static, dynamic)
+#   VCPKG_ROOT_DIR            = <C:\path\to\current\vcpkg>
+#   VCPKG_TARGET_ARCHITECTURE = target architecture (x64, x86, arm)
+#
+
+include(vcpkg_common_functions)
+
+set (CERES_VER 1.12.0) #update SHA512 checksum w.r.t to verison
+set(SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/ceres-solver-${CERES_VER})
```
Comment (KindDragon) [inline ports/ceres-solver/portfile.cmake]: Please add here:

```
set(VCPKG_PLATFORM_TOOLSET "v140") # Force VS2015 because VS2017 compiler return internal error
# eigen3\eigen\src\core\redux.h(237): fatal error C1001: An internal error has occurred in the compiler. [internal\ceres\ceres.vcxproj]
```

**Comment by KindDragon** [comment]
Maybe we should use `ceres` as package name? Because in CMakeLists.txt they use project name `project(Ceres C CXX)`
@ras0219-msft, what do you think?

File: ports/ceres-solver/portfile.cmake (hunk 1 above)
Comment (mmazat) [inline ports/ceres-solver/portfile.cmake]: I changed to vcpkg_from_github, but still need to use 
set (CERES_VER 1.12.0) 
set(SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/ceres-solver-${CERES_VER})

Comment (KindDragon) [inline ports/ceres-solver/portfile.cmake]: vcpkg_from_github set `OUT_SOURCE_PATH SOURCE_PATH` automatically

**Comment by mmazat** [comment]
I considered your comments, and changed the package name to ceres
it compiles with Toolset v140

**Comment by jasjuang** [comment]
@mmazat You are awesome, this is much needed

**Comment by ras0219-msft** [comment]
Thanks @mmazat for the PR and thanks for all the help reviewing @KindDragon!

**Comment by jasjuang** [comment]
@mmazat @ras0219-msft I just tried this port and I realized that there is no CeresConfig.cmake in it. This makes it very difficult to integrate with CMake. Would it be possible for you to add this in? Otherwise it's still easier to build Ceres from source in order to get that CeresConfig.cmake. There is glog-config.cmake for glog in vcpkg so I believe this should be possible. Thanks again for the great work

**Comment by ras0219-msft** [comment]
@jasjuang I think @KindDragon has fixed this in PR #1259.

**Comment by jasjuang** [comment]
@ras0219 @KindDragon I tried the latest build and I ran into the following error

``````
CMake Error at C:/dev/vcpkg/packages/ceres_x64-windows/share/ceres/CeresConfig.cmake:88 (message):
  Failed to find Ceres - Ceres install root:
  C:/dev/vcpkg/packages/ceres_x64-windows/share, determined from relative
  path from CeresConfig.cmake install location:
  C:/dev/vcpkg/packages/ceres_x64-windows/share/ceres, does not contain Ceres
  headers.  Either the install directory was deleted, or the install tree was
  only partially relocated outside of CMake after Ceres was built.
Call Stack (most recent call first):
  C:/dev/vcpkg/packages/ceres_x64-windows/share/ceres/CeresConfig.cmake:149 (ceres_report_not_found)
  apps/CeresMinimalExample/CMakeLists.txt:19 (find_package)


CMake Error at apps/CeresMinimalExample/CMakeLists.txt:19 (find_package):
  Found package configuration file:

    C:/dev/vcpkg/packages/ceres_x64-windows/share/ceres/CeresConfig.cmake

  but it set Ceres_FOUND to FALSE so package "Ceres" is considered to be NOT
  FOUND.


-- Configuring incomplete, errors occurred!
``````

I noticed that vcpkg placed CeresConfig.cmake at `share\ceres\CeresConfig.cmake`, whereas when I build it from source and install, it is placed at `CMake\CeresConfig.cmake. This could be a possible source of error

**Comment by KindDragon** [comment]
> It is assuming the install root directory is only one level higher hence the error occurs.

Try to patch it manually in `vcpkg\installed\x64-windows\share\ceres\`. Will it help?

**Comment by jasjuang** [comment]
@KindDragon I patched CeresConfig.cmake line 134 manually to 

``````
get_filename_component(CURRENT_ROOT_INSTALL_DIR
    ${CERES_CURRENT_CONFIG_DIR}/../../
    ABSOLUTE)
``````

But now I got a Eigen not found error, I have eigen3 installed in vcpkg prior installing ceres. One thing I do noticed that is weird is when I install ceres eigen3 wasn't listed as it's dependencies, which could be causing potential problems.

``````
CMake Error at C:/dev/vcpkg/packages/ceres_x64-windows/share/ceres/CeresConfig.cmake:88 (message):
  Failed to find Ceres - Missing required Ceres dependency: Eigen version
  3.3.3, please set EIGEN_INCLUDE_DIR.
Call Stack (most recent call first):
  C:/dev/vcpkg/packages/ceres_x64-windows/share/ceres/CeresConfig.cmake:227 (ceres_report_not_found)
  apps/CeresMinimalExample/CMakeLists.txt:19 (find_package)


CMake Error at apps/CeresMinimalExample/CMakeLists.txt:19 (find_package):
  Found package configuration file:

    C:/dev/vcpkg/packages/ceres_x64-windows/share/ceres/CeresConfig.cmake

  but it set Ceres_FOUND to FALSE so package "Ceres" is considered to be NOT
  FOUND.


-- Configuring incomplete, errors occurred!
``````

**Comment by jasjuang** [comment]
The eigen error is actually fixed by the latest ceres as indicated in #1284, but I am unable to build ceres with the newest ceres by `vcpkg install ceres --head`.

**Comment by KindDragon** [comment]
> but I also realized FindEigen.cmake by Ceres is not copied to the same directory where CeresConfig.cmake is in vcpkg, still trying to figure out the problem...

I delete it manually https://github.com/KindDragon/vcpkg/blob/27bb11f6fc0da827190571125b62db8df5c86c68/ports/ceres/portfile.cmake#L66-L68. I think FindEigen.cmake can affect other packages that use Eigen

**Comment by jasjuang** [comment]
@KindDragon We will have to figure out why there is a build fail when doing `vcpkg install ceres --head` before dealing with Eigen dependencies, it is still unclear to me what's going on internally when `vcpkg install` is called. When I build Ceres from source the very standard way everything builds and works.

``````
git clone https://github.com/ceres-solver/ceres-solver 
cd ceres-solver && mkdir build && cd build
cmake -A x64 ..
msbuild Ceres.sln /p:Configuration=Release
msbuild INSTALL.vcxproj /p:Configuration=Release
``````

**Comment by jasjuang** [comment]
@KindDragon Here are some updates on my investigation of the build fail with `vcpkg install ceres --head`. The error message is

``````
     4>libcholmod.lib(cholmod_ccolamd.o.obj) : error LNK2019: unresolved external symbol ccolamd_recommended referenced in function cholmod_ccolamd [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>libcholmod.lib(cholmod_ccolamd.o.obj) : error LNK2019: unresolved external symbol ccolamd_set_defaults referenced in function ccolamd_interface [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>libcholmod.lib(cholmod_csymamd.o.obj) : error LNK2001: unresolved external symbol ccolamd_set_defaults [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>libcholmod.lib(cholmod_ccolamd.o.obj) : error LNK2019: unresolved external symbol ccolamd referenced in function ccolamd_interface [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>libcholmod.lib(cholmod_csymamd.o.obj) : error LNK2019: unresolved external symbol csymamd referenced in function cholmod_csymamd [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>libcholmod.lib(cholmod_l_ccolamd.o.obj) : error LNK2019: unresolved external symbol ccolamd_l_recommended referenced in function cholmod_l_ccolamd [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>libcholmod.lib(cholmod_l_ccolamd.o.obj) : error LNK2019: unresolved external symbol ccolamd_l_set_defaults referenced in function ccolamd_interface [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>libcholmod.lib(cholmod_l_csymamd.o.obj) : error LNK2001: unresolved external symbol ccolamd_l_set_defaults [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>libcholmod.lib(cholmod_l_ccolamd.o.obj) : error LNK2019: unresolved external symbol ccolamd_l referenced in function ccolamd_interface [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>libcholmod.lib(cholmod_l_csymamd.o.obj) : error LNK2019: unresolved external symbol csymamd_l referenced in function cholmod_l_csymamd [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\bin\Release\ceres.dll : fatal error LNK1120: 8 unresolved externals [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>Done Building Project "C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj" (default targets) -- FAILED.
     3>Done Building Project "C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\ALL_BUILD.vcxproj" (default targets) -- FAILED.
     1>Done Building Project "C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\install.vcxproj" (default targets) -- FAILED.

Build FAILED.
``````

If the current release of ceres compiles fine with SuiteSparse 4.5.5, my guess is the latest ceres might be requiring a newer SuiteSparse. I will file an issue at ceres to find out.
