### PR TITLE
Update baselines 2025-08-11.

### PR DESCRIPTION
**Pull request by BillyONeal**
Results from the Friday evening full rebuild: https://dev.azure.com/vcpkg/public/_build/results?buildId=118841&view=results

All the Windows ones are passing-remove-from-fail-lists already fixed in https://github.com/microsoft/vcpkg/pull/46834

> PASSING, REMOVE FROM FAIL LIST: elfio:x64-android (/vcpkg/scripts/azure-pipelines/../ci.baseline.txt).
> PASSING, REMOVE FROM FAIL LIST: elfio:x64-android (/vcpkg/scripts/azure-pipelines/../ci.baseline.txt).
> PASSING, REMOVE FROM FAIL LIST: paho-mqtt:arm-neon-android (/vcpkg/scripts/azure-pipelines/../ci.baseline.txt).
> PASSING, REMOVE FROM FAIL LIST: paho-mqtt:x64-android (/vcpkg/scripts/azure-pipelines/../ci.baseline.txt).
> PASSING, REMOVE FROM FAIL LIST: paho-mqtt:x64-android (/vcpkg/scripts/azure-pipelines/../ci.baseline.txt).
> PASSING, REMOVE FROM FAIL LIST: poppler:arm-neon-android (/vcpkg/scripts/azure-pipelines/../ci.baseline.txt).
> PASSING, REMOVE FROM FAIL LIST: poppler:x64-android (/vcpkg/scripts/azure-pipelines/../ci.baseline.txt).
> PASSING, REMOVE FROM FAIL LIST: poppler:x64-android (/vcpkg/scripts/azure-pipelines/../ci.baseline.txt).
> REGRESSION: paho-mqttpp3:arm-neon-android failed with BUILD_FAILED. If expected, add paho-mqttpp3:arm-neon-android=fail to /vcpkg/scripts/azure-pipelines/../ci.baseline.txt.
> REGRESSION: paho-mqttpp3:x64-android failed with BUILD_FAILED. If expected, add paho-mqttpp3:x64-android=fail to /vcpkg/scripts/azure-pipelines/../ci.baseline.txt.
> REGRESSION: paho-mqttpp3:x64-android failed with BUILD_FAILED. If expected, add paho-mqttpp3:x64-android=fail to /vcpkg/scripts/azure-pipelines/../ci.baseline.txt.

All of the above probably caused by https://github.com/microsoft/vcpkg/pull/41293 . Note that paho-mqttpp3 was previously blocked by paho-mqtt so this is not actually a regression.

> REGRESSION: graphicsmagick:arm-neon-android failed with BUILD_FAILED. If expected, add graphicsmagick:arm-neon-android=fail to /vcpkg/scripts/azure-pipelines/../ci.baseline.txt.
> REGRESSION: graphicsmagick:x64-android failed with BUILD_FAILED. If expected, add graphicsmagick:x64-android=fail to /vcpkg/scripts/azure-pipelines/../ci.baseline.txt.
> REGRESSION: graphicsmagick:x64-android failed with BUILD_FAILED. If expected, add graphicsmagick:x64-android=fail to /vcpkg/scripts/azure-pipelines/../ci.baseline.txt.

The actual error:

> ld.lld: error: undefined symbol: __android_log_write

Probably caused by https://github.com/microsoft/vcpkg/pull/46725 and/or stealth merge conflict with https://github.com/microsoft/vcpkg/pull/41293 ... hopefully fixed in https://github.com/microsoft/vcpkg/pull/46839 ? We'll see if it's still there next time.

### CODE REVIEW

**Comment by BillyONeal** [comment]
```console
/mnt/vcpkg-ci/b/elfio/src/lease_3.12-7537cd193f.clean/examples/writer/writer.cpp:42:18: error: expected unqualified-id
   42 | const Elf_Xword  PAGE_SIZE = 0x1000;
      |                  ^
/android-ndk-r28c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/bits/page_size.h:45:19: note: expanded from macro 'PAGE_SIZE'
   45 | #define PAGE_SIZE 4096
      |                   ^
1 error generated.
```

Not sure why in my local test using the same container this didn't happen, but in CI it did. Either way, we shouldn't be building the examples.

**Review by vicroms — APPROVED** [review]
