### ISSUE TITLE
Error: Building package realsense2:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by evarcurto** [microsoft/vcpkg#11752]
Host Environment

    OS: Ubuntu 16.04
    Compiler: gcc 5.5.0

I'm trying to install the realsense software following these steps (https://github.com/IntelRealSense/librealsense). When I run **./vcpkg install realsense2** this error appears:

```
Computing installation plan...
The following packages will be built and installed:
    realsense2[core]:x64-linux
Starting package 1/1: realsense2:x64-linux
Building package realsense2[core]:x64-linux...
-- Using cached /home/eva-isr/vcpkg/downloads/IntelRealSense-librealsense-025fccf76803ee6a6e60de9f18ac6193b7ff8597.tar.gz
-- Using source at /home/eva-isr/vcpkg/buildtrees/realsense2/src/93b7ff8597-4347a45ee5
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /home/eva-isr/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /home/eva-isr/vcpkg/buildtrees/realsense2/x64-linux-dbg
    See logs for more information:
      /home/eva-isr/vcpkg/buildtrees/realsense2/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/realsense2/portfile.cmake:47 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)


Error: Building package realsense2:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: realsense2:x64-linux
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.

```

**Comment by LilyWangL** [comment]
`realsense2` build failed on Linux with the following error, now `libusb` build failed on Linux, and it will be fixed in PR #9561. Waiting for PR #9561 merged, I will continue fix `realsense2:x64-linux` build error.
```
vcpkg/buildtrees/realsense2/x64-linux-dbg/third-party/libusb/libusb/core.c:23:10: fatal error: config.h: No such file or directory
vcpkg/buildtrees/realsense2/x64-linux-dbg/third-party/libusb/libusb/hotplug.c:22:10: fatal error: config.h: No such file or directory
vcpkg/buildtrees/realsense2/x64-linux-dbg/third-party/libusb/libusb/descriptor.c:22:10: fatal error: config.h: No such file or directory
```

**Comment by RustyRaptor** [comment]
Repeated on my machine

```bash
./vcpkg install realsense2
Computing installation plan...
The following packages will be built and installed:
    realsense2[core]:x64-linux
Starting package 1/1: realsense2:x64-linux
Building package realsense2[core]:x64-linux...
-- Downloading https://github.com/IntelRealSense/librealsense/archive/025fccf76803ee6a6e60de9f18ac6193b7ff8597.tar.gz...
-- Extracting source /home/etv/vcpkg/downloads/IntelRealSense-librealsense-025fccf76803ee6a6e60de9f18ac6193b7ff8597.tar.gz
-- Applying patch fix_openni2.patch
-- Applying patch fix-dependency-glfw3.patch
-- Using source at /home/etv/vcpkg/buildtrees/realsense2/src/93b7ff8597-4347a45ee5
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /home/etv/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /home/etv/vcpkg/buildtrees/realsense2/x64-linux-dbg
    See logs for more information:
      /home/etv/vcpkg/buildtrees/realsense2/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/realsense2/portfile.cmake:47 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)


Error: Building package realsense2:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: realsense2:x64-linux
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.
```

**Comment by jvdrhoof** [comment]
Repeated on Ubuntu 18.04 with a newer Vcpkg version. Any update on this?

```
Computing installation plan...
The following packages will be built and installed:
    realsense2[core]:x64-linux
Detecting compiler hash for triplet x64-linux...
Starting package 1/1: realsense2:x64-linux
Building package realsense2[core]:x64-linux...
Could not locate cached archive: /home/jvdhooft/.cache/vcpkg/archives/ec/ecb61cb4bdd659a5f003454dd50e0357f6bb52ec.zip
-- Using cached /home/jvdhooft/vcpkg/downloads/IntelRealSense-librealsense-025fccf76803ee6a6e60de9f18ac6193b7ff8597.tar.gz
-- Cleaning sources at /home/jvdhooft/vcpkg/buildtrees/realsense2/src/93b7ff8597-4347a45ee5.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/jvdhooft/vcpkg/downloads/IntelRealSense-librealsense-025fccf76803ee6a6e60de9f18ac6193b7ff8597.tar.gz
-- Applying patch fix_openni2.patch
-- Applying patch fix-dependency-glfw3.patch
-- Using source at /home/jvdhooft/vcpkg/buildtrees/realsense2/src/93b7ff8597-4347a45ee5.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:139 (message):
    Command failed: /home/jvdhooft/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /home/jvdhooft/vcpkg/buildtrees/realsense2/x64-linux-dbg
    See logs for more information:
      /home/jvdhooft/vcpkg/buildtrees/realsense2/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/realsense2/portfile.cmake:47 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)


Error: Building package realsense2:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: realsense2:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.
```

**Comment by TechNyquist** [comment]
Very same problem on CentOS Linux release 7.8.2003 (Core).
PR #9561 seems merged. @LilyWangL any news about this issue? Maybe even a workaround waiting for the fix? Thanks.

**Comment by LilyWangL** [comment]
Thanks for your reply. I will confirm this issue soon.

**Comment by adamanov** [comment]
hello I have a same issue, Any furthre imporvement on this problem?

```
robolabjackal1@robolabjackal1:~/libraries/vcpkg$ ./vcpkg install realsense2
Computing installation plan...
A suitable version of cmake was not found (required v3.22.2). Downloading portable cmake v3.22.2...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-linux-x86_64.tar.gz -> /home/robolabjackal1/libraries/vcpkg/downloads/cmake-3.22.2linux-x86_64.tar.gz
Extracting cmake...
The following packages will be built and installed:
  * libusb[core]:x64-linux -> 1.0.24#7
    realsense2[core]:x64-linux -> 2.50.0
  * vcpkg-cmake[core]:x64-linux -> 2022-01-19
  * vcpkg-cmake-config[core]:x64-linux -> 2022-02-06
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
A suitable version of ninja was not found (required v1.10.2). Downloading portable ninja v1.10.2...
Downloading ninja...
  https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip -> /home/robolabjackal1/libraries/vcpkg/downloads/ninja-linux-1.10.2.zip
Extracting ninja...
Restored 3 packages from /home/robolabjackal1/.cache/vcpkg/archives in 9.244 ms. Use --debug to see more details.
Starting package 1/4: libusb:x64-linux
Installing package libusb[core]:x64-linux...
Elapsed time for package libusb:x64-linux: 1.178 ms
Starting package 2/4: vcpkg-cmake:x64-linux
Installing package vcpkg-cmake[core]:x64-linux...
Elapsed time for package vcpkg-cmake:x64-linux: 1.51 ms
Starting package 3/4: vcpkg-cmake-config:x64-linux
Installing package vcpkg-cmake-config[core]:x64-linux...
Elapsed time for package vcpkg-cmake-config:x64-linux: 332.5 us
Starting package 4/4: realsense2:x64-linux
Building package realsense2[core]:x64-linux...
-- Downloading https://github.com/IntelRealSense/librealsense/archive/v2.50.0.tar.gz -> IntelRealSense-librealsense-v2.50.0.tar.gz...
-- Extracting source /home/robolabjackal1/libraries/vcpkg/downloads/IntelRealSense-librealsense-v2.50.0.tar.gz
-- Applying patch fix_openni2.patch
-- Applying patch fix_config_osx.patch
-- Using source at /home/robolabjackal1/libraries/vcpkg/buildtrees/realsense2/src/v2.50.0-ec78fddb81.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: /home/robolabjackal1/libraries/vcpkg/downloads/tools/cmake-3.22.2-linux/cmake-3.22.2-linux-x86_64/bin/cmake --build . --config Release --target install -- -v -j13
    Working Directory: /home/robolabjackal1/libraries/vcpkg/buildtrees/realsense2/x64-linux-rel
    See logs for more information:
      /home/robolabjackal1/libraries/vcpkg/buildtrees/realsense2/install-x64-linux-rel-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/realsense2/portfile.cmake:47 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)


Error: Building package realsense2:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+realsense2
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[realsense2]+Build+error
including:
  package: realsense2[core]:x64-linux -> 2.50.0
    vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
    vcpkg-scripts version: 440075a9f 2022-03-23 (11 hours ago)

Additionally, attach any relevant sections from the log files above.
```

**Comment by Zrealshadow** [comment]
I have same issues. Anyone have solutions ? Many thanks
