### ISSUE TITLE
poco port x64-windows-static failure 

### ISSUE THREAD

**Issue by brucebob** [Microsoft/vcpkg#475]
C:\vcpkg\buildtrees\poco\src\poco-poco-1.7.6-release\Foundation\include\Poco/RegularExpression.h(31): fatal error C1083: Cannot open include file: 'pcre.h': No such file or directory [C:\vcpkg\buildtrees\poco\x64-windows-static-rel\JSON\JSON.vcxproj]

Ran on a clean machine and still get the same unable to find include.

**Comment by Shadowrom2020** [comment]
+1, same error here.
Package: poco:x64-windows
  Vcpkg version: 0.0.71-1888c7294fb5323acef33dae26f39bf7c2d4dfa7

[package-x64-windows-rel-out.txt](https://github.com/Microsoft/vcpkg/files/748339/package-x64-windows-rel-out.txt)

**Comment by ras0219-msft** [comment]
From #632 (indicating that this still occurs on recent versions):
> Package: poco:x64-windows
Vcpkg version: 0.0.71-ce477bf21998c80afc551de72c6140178de3a114
poco is unable to find pcre.h, build fails.

**Comment by ras0219-msft** [comment]
Ok, I am able to reproduce this locally. Looking further, it seems like POCO _is_ correctly finding PCRE's include directory.
```
// buildtrees\poco\x86-windows-rel\CMakeCache.txt
...
//Path to a file.
PCRE_INCLUDE_DIR:PATH=D:/src/vcpkg/installed/x86-windows/include
...
```
However it isn't actually including it during the JSON component build (the one that fails); only during the Foundation build. This was a "regression" introduced in https://github.com/pocoproject/poco/commit/e863111a2c5aa6bd7d4bd0dc656f81fc26e812ad to fix another issue.

I am now testing a fix which adds `${PCRE_INCLUDE_DIRS}` to the `PUBLIC` section of the Foundation library target inside POCO. This should automatically cause all other targets that depend on Foundation to have the PCRE header path added.

**Comment by ras0219-msft** [comment]
I've uploaded the above fix. Please let me know if this did not solve the issue on your machine!

**Comment by brucebob** [comment]
Can confirm x64-windows-static rel and dbg both building and linking
