### PR TITLE
[tesseract] Fix non-Windows build

### LINKED ISSUE #13622: [tesseract] build failure on Alpine (Docker)
**Host Environment**
- OS: Alpine 3.12 (docker)
- Compiler: gcc version 9.3.0 (Alpine 9.3.0) Target: x86_64-alpine-linux-musl

**To Reproduce**
Dockerfile:
```
FROM alpine:3.12 as builder

RUN apk update && apk add --no-cache pkgconfig autoconf build-base binutils cmake curl file gcc g++ git libgcc libtool linux-headers make musl-dev ninja tar zip unzip wget

RUN cd /tmp \
    && git clone https://github.com/Microsoft/vcpkg.git --depth 1 \ 
    && cd vcpkg \
    && ./bootstrap-vcpkg.sh -useSystemBinaries

RUN VCPKG_FORCE_SYSTEM_BINARIES=1 ./tmp/vcpkg/vcpkg install tesseract
```

**Failure logs** 
```
-- Building x64-linux-musl-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: /usr/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /tmp/vcpkg/buildtrees/tesseract/x64-linux-musl-dbg
    See logs for more information:
      /tmp/vcpkg/buildtrees/tesseract/install-x64-linux-musl-dbg-out.log
      /tmp/vcpkg/buildtrees/tesseract/install-x64-linux-musl-dbg-err.log
```

Excerpt from install-x64-linux-musl-dbg-out.log
```
In file included from /tmp/vcpkg/buildtrees/tesseract/src/4.1.1-1402ed03b0.clean/src/api/capi.h:27,
                 from /tmp/vcpkg/buildtrees/tesseract/src/4.1.1-1402ed03b0.clean/src/api/capi.cpp:21:
/tmp/vcpkg/buildtrees/tesseract/src/4.1.1-1402ed03b0.clean/src/ccutil/ocrclass.h:117:18: error: field 'end_time' has incomplete type 'timeval'
  117 |   struct timeval end_time;
      |                  ^~~~~~~~
/tmp/vcpkg/buildtrees/tesseract/src/4.1.1-1402ed03b0.clean/src/ccutil/ocrclass.h:117:10: note: forward declaration of 'struct timeval'
  117 |   struct timeval end_time;
      |          ^~~~~~~
/tmp/vcpkg/buildtrees/tesseract/src/4.1.1-1402ed03b0.clean/src/ccutil/ocrclass.h: In member function 'bool ETEXT_DESC::deadline_exceeded() const':
/tmp/vcpkg/buildtrees/tesseract/src/4.1.1-1402ed03b0.clean/src/ccutil/ocrclass.h:142:20: error: aggregate 'timeval now' has incomplete type and cannot be defined
  142 |     struct timeval now;
      |                    ^~~
...
```

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

### PR DESCRIPTION
**Pull request by JackBoosY**
Use [official patch](https://github.com/i-net-software/docker-boxes/commit/71f48e7e762334705700628348a380e5cc0580c3) to fix the non-Windows build error:
```
In file included from /tmp/vcpkg/buildtrees/tesseract/src/4.1.1-1402ed03b0.clean/src/api/capi.h:27,
                 from /tmp/vcpkg/buildtrees/tesseract/src/4.1.1-1402ed03b0.clean/src/api/capi.cpp:21:
/tmp/vcpkg/buildtrees/tesseract/src/4.1.1-1402ed03b0.clean/src/ccutil/ocrclass.h:117:18: error: field 'end_time' has incomplete type 'timeval'
  117 |   struct timeval end_time;
      |                  ^~~~~~~~
/tmp/vcpkg/buildtrees/tesseract/src/4.1.1-1402ed03b0.clean/src/ccutil/ocrclass.h:117:10: note: forward declaration of 'struct timeval'
  117 |   struct timeval end_time;
      |          ^~~~~~~
/tmp/vcpkg/buildtrees/tesseract/src/4.1.1-1402ed03b0.clean/src/ccutil/ocrclass.h: In member function 'bool ETEXT_DESC::deadline_exceeded() const':
/tmp/vcpkg/buildtrees/tesseract/src/4.1.1-1402ed03b0.clean/src/ccutil/ocrclass.h:142:20: error: aggregate 'timeval now' has incomplete type and cannot be defined
  142 |     struct timeval now;
      |                    ^~~
...
```

Fixes #13622.

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by JackBoosY** [comment]
Regression will be fixed by https://github.com/microsoft/vcpkg/pull/20439.

File: ports/tesseract/portfile.cmake [hunk 1]
```diff
@@ -22,9 +24,8 @@ else()
     set(TARGET_ARCHITECTURE auto)
 endif()
 
-vcpkg_configure_cmake(
+vcpkg_cmake_configure(
     SOURCE_PATH ${SOURCE_PATH}
```
Comment (PhoebeHui) [inline ports/tesseract/portfile.cmake:28]:
```suggestion
    SOURCE_PATH "${SOURCE_PATH}"
```

**Review by PhoebeHui — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the fix!
