### ISSUE TITLE
[openssl] windows static consumer link broken.

### ISSUE THREAD

**Issue by Hoikas** [microsoft/vcpkg#19081]
Consuming static triplets of openssl is broken on Windows after #18042.

**Environment**
- OS: Windows 10
- Compiler: MSVC 16.10.3

**To Reproduce**
1. Try to build a project against static openssl.

**Expected behavior**
For it to work like before #18042.

**Failure logs** 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol __imp__CertOpenStore@20	MaxMain	D:\Plasma\CyanWorlds.comEngine\build\vc++2019-x86\Sources\Tools\MaxMain\libcrypto.lib(e_capi.obj)	1	
Error	LNK2001	unresolved external symbol __imp__CertCloseStore@8	MaxMain	D:\Plasma\CyanWorlds.comEngine\build\vc++2019-x86\Sources\Tools\MaxMain\libcrypto.lib(e_capi.obj)	1	
Error	LNK2001	unresolved external symbol __imp__CertEnumCertificatesInStore@8	MaxMain	D:\Plasma\CyanWorlds.comEngine\build\vc++2019-x86\Sources\Tools\MaxMain\libcrypto.lib(e_capi.obj)	1	
Error	LNK2001	unresolved external symbol __imp__CertFindCertificateInStore@24	MaxMain	D:\Plasma\CyanWorlds.comEngine\build\vc++2019-x86\Sources\Tools\MaxMain\libcrypto.lib(e_capi.obj)	1	
Error	LNK2001	unresolved external symbol __imp__CertDuplicateCertificateContext@4	MaxMain	D:\Plasma\CyanWorlds.comEngine\build\vc++2019-x86\Sources\Tools\MaxMain\libcrypto.lib(e_capi.obj)	1	
Error	LNK2001	unresolved external symbol __imp__CertFreeCertificateContext@4	MaxMain	D:\Plasma\CyanWorlds.comEngine\build\vc++2019-x86\Sources\Tools\MaxMain\libcrypto.lib(e_capi.obj)	1	
Error	LNK2001	unresolved external symbol __imp__CertGetCertificateContextProperty@16	MaxMain	D:\Plasma\CyanWorlds.comEngine\build\vc++2019-x86\Sources\Tools\MaxMain\libcrypto.lib(e_capi.obj)	1
```	

**Additional context**
PR in progress.

**Comment by PhoebeHui** [comment]
@Hoikas, thanks for reporting this issue and working a PR for this!

We have PR https://github.com/microsoft/vcpkg/pull/18475 to fix the same issue, currently it has been merged, please get latest source and try again.
