### ISSUE TITLE
[glib] glib:x64-osx is failing

### ISSUE THREAD

**Issue by Rastaban** [microsoft/vcpkg#5661]
[config-x64-osx-dbg-err.log](https://github.com/Microsoft/vcpkg/files/2963725/config-x64-osx-dbg-err.log)
[config-x64-osx-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2963726/config-x64-osx-dbg-out.log)

**Comment by angelmixu** [comment]
For me it's building correctly when using static libraries (I'm building pango: ./vcpkg install pango).

What it has been failing is when building dynamic libraries, I've been some days going around it for fixing, and talked on the cpplang channel about the best approach, but... I still can't build it correctly.

When building pango, and thus glib as a dependency using dynamic linkage, there's an error but we can't see much of it. I had to go to `buildtrees/glib/x64-osx-dbg/config/config.log` to take a look, configure script was failing.

I could see the following:

```
result: 
configure:8299: checking for ngettext in -lintl
configure:8324: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -o conftest -fPIC  -I/Users/angel/code/vcpkg/in
stalled/x64-osx/include -I/Users/angel/code/vcpkg/installed/x64-osx/include -L/Users/angel/code/vcpkg/installed/x64-osx/debug/lib -Wl,-framework,Carbon -
Wl,-framework,Foundation conftest.c -lintl -liconv  >&5
ld: library not found for -lintl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:8324: $? = 1
```

And looking at `installed/x64-osx/lib/` or `installed/x64-osx/debug/lib/` I can't find any libintl.dylib, so I took a look at bin directory and there was it.

Going to the gettext port, in the CMakeLists.txt I can see the following:

```
 install(TARGETS libintl
   EXPORT unofficial-gettext-targets
   RUNTIME DESTINATION bin
   LIBRARY DESTINATION bin
   ARCHIVE DESTINATION lib
 )
```

In most of the ports I could take a look, the LIBRARY DESTINATION was set to lib, so looks like dylibs also should be put on lib, and not on bin directory.
After rebuilding gettext with the new .dylib destination I could find another error on the config.log from glib:

```
configure:22022: checking size of long long
configure:22027: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -o conftest -fPIC  -I/Users/angel/code/vcpkg/i
nstalled/x64-osx/include -I/Users/angel/code/vcpkg/installed/x64-osx/include -L/Users/angel/code/vcpkg/installed/x64-osx/debug/lib -Wl,-framework,Carbon 
-Wl,-framework,Foundation conftest.c -lintl  -Wl,-framework -Wl,CoreFoundation  >&5
configure:22027: $? = 0
configure:22027: ./conftest
dyld: Library not loaded: @rpath/libintl.dylib
  Referenced from: /Users/angel/code/vcpkg/buildtrees/glib/x64-osx-dbg/config/./conftest
  Reason: image not found
/Users/angel/code/vcpkg/buildtrees/glib/src/2.52.3-624b8d46d4/configure: line 2057: 76814 Abort trap: 6           ./conftest$ac_exeext
configure:22027: $? = 134
configure: program exited with status 134
```

It link correctly, but it can't find the library on the rpath when running the executable test.
I tried to set `CMAKE_INSTALL_RPATH_USE_LINK_PATH` to true, and set CMAKE_INSTALL_RPATH and CMAKE_BUILD_RPATH to ${LIB_DIR} but it didn't work.

I had to append the `-rpath ${LIB_DIR}` to the LDFLAGS variable before the configure step on glib/CMakeLists.txt as follows:

```
if(BUILD_SHARED_LIBS)
            set(LDFLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${CMAKE_SHARED_LINKER_FLAGS_${UPPER_CONFIG}} -L${LIB_DIR} -rpath ${LIB_DIR}")
        else()
            set(LDFLAGS "${CMAKE_STATIC_LINKER_FLAGS} ${CMAKE_STATIC_LINKER_FLAGS_${UPPER_CONFIG}} -L${LIB_DIR}")
        endif()
```

This way configure was detecting correctly all the stuff.
Then, later, another error arise, but this time when compiling and linking glib:

```
[340/347] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DDLL_EXPORT -DGIO_MODULE_DIR=\"gio/modules\" -DGLIB_COMPILATION -DG_ENABLE_DEBUG -DG_LOG_DOMAIN=\"GLib\" -DLIBDIR=\"\" -Dglib_EXPORTS -Iconfig -Iconfig/glib -Iconfig/gio -Iconfig/gmodule -I/Users/angel/code/vcpkg/buildtrees/glib/src/2.52.3-624b8d46d4/. -I/Users/angel/code/vcpkg/buildtrees/glib/src/2.52.3-624b8d46d4/glib -I/Users/angel/code/vcpkg/installed/x64-osx/include -fPIC -g -fPIC   -std=gnu11 -MD -MT CMakeFiles/glib.dir/glib/gspawn.c.o -MF CMakeFiles/glib.dir/glib/gspawn.c.o.d -o CMakeFiles/glib.dir/glib/gspawn.c.o   -c /Users/angel/code/vcpkg/buildtrees/glib/src/2.52.3-624b8d46d4/glib/gspawn.c
[341/347] : && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -g  -dynamiclib -Wl,-headerpad_max_install_names  -o libglib-2.dylib -install_name @rpath/libglib-2.dylib CMakeFiles/glib.dir/glib/deprecated/gallocator.c.o CMakeFiles/glib.dir/glib/deprecated/gcache.c.o CMakeFiles/glib.dir/glib/deprecated/gcompletion.c.o CMakeFiles/glib.dir/glib/deprecated/grel.c.o CMakeFiles/glib.dir/glib/deprecated/gthread-deprecated.c.o CMakeFiles/glib.dir/glib/garray.c.o CMakeFiles/glib.dir/glib/gasyncqueue.c.o CMakeFiles/glib.dir/glib/gatomic.c.o CMakeFiles/glib.dir/glib/gbacktrace.c.o CMakeFiles/glib.dir/glib/gbase64.c.o CMakeFiles/glib.dir/glib/gbitlock.c.o CMakeFiles/glib.dir/glib/gbookmarkfile.c.o CMakeFiles/glib.dir/glib/gbytes.c.o CMakeFiles/glib.dir/glib/gcharset.c.o CMakeFiles/glib.dir/glib/gchecksum.c.o CMakeFiles/glib.dir/glib/gconvert.c.o CMakeFiles/glib.dir/glib/gdataset.c.o CMakeFiles/glib.dir/glib/gdate.c.o CMakeFiles/glib.dir/glib/gdatetime.c.o CMakeFiles/glib.dir/glib/gdir.c.o CMakeFiles/glib.dir/glib/genviron.c.o CMakeFiles/glib.dir/glib/gerror.c.o CMakeFiles/glib.dir/glib/gfileutils.c.o CMakeFiles/glib.dir/glib/ggettext.c.o CMakeFiles/glib.dir/glib/ghash.c.o CMakeFiles/glib.dir/glib/ghmac.c.o CMakeFiles/glib.dir/glib/ghook.c.o CMakeFiles/glib.dir/glib/ghostutils.c.o CMakeFiles/glib.dir/glib/giochannel.c.o CMakeFiles/glib.dir/glib/gkeyfile.c.o CMakeFiles/glib.dir/glib/glib-init.c.o CMakeFiles/glib.dir/glib/glib-private.c.o CMakeFiles/glib.dir/glib/glist.c.o CMakeFiles/glib.dir/glib/gmain.c.o CMakeFiles/glib.dir/glib/gmappedfile.c.o CMakeFiles/glib.dir/glib/gmarkup.c.o CMakeFiles/glib.dir/glib/gmem.c.o CMakeFiles/glib.dir/glib/gmessages.c.o CMakeFiles/glib.dir/glib/gnode.c.o CMakeFiles/glib.dir/glib/goption.c.o CMakeFiles/glib.dir/glib/gpattern.c.o CMakeFiles/glib.dir/glib/gpoll.c.o CMakeFiles/glib.dir/glib/gprimes.c.o CMakeFiles/glib.dir/glib/gqsort.c.o CMakeFiles/glib.dir/glib/gquark.c.o CMakeFiles/glib.dir/glib/gqueue.c.o CMakeFiles/glib.dir/glib/grand.c.o CMakeFiles/glib.dir/glib/gregex.c.o CMakeFiles/glib.dir/glib/gscanner.c.o CMakeFiles/glib.dir/glib/gsequence.c.o CMakeFiles/glib.dir/glib/gshell.c.o CMakeFiles/glib.dir/glib/gslice.c.o CMakeFiles/glib.dir/glib/gslist.c.o CMakeFiles/glib.dir/glib/gstdio.c.o CMakeFiles/glib.dir/glib/gstrfuncs.c.o CMakeFiles/glib.dir/glib/gstring.c.o CMakeFiles/glib.dir/glib/gstringchunk.c.o CMakeFiles/glib.dir/glib/gtestutils.c.o CMakeFiles/glib.dir/glib/gthread.c.o CMakeFiles/glib.dir/glib/gthreadpool.c.o CMakeFiles/glib.dir/glib/gtimer.c.o CMakeFiles/glib.dir/glib/gtimezone.c.o CMakeFiles/glib.dir/glib/gtranslit.c.o CMakeFiles/glib.dir/glib/gtrashstack.c.o CMakeFiles/glib.dir/glib/gtree.c.o CMakeFiles/glib.dir/glib/guniprop.c.o CMakeFiles/glib.dir/glib/gutf8.c.o CMakeFiles/glib.dir/glib/gunibreak.c.o CMakeFiles/glib.dir/glib/gunicollate.c.o CMakeFiles/glib.dir/glib/gunidecomp.c.o CMakeFiles/glib.dir/glib/gurifuncs.c.o CMakeFiles/glib.dir/glib/gutils.c.o CMakeFiles/glib.dir/glib/guuid.c.o CMakeFiles/glib.dir/glib/gvariant.c.o CMakeFiles/glib.dir/glib/gvariant-core.c.o CMakeFiles/glib.dir/glib/gvariant-parser.c.o CMakeFiles/glib.dir/glib/gvariant-serialiser.c.o CMakeFiles/glib.dir/glib/gvarianttypeinfo.c.o CMakeFiles/glib.dir/glib/gvarianttype.c.o CMakeFiles/glib.dir/glib/gversion.c.o CMakeFiles/glib.dir/glib/gwakeup.c.o CMakeFiles/glib.dir/glib/gprintf.c.o CMakeFiles/glib.dir/glib/gnulib/asnprintf.c.o CMakeFiles/glib.dir/glib/gnulib/printf-args.c.o CMakeFiles/glib.dir/glib/gnulib/printf-parse.c.o CMakeFiles/glib.dir/glib/gnulib/printf.c.o CMakeFiles/glib.dir/glib/gnulib/vasnprintf.c.o CMakeFiles/glib.dir/glib/libcharset/localcharset.c.o CMakeFiles/glib.dir/glib/gthread-posix.c.o CMakeFiles/glib.dir/glib/giounix.c.o CMakeFiles/glib.dir/glib/gspawn.c.o CMakeFiles/glib.dir/glib/glib-unix.c.o  -Wl,-rpath,/Users/angel/code/vcpkg/installed/x64-osx/debug/lib -framework CoreServices -framework CoreFoundation -framework Foundation /Users/angel/code/vcpkg/installed/x64-osx/debug/lib/libpcre.dylib /Users/angel/code/vcpkg/installed/x64-osx/debug/lib/libintl.dylib -liconv -lcharset && :
[342/347] : && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -g  -dynamiclib -Wl,-headerpad_max_install_names  -o libgthread-2.dylib -install_name @rpath/libgthread-2.dylib CMakeFiles/gthread.dir/gthread/gthread-impl.c.o  -Wl,-rpath,/Users/angel/code/vcpkg/buildtrees/glib/x64-osx-dbg -Wl,-rpath,/Users/angel/code/vcpkg/installed/x64-osx/debug/lib -framework CoreServices -framework CoreFoundation -framework Foundation libglib-2.dylib /Users/angel/code/vcpkg/installed/x64-osx/debug/lib/libintl.dylib -framework CoreServices -framework CoreFoundation -framework Foundation && :
[343/347] : && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -g  -dynamiclib -Wl,-headerpad_max_install_names  -o libgmodule-2.dylib -install_name @rpath/libgmodule-2.dylib CMakeFiles/gmodule.dir/gmodule/gmodule.c.o  -Wl,-rpath,/Users/angel/code/vcpkg/buildtrees/glib/x64-osx-dbg -Wl,-rpath,/Users/angel/code/vcpkg/installed/x64-osx/debug/lib -framework CoreServices -framework CoreFoundation -framework Foundation libglib-2.dylib /Users/angel/code/vcpkg/installed/x64-osx/debug/lib/libintl.dylib -framework CoreServices -framework CoreFoundation -framework Foundation && :
[344/347] : && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -g  -dynamiclib -Wl,-headerpad_max_install_names  -o libkqueue-2.dylib -install_name @rpath/libkqueue-2.dylib CMakeFiles/kqueue.dir/gio/kqueue/dep-list.c.o CMakeFiles/kqueue.dir/gio/kqueue/gkqueuefilemonitor.c.o CMakeFiles/kqueue.dir/gio/kqueue/kqueue-exclusions.c.o CMakeFiles/kqueue.dir/gio/kqueue/kqueue-helper.c.o CMakeFiles/kqueue.dir/gio/kqueue/kqueue-missing.c.o CMakeFiles/kqueue.dir/gio/kqueue/kqueue-sub.c.o CMakeFiles/kqueue.dir/gio/kqueue/kqueue-thread.c.o CMakeFiles/kqueue.dir/gio/kqueue/kqueue-utils.c.o  -Wl,-rpath,/Users/angel/code/vcpkg/buildtrees/glib/x64-osx-dbg -framework CoreServices -framework CoreFoundation -framework Foundation libgmodule-2.dylib -framework CoreServices -framework CoreFoundation -framework Foundation && :
FAILED: libkqueue-2.dylib 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -g  -dynamiclib -Wl,-headerpad_max_install_names  -o libkqueue-2.dylib -install_name @rpath/libkqueue-2.dylib CMakeFiles/kqueue.dir/gio/kqueue/dep-list.c.o CMakeFiles/kqueue.dir/gio/kqueue/gkqueuefilemonitor.c.o CMakeFiles/kqueue.dir/gio/kqueue/kqueue-exclusions.c.o CMakeFiles/kqueue.dir/gio/kqueue/kqueue-helper.c.o CMakeFiles/kqueue.dir/gio/kqueue/kqueue-missing.c.o CMakeFiles/kqueue.dir/gio/kqueue/kqueue-sub.c.o CMakeFiles/kqueue.dir/gio/kqueue/kqueue-thread.c.o CMakeFiles/kqueue.dir/gio/kqueue/kqueue-utils.c.o  -Wl,-rpath,/Users/angel/code/vcpkg/buildtrees/glib/x64-osx-dbg -framework CoreServices -framework CoreFoundation -framework Foundation libgmodule-2.dylib -framework CoreServices -framework CoreFoundation -framework Foundation && :
Undefined symbols for architecture x86_64:
  "__g_poll_file_monitor_new", referenced from:
      _g_kqueue_file_monitor_start in gkqueuefilemonitor.c.o
  "_g_assertion_message_expr", referenced from:
      _g_kqueue_file_monitor_start in gkqueuefilemonitor.c.o
      __fallback_callback in gkqueuefilemonitor.c.o
      __kh_dir_diff in kqueue-helper.c.o
      __kh_start_watching in kqueue-helper.c.o
      __kh_add_sub in kqueue-helper.c.o
      __kh_cancel_sub in kqueue-helper.c.o
      __kh_file_appeared_cb in kqueue-helper.c.o
      ...
  "_g_direct_equal", referenced from:
      __kh_startup_impl in kqueue-helper.c.o
  "_g_direct_hash", referenced from:
      __kh_startup_impl in kqueue-helper.c.o
  "_g_file_monitor_cancel", referenced from:
      _g_kqueue_file_monitor_cancel in gkqueuefilemonitor.c.o
  "_g_file_monitor_emit_event", referenced from:
      __fallback_callback in gkqueuefilemonitor.c.o
      __kh_file_appeared_cb in kqueue-helper.c.o
  "_g_file_monitor_get_type", referenced from:
      _g_kqueue_file_monitor_class_init in gkqueuefilemonitor.c.o
      _g_kqueue_file_monitor_cancel in gkqueuefilemonitor.c.o
      __fallback_callback in gkqueuefilemonitor.c.o
      __kh_file_appeared_cb in kqueue-helper.c.o
  "_g_file_monitor_source_handle_event", referenced from:
      _handle_created in kqueue-helper.c.o
      _handle_deleted in kqueue-helper.c.o
      _handle_moved in kqueue-helper.c.o
      _handle_overwritten in kqueue-helper.c.o
      _process_kqueue_notifications in kqueue-helper.c.o
  "_g_file_new_for_path", referenced from:
      _g_kqueue_file_monitor_start in gkqueuefilemonitor.c.o
      __kh_file_appeared_cb in kqueue-helper.c.o
  "_g_file_test", referenced from:
      __kh_file_appeared_cb in kqueue-helper.c.o
  "_g_free", referenced from:
      __kh_sub_free in kqueue-sub.c.o
      _kevents_free in kqueue-utils.c.o
  "_g_get_monotonic_time", referenced from:
      _handle_created in kqueue-helper.c.o
      _handle_deleted in kqueue-helper.c.o
      _handle_moved in kqueue-helper.c.o
      _handle_overwritten in kqueue-helper.c.o
      _process_kqueue_notifications in kqueue-helper.c.o
  "_g_hash_table_insert", referenced from:
      __kh_start_watching in kqueue-helper.c.o
  "_g_hash_table_lookup", referenced from:
      _process_kqueue_notifications in kqueue-helper.c.o
  "_g_hash_table_new", referenced from:
      __kh_startup_impl in kqueue-helper.c.o
  "_g_hash_table_remove", referenced from:
      __kh_cancel_sub in kqueue-helper.c.o
  "_g_intern_static_string", referenced from:
      _g_kqueue_file_monitor_get_type in gkqueuefilemonitor.c.o
  "_g_io_add_watch", referenced from:
      __kh_startup_impl in kqueue-helper.c.o
  "_g_io_channel_unix_new", referenced from:
      __kh_startup_impl in kqueue-helper.c.o
  "_g_io_extension_point_implement", referenced from:
      _g_kqueue_file_monitor_get_type in gkqueuefilemonitor.c.o
  "_g_local_file_monitor_get_type", referenced from:
      _g_kqueue_file_monitor_get_type in gkqueuefilemonitor.c.o
      _g_kqueue_file_monitor_class_init in gkqueuefilemonitor.c.o
      __fallback_callback in gkqueuefilemonitor.c.o
  "_g_log", referenced from:
      _dl_create in dep-list.c.o
      _dl_shallow_copy in dep-list.c.o
      _dl_listing in dep-list.c.o
      __kh_startup_impl in kqueue-helper.c.o
      __kh_start_watching in kqueue-helper.c.o
      __kh_cancel_sub in kqueue-helper.c.o
      _process_kqueue_notifications in kqueue-helper.c.o
      ...
  "_g_malloc0_n", referenced from:
      _kevents_init_sz in kqueue-utils.c.o
  "_g_mutex_lock", referenced from:
      __kh_start_watching in kqueue-helper.c.o
      __kh_cancel_sub in kqueue-helper.c.o
      _process_kqueue_notifications in kqueue-helper.c.o
      __km_add_missing in kqueue-missing.c.o
      _km_scan_missing in kqueue-missing.c.o
      __km_remove in kqueue-missing.c.o
      __kqueue_thread_collect_fds in kqueue-thread.c.o
      ...
  "_g_mutex_unlock", referenced from:
      __kh_start_watching in kqueue-helper.c.o
      __kh_cancel_sub in kqueue-helper.c.o
      _process_kqueue_notifications in kqueue-helper.c.o
      __km_add_missing in kqueue-missing.c.o
      _km_scan_missing in kqueue-missing.c.o
      __km_remove in kqueue-missing.c.o
      __kqueue_thread_collect_fds in kqueue-thread.c.o
      ...
  "_g_object_unref", referenced from:
      _g_kqueue_file_monitor_finalize in gkqueuefilemonitor.c.o
      __kh_file_appeared_cb in kqueue-helper.c.o
  "_g_once_impl", referenced from:
      __kh_startup in kqueue-helper.c.o
  "_g_once_init_enter", referenced from:
      _g_kqueue_file_monitor_get_type in gkqueuefilemonitor.c.o
  "_g_once_init_leave", referenced from:
      _g_kqueue_file_monitor_get_type in gkqueuefilemonitor.c.o
  "_g_queue_get_length", referenced from:
      __kqueue_thread_collect_fds in kqueue-thread.c.o
  "_g_queue_pop_head", referenced from:
      __kqueue_thread_collect_fds in kqueue-thread.c.o
  "_g_queue_push_tail", referenced from:
      __kqueue_thread_push_fd in kqueue-thread.c.o
  "_g_realloc_n", referenced from:
      _kevents_extend_sz in kqueue-utils.c.o
      _kevents_reduce in kqueue-utils.c.o
  "_g_signal_connect_data", referenced from:
      _g_kqueue_file_monitor_start in gkqueuefilemonitor.c.o
  "_g_signal_handlers_disconnect_matched", referenced from:
      _g_kqueue_file_monitor_cancel in gkqueuefilemonitor.c.o
  "_g_slice_alloc", referenced from:
      __kh_sub_new in kqueue-sub.c.o
  "_g_slice_free1", referenced from:
      __kh_sub_free in kqueue-sub.c.o
  "_g_slist_find", referenced from:
      __km_add_missing in kqueue-missing.c.o
      __kqueue_thread_cleanup_fds in kqueue-thread.c.o
  "_g_slist_free", referenced from:
      _km_scan_missing in kqueue-missing.c.o
      __kqueue_thread_cleanup_fds in kqueue-thread.c.o
  "_g_slist_prepend", referenced from:
      __km_add_missing in kqueue-missing.c.o
      _km_scan_missing in kqueue-missing.c.o
      __kqueue_thread_remove_fd in kqueue-thread.c.o
  "_g_slist_remove", referenced from:
      __km_remove in kqueue-missing.c.o
  "_g_slist_remove_link", referenced from:
      _km_scan_missing in kqueue-missing.c.o
  "_g_strdup", referenced from:
      __kh_sub_new in kqueue-sub.c.o
  "_g_timeout_add_seconds", referenced from:
      __km_add_missing in kqueue-missing.c.o
  "_g_type_check_class_cast", referenced from:
      _g_kqueue_file_monitor_class_init in gkqueuefilemonitor.c.o
      _g_kqueue_file_monitor_finalize in gkqueuefilemonitor.c.o
      _g_kqueue_file_monitor_cancel in gkqueuefilemonitor.c.o
  "_g_type_check_instance_cast", referenced from:
      _g_kqueue_file_monitor_finalize in gkqueuefilemonitor.c.o
      _g_kqueue_file_monitor_cancel in gkqueuefilemonitor.c.o
      _g_kqueue_file_monitor_start in gkqueuefilemonitor.c.o
      __fallback_callback in gkqueuefilemonitor.c.o
      __kh_file_appeared_cb in kqueue-helper.c.o
  "_g_type_class_adjust_private_offset", referenced from:
      _g_kqueue_file_monitor_class_intern_init in gkqueuefilemonitor.c.o
  "_g_type_class_peek_parent", referenced from:
      _g_kqueue_file_monitor_class_intern_init in gkqueuefilemonitor.c.o
  "_g_type_register_static_simple", referenced from:
      _g_kqueue_file_monitor_get_type in gkqueuefilemonitor.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[345/347] : && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -g  -dynamiclib -Wl,-headerpad_max_install_names  -o libgobject-2.dylib -install_name @rpath/libgobject-2.dylib CMakeFiles/gobject.dir/gobject/gatomicarray.c.o CMakeFiles/gobject.dir/gobject/gbinding.c.o CMakeFiles/gobject.dir/gobject/gboxed.c.o CMakeFiles/gobject.dir/gobject/gclosure.c.o CMakeFiles/gobject.dir/gobject/genums.c.o CMakeFiles/gobject.dir/gobject/gmarshal.c.o CMakeFiles/gobject.dir/gobject/gobject.c.o CMakeFiles/gobject.dir/gobject/gparam.c.o CMakeFiles/gobject.dir/gobject/gparamspecs.c.o CMakeFiles/gobject.dir/gobject/gsignal.c.o CMakeFiles/gobject.dir/gobject/gsourceclosure.c.o CMakeFiles/gobject.dir/gobject/gtype.c.o CMakeFiles/gobject.dir/gobject/gtypemodule.c.o CMakeFiles/gobject.dir/gobject/gtypeplugin.c.o CMakeFiles/gobject.dir/gobject/gvalue.c.o CMakeFiles/gobject.dir/gobject/gvaluearray.c.o CMakeFiles/gobject.dir/gobject/gvaluetransform.c.o CMakeFiles/gobject.dir/gobject/gvaluetypes.c.o  -Wl,-rpath,/Users/angel/code/vcpkg/buildtrees/glib/x64-osx-dbg -Wl,-rpath,/Users/angel/code/vcpkg/installed/x64-osx/debug/lib -framework CoreServices -framework CoreFoundation -framework Foundation libgthread-2.dylib libglib-2.dylib /Users/angel/code/vcpkg/installed/x64-osx/debug/lib/libffi.dylib -framework CoreServices -framework CoreFoundation -framework Foundation && :
ninja: build stopped: subcommand failed.
```

And here is when I got stuck, because it can't link with its own libraries :(
Any suggestion?

Thanks!

**Comment by venabled** [comment]
I can get it to build (static) but then downstream libs throw linker errors for a lot of the libintl and getText symbols as above: 

```
[25/58] : && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -std=gnu99 -Wno-format-zero-length -g  -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 1.0.0 -current_version 1.4.0 -o lcm/liblcm.1.4.0.dylib -install_name @rpath/liblcm.1.dylib lcm/CMakeFiles/lcm.dir/eventlog.c.o lcm/CMakeFiles/lcm.dir/lcm.c.o lcm/CMakeFiles/lcm.dir/lcm_file.c.o lcm/CMakeFiles/lcm.dir/lcm_memq.c.o lcm/CMakeFiles/lcm.dir/lcm_mpudpm.c.o lcm/CMakeFiles/lcm.dir/lcm_tcpq.c.o lcm/CMakeFiles/lcm.dir/lcm_udpm.c.o lcm/CMakeFiles/lcm.dir/ringbuffer.c.o lcm/CMakeFiles/lcm.dir/udpm_util.c.o lcm/CMakeFiles/lcm.dir/lcmtypes/channel_port_map_update_t.c.o lcm/CMakeFiles/lcm.dir/lcmtypes/channel_to_port_t.c.o  /Users/venabled/source/vcpkg/installed/x64-osx/debug/lib/libglib-2.0.a && :
FAILED: lcm/liblcm.1.4.0.dylib 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -std=gnu99 -Wno-format-zero-length -g  -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 1.0.0 -current_version 1.4.0 -o lcm/liblcm.1.4.0.dylib -install_name @rpath/liblcm.1.dylib lcm/CMakeFiles/lcm.dir/eventlog.c.o lcm/CMakeFiles/lcm.dir/lcm.c.o lcm/CMakeFiles/lcm.dir/lcm_file.c.o lcm/CMakeFiles/lcm.dir/lcm_memq.c.o lcm/CMakeFiles/lcm.dir/lcm_mpudpm.c.o lcm/CMakeFiles/lcm.dir/lcm_tcpq.c.o lcm/CMakeFiles/lcm.dir/lcm_udpm.c.o lcm/CMakeFiles/lcm.dir/ringbuffer.c.o lcm/CMakeFiles/lcm.dir/udpm_util.c.o lcm/CMakeFiles/lcm.dir/lcmtypes/channel_port_map_update_t.c.o lcm/CMakeFiles/lcm.dir/lcmtypes/channel_to_port_t.c.o  /Users/venabled/source/vcpkg/installed/x64-osx/debug/lib/libglib-2.0.a && :
Undefined symbols for architecture x86_64:
  "_CFRelease", referenced from:
      _find_folder in libglib-2.0.a(gutils.c.o)
  "_CFStringGetCString", referenced from:
      _find_folder in libglib-2.0.a(gutils.c.o)
  "_CFStringGetCStringPtr", referenced from:
      _find_folder in libglib-2.0.a(gutils.c.o)
  "_CFStringGetLength", referenced from:
      _find_folder in libglib-2.0.a(gutils.c.o)
  "_CFURLCopyFileSystemPath", referenced from:
      _find_folder in libglib-2.0.a(gutils.c.o)
  "_CFURLCreateFromFSRef", referenced from:
      _find_folder in libglib-2.0.a(gutils.c.o)
  "_FSFindFolder", referenced from:
      _find_folder in libglib-2.0.a(gutils.c.o)
  "_iconv", referenced from:
      _g_iconv in libglib-2.0.a(gconvert.c.o)
     (maybe you meant: _g_convert_with_iconv, _g_iconv_close , _g_iconv , _g_iconv_open )
  "_iconv_close", referenced from:
      _g_iconv_close in libglib-2.0.a(gconvert.c.o)
     (maybe you meant: _g_iconv_close)
  "_iconv_open", referenced from:
      _try_conversion in libglib-2.0.a(gconvert.c.o)
     (maybe you meant: _g_iconv_open)
  "_kCFAllocatorSystemDefault", referenced from:
      _find_folder in libglib-2.0.a(gutils.c.o)
  "_libintl_bind_textdomain_codeset", referenced from:
      _ensure_gettext_initialized in libglib-2.0.a(ggettext.c.o)
  "_libintl_bindtextdomain", referenced from:
      _ensure_gettext_initialized in libglib-2.0.a(ggettext.c.o)
  "_libintl_dcgettext", referenced from:
      _g_dcgettext in libglib-2.0.a(ggettext.c.o)
  "_libintl_dgettext", referenced from:
      _g_dgettext in libglib-2.0.a(ggettext.c.o)
  "_libintl_dngettext", referenced from:
      _g_dngettext in libglib-2.0.a(ggettext.c.o)
  "_libintl_gettext", referenced from:
      __g_dgettext_should_translate in libglib-2.0.a(ggettext.c.o)
  "_libintl_newlocale", referenced from:
      _get_C_locale in libglib-2.0.a(gstrfuncs.c.o)
  "_libintl_setlocale", referenced from:
      __g_dgettext_should_translate in libglib-2.0.a(ggettext.c.o)
  "_libintl_textdomain", referenced from:
      __g_dgettext_should_translate in libglib-2.0.a(ggettext.c.o)
  "_pcre_compile2", referenced from:
      _regex_compile in libglib-2.0.a(gregex.c.o)
  "_pcre_config", referenced from:
      _g_regex_new in libglib-2.0.a(gregex.c.o)
  "_pcre_dfa_exec", referenced from:
      _g_regex_match_all_full in libglib-2.0.a(gregex.c.o)
  "_pcre_exec", referenced from:
      _g_match_info_next in libglib-2.0.a(gregex.c.o)
  "_pcre_free", referenced from:
      _g_regex_unref in libglib-2.0.a(gregex.c.o)
      _g_regex_match_all_full in libglib-2.0.a(gregex.c.o)
  "_pcre_fullinfo", referenced from:
      _regex_compile in libglib-2.0.a(gregex.c.o)
      _g_regex_get_max_backref in libglib-2.0.a(gregex.c.o)
      _g_regex_get_capture_count in libglib-2.0.a(gregex.c.o)
      _g_regex_get_has_cr_or_lf in libglib-2.0.a(gregex.c.o)
      _g_regex_get_max_lookbehind in libglib-2.0.a(gregex.c.o)
      _match_info_new in libglib-2.0.a(gregex.c.o)
  "_pcre_get_stringnumber", referenced from:
      _get_matched_substring_number in libglib-2.0.a(gregex.c.o)
      _g_regex_get_string_number in libglib-2.0.a(gregex.c.o)
  "_pcre_get_stringtable_entries", referenced from:
      _get_matched_substring_number in libglib-2.0.a(gregex.c.o)
  "_pcre_study", referenced from:
      _g_regex_new in libglib-2.0.a(gregex.c.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by gourdi** [comment]
I have the exact same issue. Did you manage to fix your link issue?

**Comment by venabled** [comment]
Actually, I just picked this back up and now on Catalina I can't even get thru `configure` since with the current XCode 11, the build isn't picking up the location of the c/c++ library headers. 

Something like this: 

```
configure:4302: checking whether we are cross compiling
configure:4310: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -o conftest -fPIC -g -I/Users/venabled/source/vcpkg/installed/x64-osx/include -I/Users/venabled/source/vcpkg/installed/x64-osx/include -L/Users/venabled/source/vcpkg/installed/x64-osx/debug/lib conftest.c  >&5
conftest.c:14:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
configure:4314: $? = 1
configure:4321: ./conftest
/Users/venabled/source/vcpkg/buildtrees/glib/src/2.52.3-34a15219ec/configure: line 4323: ./conftest: No such file or directory
configure:4325: $? = 127
```

- **OS:** macOS Catalina (10.15.4)
- **XCode:** 11.4.1 (Build version 11E503a)

**Comment by gourdi** [comment]
Ah, then maybe you should check https://github.com/microsoft/vcpkg/issues/9012

**Comment by angelmixu** [comment]
Hey people, I'm trying to migrate glib port to use the meson build that glib migrated to.
It's on this PR: https://github.com/microsoft/vcpkg/pull/9799

**Comment by NancyLi1013** [comment]
Hi all,
Thanks for joining the discussion for this issue.
This temporary solution is like this:

```
set(ENV{SDKROOT} ${CMAKE_OSX_SYSROOT})

just before

execute_process(
         COMMAND "${CMAKE_SOURCE_DIR}/configure"
```
It's duplicated to #9012. So let's track this issue there.
