### PR TITLE
[qt5]Fix static build failure in windows

### PR DESCRIPTION
**Pull request by JackBoosY**
1. The option `staticlib` is no longer supported in static builds, replacing it with `static`.
2. Now we don't need to use `qmake_all` to build qt5 and other modules in windows-static, it seems to **break** the disabled parameters during the build. See [documentation](https://wiki.qt.io/Building_Qt_Documentation).

Fix the failure of qt5 module build in windows-static (caused by #5293):

- [x] qt5-base
- [x] qt5-3d
- [x] qt5-activeqt : only support Windows
- [x] qt5-charts
- [x] qt5-connectivity
- [x] qt5-datavis3d
- [x] qt5-declarative
- [x] qt5-gamepad
- [x] qt5-graphicaleffects
- [x] qt5-imageformats
- [x] qt5-location
- [x] qt5-macextras : only support OSX
- [x] qt5-modularscripts
- [x] qt5-mqtt
- [x] qt5-multimedia
- [x] qt5-networkauth
- [x] qt5-purchasing
- [x] qt5-quickcontrols
- [x] qt5-quickcontrols2
- [x] qt5-remoteobjects
- [x] qt5-script
- [x] qt5-scxml
- [x] qt5-sensors
- [x] qt5-serialport
- [x] qt5-speech
- [x] qt5-svg
- [x] qt5-tools
- [x] qt5-virtualkeyboard
- [x] qt5-webchannel
- [x] qt5-websockets
- [x] qt5-webview
- [x] qt5-winextras : only support Windows
- [x] qt5-xmlpatterns

Related: #4560 #6240 #5881 #731 #513.

NOTE: Need to wait for PR #7230 to merge.

### CODE REVIEW

**Comment by JackBoosY** [comment]
1. There will be some errors when using vcpkg freetype:
```
   Creating library ..\..\bin\qml.lib and object ..\..\bin\qml.exp
freetyped.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompressInit referenced in function ft_bzip2_file_init
freetyped.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompress referenced in function ft_bzip2_file_fill_output
freetyped.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompressEnd referenced in function ft_bzip2_file_done
..\..\bin\qml.exe : fatal error LNK1120: 3 unresolved externals
   Creating library ..\..\bin\qmleasing.lib and object ..\..\bin\qmleasing.exp
freetyped.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompressInit referenced in function ft_bzip2_file_init
freetyped.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompress referenced in function ft_bzip2_file_fill_output
freetyped.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompressEnd referenced in function ft_bzip2_file_done
..\..\bin\qmleasing.exe : fatal error LNK1120: 3 unresolved externals
```
I am temporarily unable to solve these problems, so temporarily use qt5 built-in freetype.

2. We need to use **qtmain.lib**/**qtmaind.lib** when building qt5-declarative, but its path is **wrong**. Although this path was fixed in _qt5-base/fixcmake.py_, bug it obviously didn't work.
So I temporarily commented on these codes to delete this library, waiting for the issue to be fixed later.

**Comment by heydojo** [comment]
> There will be some errors when using vcpkg freetype:

The windows port doesn't need to compile against freetype. https://doc.qt.io/archives/qt-5.11/qtgui-attribution-freetype.html

> Configure with -no-freetype, or -system-freetype to avoid.

```
Creating library ..\..\bin\qml.lib and object ..\..\bin\qml.exp
freetyped.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompressInit referenced in function ft_bzip2_file_init
freetyped.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompress referenced in function ft_bzip2_file_fill_output
freetyped.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompressEnd referenced in function ft_bzip2_file_done
..\..\bin\qml.exe : fatal error LNK1120: 3 unresolved externals
   Creating library ..\..\bin\qmleasing.lib and object ..\..\bin\qmleasing.exp
freetyped.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompressInit referenced in function ft_bzip2_file_init
freetyped.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompress referenced in function ft_bzip2_file_fill_output
freetyped.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompressEnd referenced in function ft_bzip2_file_done
..\..\bin\qmleasing.exe : fatal error LNK1120: 3 unresolved externals
```

https://github.com/microsoft/vcpkg/blob/master/ports/qt5-base/portfile.cmake#L41

The back slashes in your code snippet give it away that it was compiled on Windows. And I can see that `-system-freetype` exists inside of the configure step of the port file.

Does this then mean that there needs to be a conditional for Windows which uses `-no-freetype` instead of `-system-freetype` in the configure section of the port file?
The Windows code really should not be compiled against freetype.

**Comment by JackBoosY** [comment]
Since qt5-linux has been fixed, create a new PR #7313 to solve this issue.
