### ISSUE TITLE
gettext-0.19 fails to build

### ISSUE THREAD

**Issue by rspeir** [Microsoft/vcpkg#2961]
I'm trying to get cairo installed on my machine, but one of its prerequisites, gettext, fails to build. The build fails in both x86 and x64 mode. 

Relevant text from the log files:
c:\users\n1kt0\documents\visual studio 2015\vcpkg\buildtrees\gettext\src\gettext-0.19\gettext-runtime\intl\xsize.h(31): fatal error C1189: #error:  "Please include config.h first."

I checked the source files, and it appears that xsize.c includes config.h before including xsize.h, so I don't know what the problem is unless the _GL_INLINE_HEADER_BEGIN macro it checks for gets undefined somewhere. 

Anyone have any ideas?

**Comment by glachancecmaisonneuve** [comment]
Confirmed. https://ci.appveyor.com/project/glachancecmaisonneuve/vcpkg/build/1.0.3

**Comment by glachancecmaisonneuve** [comment]
Confirmed.  https://ci.appveyor.com/project/glachancecmaisonneuve/vcpkg

**Comment by Forgon2100** [comment]
The problem was introduced with the commit https://github.com/Microsoft/vcpkg/commit/01ba04e9a737a2b68993e196b7980ce56b8fde00 named "[gettext] Improve and simplify port".

**Comment by ras0219-msft** [comment]
Thanks for reporting!

It looks like the macro fixing patch wasn't being applied correctly to new extractions. I've fixed it in master (35387141) -- let me know if this works for you all :)

**Comment by JackBoosY** [comment]
Hi @rspeir , the latest version is fixed. Plz rebuild after update vcpkg.
Thx.
