### ISSUE TITLE
[kddockwidgets] seems to have optional deps

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#38509]
```
DragController.cpp.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) class std::shared_ptr<class spdlog::logger> __cdecl spdlog::get(char const *)" (__imp_?get@spdlog@@YA?AV?$shared_ptr@Vlogger@spdlog@@@std@@PEBD@Z)
  Hint on symbols that are defined and could potentially match:
    "__declspec(dllimport) public: static class QQmlEnginePrivate * __cdecl QQmlEnginePrivate::get(class QQmlEngine *)" (__imp_?get@QQmlEnginePrivate@@SAPEAV1@PEAVQQmlEngine@@@Z)
    "__declspec(dllimport) public: static class QQuickItemPrivate * __cdecl QQuickItemPrivate::get(class QQuickItem *)" (__imp_?get@QQuickItemPrivate@@SAPEAV1@PEAVQQuickItem@@@Z)
    "__declspec(dllimport) public: static class QQuickItemPrivate const * __cdecl QQuickItemPrivate::get(class QQuickItem const *)" (__imp_?get@QQuickItemPrivate@@SAPEBV1@PEBVQQuickItem@@@Z)

bin\kddockwidgets-qt62d.dll : fatal error LNK1120: 1 unresolved externals
```

Seems to lookup `qtdeclarative/qtquick` but is only declaring a dependency on `qtbase`

**Comment by Neumann-A** [comment]
https://github.com/KDAB/KDDockWidgets/blob/eb4304f39c706862fa698dc59122ae95fc58c26c/CMakeLists.txt#L162-L190

Definitely auto detected deps here.

**Comment by Neumann-A** [comment]
Broken by #35882 removing `-DKDDockWidgets_QTQUICK=OFF` and not controlling `KDDockWidgets_FRONTENDS` explicitly (since that seems to be the new way to control it). @MonicaLiu0311 please fix your introduced regression
