### PR TITLE
[cryptopp]: Fix compilation with clang-cl

### PR DESCRIPTION
**Pull request by raphaelthegreat**
**Describe the pull request**

- #### What does your PR fix?
  Fixes compilation on Windows using clang-cl, by performing the following:
  * Add clang-cl 12.0+ to supported configurations
  * Use MSVC path to detect CRYPTOPP_CXX17_UNCAUGHT_EXCEPTIONS

### CODE REVIEW

**Comment by Neumann-A** [comment]
I get:
```
FAILED: CMakeFiles/cryptopp-object.dir/chacha_avx.cpp.obj 
E:\vcpkg_cache\downloads\tools\clang\clang-14.0.6\bin\clang-cl.exe  /nologo -TP -D_WIN32_WINNT=0x0A00  /nologo /EHsc /GR /DWIN32 /D_WIN64 /D_WIN32_WINNT=0x0A00 /DWINVER=0x0A00 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_DEPRECATE /D_ATL_SECURE_NO_DEPRECATE /D_SCL_SECURE_NO_WARNINGS /D_CRT_INTERNAL_NONSTDC_NAMES /D_CRT_DECLARE_NONSTDC_NAMES /D_FORCENAMELESSUNION -mcrc32 -msse4.2 /clang:-fasm -fmacro-backtrace-limit=0 /utf-8 /WX- /Od /Ob0 /GS /RTC1 /FC  /MDd /Z7 /Brepro /D_DEBUG /FC  /FIwinapifamily.h /showIncludes /FoCMakeFiles\cryptopp-object.dir\chacha_avx.cpp.obj /FdCMakeFiles\cryptopp-object.dir\ -c -- E:\vcpkg_folders\llvm_test\buildtrees\cryptopp\src\TOPP_8_6_0-ea3517667b\chacha_avx.cpp
E:\vcpkg_folders\llvm_test\buildtrees\cryptopp\src\TOPP_8_6_0-ea3517667b\chacha_avx.cpp(63,8): error: unknown type name '__m256i'
inline __m256i RotateLeft(const __m256i val)
       ^
```
because the build seems not to be adding the required `-mavx2` flag

**Comment by GPUCode** [comment]
> 

I tested the build with clang-cl included in the VS 2022 installer and it compiled successfully. I'll try the standalone as well, it probably can't detect the platform correctly

**Comment by GPUCode** [comment]
So I performed some tests and the problem seems to be that while CMake enables the MSVC flag with clang-cl, CMAKE_CXX_COMPILER_ID remains equal to "Clang" which breaks the SIMD flag configuration.

**Comment by GPUCode** [comment]
Tested build using the latest clang-cl 14.0 using the x64-windows-llvm triplet from this repository: https://github.com/Neumann-A/my-vcpkg-triplets
The only change that was needed was to replace /clang:-fopenmp-simd with /openmp here https://github.com/Neumann-A/my-vcpkg-triplets/blob/5c1f246cf87c2bc274aac77ee3440eaeb8a253c0/x64-windows-llvm.toolchain.common.cmake#L49

**Comment by Neumann-A** [comment]
Merged this into #25897. Compiles fine now.

**Review by FrankXie05 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Please submit this patch upstream to https://github.com/weidai11/cryptopp

Thanks!
