### PR TITLE
[pcl] update to version 1.14.0

### PR DESCRIPTION
**Pull request by mvieth**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~ no change
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~ no change
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

Updated `add-gcc-version-check.patch` and `fit-numeric-literals-flag.patch` to work with PCL 1.14.0.
Modified `fix-clang-cl.patch` because some of the changes are already included in PCL 1.14.0.
Removed `devendor-zlib.patch` because it is included in PCL 1.14.0 ( https://github.com/PointCloudLibrary/pcl/pull/5684 )
Deleted further patches which are unused since vcpkg update to PCL 1.13.1.

### CODE REVIEW

**Comment by Adela0814** [comment]
@mvieth  I encountered the following errors while testing all features.
Repro steps:
`.\vcpkg.exe install pcl[*]:x64-windows`
Error message:
```
        Line 19194: E:\5\vcpkg\buildtrees\pcl\src\pcl-1.14.0-55b936601d.clean\gpu\kinfu\src\cuda\marching_cubes.cu(61): note: see reference to function template instantiation 'cudaError_t cudaBindTexture<int,1,cudaReadModeElementType>(size_t *,const texture<int,1,cudaReadModeElementType> &,const void *,const cudaChannelFormatDesc &,size_t)' being compiled
	Line 19196: E:\5\vcpkg\buildtrees\pcl\src\pcl-1.14.0-55b936601d.clean\gpu\kinfu\src\cuda\marching_cubes.cu(68): note: see reference to function template instantiation 'cudaError_t cudaUnbindTexture<int,1,cudaReadModeElementType>(const texture<int,1,cudaReadModeElementType> &)' being compiled
	Line 19254: E:\5\vcpkg\buildtrees\pcl\src\pcl-1.14.0-55b936601d.clean\gpu\segmentation\src\extract_clusters.cpp(50): error C2375: 'pcl::detail::economical_download': redefinition; different linkage
	Line 19533: E:\5\vcpkg\buildtrees\pcl\src\pcl-1.14.0-55b936601d.clean\gpu\kinfu_large_scale\src\cuda\marching_cubes.cu(62): note: see reference to function template instantiation 'cudaError_t cudaBindTexture<int,1,cudaReadModeElementType>(size_t *,const texture<int,1,cudaReadModeElementType> &,const void *,const cudaChannelFormatDesc &,size_t)' being compiled
	Line 19536: E:\5\vcpkg\buildtrees\pcl\src\pcl-1.14.0-55b936601d.clean\gpu\kinfu_large_scale\src\cuda\marching_cubes.cu(69): note: see reference to function template instantiation 'cudaError_t cudaUnbindTexture<int,1,cudaReadModeElementType>(const texture<int,1,cudaReadModeElementType> &)' being compiled

```

**Comment by mvieth** [comment]
@Adela0814 Thank you, I only tested with Linux so far, where everything passed. Could you tell me which CUDA version you used?

**Comment by Adela0814** [comment]
> @Adela0814 Thank you, I only tested with Linux so far, where everything passed. Could you tell me which CUDA version you used?

11.6.

**Comment by mvieth** [comment]
@Adela0814 With the new patch I added, `.\vcpkg.exe install pcl[*]:x64-windows` installs successfully

**Review by Adela0814 — APPROVED** [review]
