### ISSUE TITLE
[pcl] Qhull is disabled in pcl_config.h, causes pcl::ConvexHull to not compile or (with workaround) to link

### ISSUE THREAD

**Issue by MK-3PP** [microsoft/vcpkg#17662]
**Host Environment**
- OS: Windows 10 Pro 1909
- Compiler: v142 (Visual Studio 2019)

**To Reproduce**

1. `.\vcpkg install pcl:x64-windows`
2. Examine `.\vcpkg\installed\x64-windows\include\pcl\pcl_config.h` for `/* #undef HAVE_QHULL */`. Expected: `#define HAVE_QHULL`

**Additional context**
Using yesterday's Revision 95836f4883ffb481b7dd5f89569bc6ef55c31a7e of Vcpkg the problem occurs. Two weeks ago it worked fine with 807a7987612bbd702be9d9b8069124be62aff857. In the meantime issue https://github.com/microsoft/vcpkg/issues/13881, that addressed a related problem, was resolved and PR https://github.com/microsoft/vcpkg/pull/17437 was merged to master. Maybe a new bug was introduced?

`.\vcpkg\installed\x64-windows\bin\pcl_surface.dll` does not export any `pcl::ConvexHull` symbols or anything with `hull`.

Creating a test project with the environment set to the `.\vcpkg\installed\x64-windows\include` and `.\vcpkg\installed\x64-windows\lib` directories, linking all *.lib files in the latter.
Naively using pcl::ConvexHull gives compiler errors:

```
// ConvexHull Test.cpp

#include "pcl/point_types.h"
#include "pcl/point_cloud.h"
#include "pcl/surface/convex_hull.h"

int main() {
    pcl::PointCloud<pcl::PointXYZ> pc;
    pcl::ConvexHull<pcl::PointXYZ> hull;

    hull.reconstruct(pc);
}
```
Build log:
```
1>C:\ConvexHull Test\ConvexHull Test.cpp(12,10): error C2039: 'ConvexHull': is not a member of 'pcl'
1>C:\ConvexHull Test\ConvexHull Test.cpp(12,20): error C2065: 'ConvexHull': undeclared identifier
1>C:\ConvexHull Test\ConvexHull Test.cpp(12,26): error C2275: 'pcl::PointXYZ': illegal use of this type as an expression
1>C:\ConvexHull Test\ConvexHull Test.cpp(12,36): error C2065: 'hull': undeclared identifier
1>C:\ConvexHull Test\ConvexHull Test.cpp(14,5): error C2065: 'hull': undeclared identifier
```

**Workaround** (kinda)
Manually defining `HAVE_QHULL` before including pcl_config.h (happens in any PCL header), compilation succeeds, but linking fails:
```
// ConvexHull Test.cpp

#define HAVE_QHULL

#include "pcl/point_types.h"
#include "pcl/point_cloud.h"
#include "pcl/surface/convex_hull.h"

int main() {
    pcl::PointCloud<pcl::PointXYZ> pc;
    pcl::ConvexHull<pcl::PointXYZ> hull;

    hull.reconstruct(pc);
}
```
Build log:
```
1>ConvexHull Test.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl pcl::ConvexHull<struct pcl::PointXYZ>::performReconstruction(struct pcl::PolygonMesh &)" (?performReconstruction@?$ConvexHull@UPointXYZ@pcl@@@pcl@@MEAAXAEAUPolygonMesh@2@@Z)
1>ConvexHull Test.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl pcl::ConvexHull<struct pcl::PointXYZ>::performReconstruction(class std::vector<struct pcl::Vertices,class std::allocator<struct pcl::Vertices> > &)" (?performReconstruction@?$ConvexHull@UPointXYZ@pcl@@@pcl@@MEAAXAEAV?$vector@UVertices@pcl@@V?$allocator@UVertices@pcl@@@std@@@std@@@Z)
1>ConvexHull Test.obj : error LNK2001: unresolved external symbol "public: void __cdecl pcl::ConvexHull<struct pcl::PointXYZ>::reconstruct(class pcl::PointCloud<struct pcl::PointXYZ> &)" (?reconstruct@?$ConvexHull@UPointXYZ@pcl@@@pcl@@QEAAXAEAV?$PointCloud@UPointXYZ@pcl@@@2@@Z)
1>C:\ConvexHull Test\x64\Release\ConvexHull Test.exe : fatal error LNK1120: 3 unresolved externals
```

**Comment by JackBoosY** [comment]
Broken by PR https://github.com/microsoft/vcpkg/pull/17437.

**Comment by JackBoosY** [comment]
Upstream PR https://github.com/PointCloudLibrary/pcl/pull/4540.
Waiting for upstream fix this.

**Comment by MK-3PP** [comment]
Update:
After getting inconsistent results i kept on aimlessly testing various combinations of Vcpkg version and build configuration. Turns out, it also depends on whether the build emits static or dynamic libraries. Static Qhull seems to behave differently than dynamic Qhull. Following this text I will provide an overview of two Vcpkg revisions, each using custom triplets to build once static and once dynamic libraries. As a measure for success i take the HAVE_XXX compiler flags in pcl_config.h and the presence of the surface/convex_hull.h header.

**Vcpkg https://github.com/microsoft/vcpkg/commit/807a7987612bbd702be9d9b8069124be62aff857**
> **x64-windows-v142**
> pcl_config.h:
> // #undef HAVE_QHULL
> #define HAVE_QHULL_2011 1
> 
> surface/convex_hull.h:
> **not** present

> **x64-windows-v142-static**
> pcl_config.h:
> #define HAVE_QHULL 1
> #define HAVE_QHULL_2011 1
> 
> surface/convex_hull.h:
> present

**Vcpkg https://github.com/microsoft/vcpkg/commit/95836f4883ffb481b7dd5f89569bc6ef55c31a7e**
> **x64-windows-v142**
> pcl_config.h:
> // #undef HAVE_QHULL
> // #undef HAVE_QHULL_2011
> 
> surface/convex_hull.h:
> present

> **x64-windows-v142-static**
> pcl_config.h:
> // #undef HAVE_QHULL
> // #undef HAVE_QHULL_2011
> 
> surface/convex_hull.h:
> present


There are many more points of data, e.g. other present / non-present headers, and lib / dll files or differing build output, but since I am not exactly knowing what to look out for, I will leave it at those examples.

Build output and logs seem inconsistent*, depending on the Vcpkg root directory. So I do not provide it until explicitly asked for it - I would have to rerun 3 hrs of buils under identical conditions.

*) (From memory)
* Differing warning messages when Qhull gets built.
* Command line Freezes up to 30 minutes, then build aborts before PCL.
* Command line Freezes for over 15 minutes -> continues as if nothing happened after user input of Strg+C, and successfully builds PCL.

**Comment by JackBoosY** [comment]
The problem with pcl in vcpkg is that when deleting `FindQhull.cmake`, `set(HAVE_QHULL_2011 ON)` and `set(HAVE_QHULL ON)` are not added, and the macro `qh_dllimport` is not added, and I get a link error after finishing these:
LNK2001: couldn't find symbol `__imp__qh_qh`.

**Comment by WangZP10969** [comment]
> Upstream PR [PointCloudLibrary/pcl#4540](https://github.com/PointCloudLibrary/pcl/pull/4540).
> Waiting for upstream fix this.

@JackBoosY  The upstream has been merged, maybe there will be new developments here?

**Comment by JackBoosY** [comment]
I think we should wait for the next release, fix this issue by updating pcl.

**Comment by WangZP10969** [comment]
# 18855

**Comment by WangZP10969** [comment]
After testing, this problem still exists in the master branch, but qhull can be used in pcl normally by using the following recovery scheme (the test convex hull calculation function is normal)
https://github.com/microsoft/vcpkg/pull/18855#issuecomment-961480058

**Comment by Yourbee** [comment]
I use the PCL-1.11.1-AllInOne package. When I include <pcl/surface/convex_hull.h>, the compiled program will need vtk'dll, but now the PCL of vcpkg does not have vtk. I don't know if the two are related.

**Comment by JackBoosY** [comment]
@Yourbee Can you please provide the failure logs?

**Comment by yoavmil** [comment]
I'm facing the same problem. Any solution or workaround?

**Comment by JackBoosY** [comment]
> I'm facing the same problem. Any solution or workaround?

Failure logs please.

**Comment by yoavmil** [comment]
At concave_hull.h for example, HAVE_QHULL isn't defined
```
#ifdef HAVE_QHULL
```
Please point me to the logs you're looking for.

**Comment by JackBoosY** [comment]
@yoavmil Can you please provide all logs in directory _VCPKG_ROOT/buildtrees/pcl_?

**Comment by yoavmil** [comment]
[pcl.zip](https://github.com/microsoft/vcpkg/files/8014125/pcl.zip)
here you go. anything else

**Comment by JackBoosY** [comment]
Will try to fix this tomorrow.

**Comment by yoavmil** [comment]
BTW, while you take a look, note that also the visualizer doesn't complie, maybe it's related.
```
include\pcl\visualization\point_cloud_geometry_handlers.h(49,10): fatal error C1083: Cannot open include file: 'vtkSmartPointer.h': No such file or directory (compiling source file ConvertPngToCloud.cpp)
```

**Comment by JackBoosY** [comment]
Confirmed.
In _pcl_config.h_:
```cpp
...
/* #undef HAVE_QHULL */
...
#ifdef DISABLE_QHULL
#undef HAVE_QHULL
#endif
...
```

**Comment by JackBoosY** [comment]
@yoavmil Can you please test PR https://github.com/microsoft/vcpkg/pull/22995?

Thanks.

**Comment by yoavmil** [comment]
Yes! It works. 
Just to be sure, I cloned your fork, installed all the dependecies I needed, and `vcpkg integrate install`, then compiled and it's ok.
It took a few hours though.
