### PR TITLE
Baseline Fixes 2025-09-15

### PR DESCRIPTION
**Pull request by BillyONeal**
x64-osx did not complete within 48 hours: #47358

```console
REGRESSION: sourcemeta-blaze:x64-linux failed with FILE_CONFLICTS. If expected, add sourcemeta-blaze:x64-linux=fail to /vcpkg/scripts/azure-pipelines/../ci.baseline.txt.
REGRESSION: sourcemeta-blaze:x64-uwp failed with FILE_CONFLICTS. If expected, add sourcemeta-blaze:x64-uwp=fail to D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: sourcemeta-blaze:x64-windows failed with FILE_CONFLICTS. If expected, add sourcemeta-blaze:x64-windows=fail to D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: sourcemeta-blaze:x64-windows-release failed with FILE_CONFLICTS. If expected, add sourcemeta-blaze:x64-windows-release=fail to D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: sourcemeta-blaze:x64-windows-static failed with FILE_CONFLICTS. If expected, add sourcemeta-blaze:x64-windows-static=fail to D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: sourcemeta-blaze:x64-windows-static-md failed with FILE_CONFLICTS. If expected, add sourcemeta-blaze:x64-windows-static-md=fail to D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: sourcemeta-blaze:x86-windows failed with FILE_CONFLICTS. If expected, add sourcemeta-blaze:x86-windows=fail to D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt.
```

#47360

```console
PASSING, REMOVE FROM FAIL LIST: libwandio:arm-neon-android (/vcpkg/scripts/azure-pipelines/../ci.baseline.txt).
PASSING, REMOVE FROM FAIL LIST: libwandio:arm64-android (/vcpkg/scripts/azure-pipelines/../ci.baseline.txt).
PASSING, REMOVE FROM FAIL LIST: libwandio:x64-android (/vcpkg/scripts/azure-pipelines/../ci.baseline.txt).
PASSING, REMOVE FROM FAIL LIST: sleef:arm-neon-android (/vcpkg/scripts/azure-pipelines/../ci.baseline.txt).
PASSING, REMOVE FROM FAIL LIST: sleef:arm64-android (/vcpkg/scripts/azure-pipelines/../ci.baseline.txt).
```

:)

```console
PASSING, REMOVE FROM FAIL LIST: libxt:x64-windows (D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt).
PASSING, REMOVE FROM FAIL LIST: libxt:x64-windows-release (D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt).
```

:), but that this port tries to change the compiler to clang is unacceptable. Not sure if it can be fixed.

```console
REGRESSION: saucer:arm64-windows failed with BUILD_FAILED. If expected, add saucer:arm64-windows=fail to D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: saucer:arm64-windows-static-md failed with BUILD_FAILED. If expected, add saucer:arm64-windows-static-md=fail to D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: saucer:x64-windows failed with BUILD_FAILED. If expected, add saucer:x64-windows=fail to D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: saucer:x64-windows-static failed with BUILD_FAILED. If expected, add saucer:x64-windows-static=fail to D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: saucer:x64-windows-static-md failed with BUILD_FAILED. If expected, add saucer:x64-windows-static-md=fail to D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: saucer:x86-windows failed with BUILD_FAILED. If expected, add saucer:x86-windows=fail to D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt.
C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1442~1.344\bin\Hostx64\arm64\cl.exe   /TP -DFMT_SHARED -DNOMINMAX=1 -DSAUCER_WEBKIT_PRIVATE -DSAUCER_WEBVIEW2 -DUNICODE=1 -D_UNICODE=1 -ID:\b\saucer\src\v6.0.1-2f81a02f31.clean\include -ID:\b\saucer\src\v6.0.1-2f81a02f31.clean\private -ID:\b\saucer\src\v6.0.1-2f81a02f31.clean\private\saucer -ID:\b\saucer\src\v6.0.1-2f81a02f31.clean\include\saucer -external:ID:\installed\arm64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /utf-8 /GR /EHsc /MP  /MDd /Z7 /Ob0 /Od /RTC1  -std:c++latest -MDd /wd5030 /utf-8 /Zc:preprocessor /permissive- /Zc:lambda /showIncludes /FoCMakeFiles\saucer.dir\src\glaze.serializer.cpp.obj /FdCMakeFiles\saucer.dir\saucer.pdb /FS -c D:\b\saucer\src\v6.0.1-2f81a02f31.clean\src\glaze.serializer.cpp
D:\b\saucer\src\v6.0.1-2f81a02f31.clean\src\glaze.serializer.cpp : fatal error C1605: compiler limit: object file size cannot exceed 4 GB
ninja: build stopped: subcommand failed.
```

Probably stealth merge conflict between #46911 and #47208 .

```console
REGRESSION: blend2d:arm64-uwp failed with BUILD_FAILED. If expected, add blend2d:arm64-uwp=fail to D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: blend2d:arm64-windows failed with BUILD_FAILED. If expected, add blend2d:arm64-windows=fail to D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: blend2d:arm64-windows-static-md failed with BUILD_FAILED. If expected, add blend2d:arm64-windows-static-md=fail to D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: opencv4:arm64-uwp failed with BUILD_FAILED. If expected, add opencv4:arm64-uwp=fail to D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: vcpkg-ci-opencv:arm64-uwp cascaded, but it is required to pass. (D:\a\_work\1\s\scripts\azure-pipelines/../ci.baseline.txt).
```

This is broken for the same Windows SDK + arm64 + -Zc:arm64-aliased-neon-types- reason as several other ports. Probably broken by #47208 injecting that switch into CMake configs? But naïve build of glaze does not have that switch...

```console
C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1442~1.344\bin\Hostx64\arm64\cl.exe   /TP  -external:ID:\installed\arm64-uwp\include -external:W0 /DWIN32 /D_WINDOWS /D_UNICODE /DUNICODE /DWINAPI_FAMILY=WINAPI_FAMILY_APP /D__WRL_NO_DEFAULT_LIB__ /nologo /Z7 /MP /GS /Gd /Gm- /W3 /WX- /Zc:wchar_t /Zc:inline /Zc:forScope /fp:precise /Oy- /EHsc  /utf-8  /MDd /Od /RTC1  -MDd -MP -GR- -GF -Zc:__cplusplus -Zc:inline -Zc:strictStrings -Zc:threadSafeInit- -W4 -Zc:arm64-aliased-neon-types- -GS /showIncludes /FoCMakeFiles\blend2d.dir\src\blend2d\fontmanager.cpp.obj /FdCMakeFiles\blend2d.dir\ /FS -c D:\b\blend2d\src\fc85f14251-f50748665f.clean\src\blend2d\fontmanager.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\wchar.h(254): error C2664: '__n64 __uint64x1_t_to_n64(uint64x1_t)': cannot convert argument 1 from 'uint16x4_t' to 'uint64x1_t'
C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\wchar.h(254): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.42.34433\include\arm64_neon.h(1957): note: see declaration of '__uint64x1_t_to_n64'
C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\wchar.h(254): note: while trying to match the argument list '(uint16x4_t)'
C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\wchar.h(381): error C2664: '__n64 __uint64x1_t_to_n64(uint64x1_t)': cannot convert argument 1 from 'uint16x4_t' to 'uint64x1_t'
C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\wchar.h(381): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.42.34433\include\arm64_neon.h(1957): note: see declaration of '__uint64x1_t_to_n64'
C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\wchar.h(381): note: while trying to match the argument list '(uint16x4_t)'
[30/124] C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1442~1.344\bin\Hostx64\arm64\cl.exe   /TP  -external:ID:\installed\arm64-uwp\include -external:W0 /DWIN32 /D_WINDOWS /D_UNICODE /DUNICODE /DWINAPI_FAMILY=WINAPI_FAMILY_APP /D__WRL_NO_DEFAULT_LIB__ /nologo /Z7 /MP /GS /Gd /Gm- /W3 /WX- /Zc:wchar_t /Zc:inline /Zc:forScope /fp:precise /Oy- /EHsc  /utf-8  /MDd /Od /RTC1  -MDd -MP -GR- -GF -Zc:__cplusplus -Zc:inline -Zc:strictStrings -Zc:threadSafeInit- -W4 -Zc:arm64-aliased-neon-types- -GS /showIncludes /FoCMakeFiles\blend2d.dir\src\blend2d\object.cpp.obj /FdCMakeFiles\blend2d.dir\ /FS -c D:\b\blend2d\src\fc85f14251-f50748665f.clean\src\blend2d\object.cpp
FAILED: CMakeFiles/blend2d.dir/src/blend2d/object.cpp.obj
```

Drive-by fix: Remove blitz:x64-uwp=fail because it supports !uwp

https://dev.azure.com/vcpkg/public/_build/results?buildId=120022&view=results suggests that this month's updates may fix several of these.

### CODE REVIEW

**Review by davidmrdavid — APPROVED** [review]
LGTM. Approving as it seems like a routine baseline-updating PR :-) . Though I probably don't have the permissions to unblock you

File: scripts/ci.baseline.txt [hunk 1]
```diff
@@ -135,6 +135,9 @@ openblas:x64-windows-static-md=pass
 openblas:x64-windows-static=pass
 # </BLAS+LAPACK>
 ################################################################
+blend2d:arm64-uwp=fail
+blend2d:arm64-window=fail
```
Comment (BillyONeal) [inline scripts/ci.baseline.txt]:
```suggestion
blend2d:arm64-windows=fail
```

File: scripts/ci.feature.baseline.txt [hunk 2]
```diff
@@ -61,9 +61,10 @@ armadillo:arm-neon-android=cascade
 armadillo:arm64-android=cascade
 armadillo:x64-android=cascade
 bit7z(uwp)=cascade
-blitz:arm-uwp=fail
+blend2d:arm64-uwp=fail
+blend2d:arm64-window=fail
```
Comment (BillyONeal) [inline scripts/ci.feature.baseline.txt]:
```suggestion
blend2d:arm64-windows=fail
```

**Review by vicroms — APPROVED** [review]
