### ISSUE TITLE
[ixwebsocket] build failure on mingw static

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#30181]
**Host Environment**

- OS: linux ubuntu 22.04
- Compiler: gcc 11.3

**To Reproduce**

`./vcpkg install ixwebsocket[core,openssl] --triplet x64-mingw-static`

**Failure logs**

```
Building ixwebsocket[core,openssl]:x64-mingw-static...
-- [OVERLAY] Loading triplet configuration from: /home/runner/work/boinc/boinc/3rdParty/vcpkg_ports/triplets/ci/x64-mingw-static.cmake
-- Downloading https://github.com/machinezone/IXWebSocket/archive/v11.4.3.tar.gz -> machinezone-IXWebSocket-v11.4.3.tar.gz...
-- Extracting source /home/runner/work/boinc/boinc/3rdParty/mingw/vcpkg/downloads/machinezone-IXWebSocket-v11.4.3.tar.gz
-- Using source at /home/runner/work/boinc/boinc/3rdParty/mingw/vcpkg/buildtrees/ixwebsocket/src/v11.4.3-4145a001aa.clean
-- Configuring x64-mingw-static
-- Building x64-mingw-static-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /usr/local/bin/cmake --build . --config Release --target install -- -v -j3
    Working Directory: /home/runner/work/boinc/boinc/3rdParty/mingw/vcpkg/buildtrees/ixwebsocket/x64-mingw-static-rel
    See logs for more information:
      /home/runner/work/boinc/boinc/3rdParty/mingw/vcpkg/buildtrees/ixwebsocket/install-x64-mingw-static-rel-out.log

Call Stack (most recent call first):
  /home/runner/work/boinc/boinc/build/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  /home/runner/work/boinc/boinc/build/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/ixwebsocket/portfile.cmake:30 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)
```

```
/home/runner/work/boinc/boinc/3rdParty/mingw/vcpkg/buildtrees/ixwebsocket/src/v11.4.3-4145a001aa.clean/ixwebsocket/IXDNSLookup.h:60:14: error: ‘mutex’ in namespace ‘std’ does not name a type
```

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

[logs.zip](https://github.com/microsoft/vcpkg/files/10969911/logs.zip)

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by dg0yt** [comment]
Builds with gcc 7.3 (mingw on Ubuntu 18.04). Builds with gcc 11 (msys2 on Windows).

Check your mingw toolchain. AFAICT you need the "posix" variant. The "win32" variant doesn't support C++11 multithreading features.
https://stackoverflow.com/questions/17242516/mingw-w64-threads-posix-vs-win32

**Comment by talregev** [comment]
This gcc come with GitHub action Linux Ubuntu 22.04
How I set gcc to be "posix" variant?

**Comment by dg0yt** [comment]
Is this a vcpkg question? Did you even try to research yourself?

**Comment by talregev** [comment]
I didn't know I cannot ask you questions to understand.

**Comment by dg0yt** [comment]
I just ask for fair usage of my free time. I tried to put enough information into https://github.com/microsoft/vcpkg/issues/30181#issuecomment-1469451071 to guide your next steps. You posted a new question within four minutes, with no relation to vpckg.

**Comment by talregev** [comment]
I appreciate your knowledge and  your free time.
Don't be toxic if you don't think it relevant or I need to search it for my self.
I am free to ask relevant and not relevant questions in here. 
It the same to write me "RTFM" and it not acceptable in vcpkg community.

**Comment by talregev** [comment]
I try to add cxxflags:
```
export CXXFLAGS="-pthread --enable-threads=posix"
export CMAKE_CXXFLAGS="-pthread --enable-threads=posix"
```

Can I set gcc to be in posix mode, or I must install different gcc?

**Comment by dg0yt** [comment]
As I tried to express by the terms "toolchain variant", it is a "different gcc", not different flags.

**Comment by talregev** [comment]
> As I tried to express by the terms "toolchain variant", it is a "different gcc", not different flags.

When you write different gcc, it more clear. Thank you!

**Comment by talregev** [comment]
It wasn't easy to find, but after some search, I understand how to setup the mingw posix:
See the variant of mingw you have:
```
sudo update-alternatives --list x86_64-w64-mingw32-gcc
sudo update-alternatives --list x86_64-w64-mingw32-g++
```
Then set the posix:

```
sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
```

Thanks in advance.
