### ISSUE TITLE
[boost-atomic] build failure

### ISSUE THREAD

**Issue by GiantDeveloper021** [microsoft/vcpkg#21353]
**Host Environment**
- OS: [Windows]

**To Reproduce**
.\vcpkg install pcl:x64-windows

**Failure logs** 
C:\vcpkg> .\vcpkg install pcl:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * boost-asio[core]:x64-windows -> 1.77.0
  * boost-atomic[core]:x64-windows -> 1.77.0
  * boost-bimap[core]:x64-windows -> 1.77.0
  * boost-circular-buffer[core]:x64-windows -> 1.77.0
  * boost-coroutine[core]:x64-windows -> 1.77.0
  * boost-date-time[core]:x64-windows -> 1.77.0
  * boost-dynamic-bitset[core]:x64-windows -> 1.77.0
  * boost-endian[core]:x64-windows -> 1.77.0
  * boost-filesystem[core]:x64-windows -> 1.77.0
  * boost-foreach[core]:x64-windows -> 1.77.0
  * boost-format[core]:x64-windows -> 1.77.0
  * boost-functional[core]:x64-windows -> 1.77.0
  * boost-graph[core]:x64-windows -> 1.77.0
  * boost-interprocess[core]:x64-windows -> 1.77.0
  * boost-iostreams[bzip2,core,lzma,zlib,zstd]:x64-windows -> 1.77.0#1
  * boost-lambda[core]:x64-windows -> 1.77.0
  * boost-lexical-cast[core]:x64-windows -> 1.77.0
  * boost-math[core]:x64-windows -> 1.77.0
  * boost-multi-array[core]:x64-windows -> 1.77.0
  * boost-multi-index[core]:x64-windows -> 1.77.0
  * boost-numeric-conversion[core]:x64-windows -> 1.77.0
  * boost-parameter[core]:x64-windows -> 1.77.0
  * boost-phoenix[core]:x64-windows -> 1.77.0
  * boost-property-map[core]:x64-windows -> 1.77.0
  * boost-property-tree[core]:x64-windows -> 1.77.0
  * boost-proto[core]:x64-windows -> 1.77.0
  * boost-ptr-container[core]:x64-windows -> 1.77.0
  * boost-random[core]:x64-windows -> 1.77.0
  * boost-serialization[core]:x64-windows -> 1.77.0
  * boost-signals2[core]:x64-windows -> 1.77.0
  * boost-sort[core]:x64-windows -> 1.77.0
  * boost-spirit[core]:x64-windows -> 1.77.0
  * boost-thread[core]:x64-windows -> 1.77.0
  * boost-tokenizer[core]:x64-windows -> 1.77.0
  * boost-tti[core]:x64-windows -> 1.77.0
  * boost-uuid[core]:x64-windows -> 1.77.0
  * boost-variant[core]:x64-windows -> 1.77.0
  * boost-xpressive[core]:x64-windows -> 1.77.0
  * bzip2[core]:x64-windows -> 1.0.8#2
  * eigen3[core]:x64-windows -> 3.3.9#1
  * flann[core]:x64-windows -> 2019-04-07#3
  * liblzma[core]:x64-windows -> 5.2.5#4
  * libpng[core]:x64-windows -> 1.6.37#15
  * lz4[core]:x64-windows -> 1.9.3#3
  * openssl[core]:x64-windows -> 1.1.1l#3
    pcl[core]:x64-windows -> 1.12.0
  * qhull[core]:x64-windows -> 8.0.2#2
  * vcpkg-cmake-config[core]:x64-windows -> 2021-09-27
  * zlib[core]:x64-windows -> 1.2.11#13
  * zstd[core]:x64-windows -> 1.5.0#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\Haris\AppData\Local\vcpkg\archives in 8.533 ms. Use --debug to see more details.
Starting package 1/50: boost-atomic:x64-windows
Building package boost-atomic[core]:x64-windows...
-- Using cached boostorg-atomic-boost-1.77.0.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/boost-atomic/src/ost-1.77.0-89304db709.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/boostorg-atomic-boost-1.77.0.tar.gz
-- Using source at C:/vcpkg/buildtrees/boost-atomic/src/ost-1.77.0-89304db709.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/vcpkg/buildtrees/boost-atomic/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\boost-atomic\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:105 (vcpkg_cmake_install)
  ports/boost-atomic/portfile.cmake:23 (boost_modular_build)
  scripts/ports.cmake:142 (include)

Error: Building package boost-atomic:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: boost-atomic[core]:x64-windows -> 1.77.0
  vcpkg version: 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42
  vcpkg-tool version: Failed to get HEAD: fatal: not a git repository: 'C:\vcpkg\.git'

Additionally, attach any relevant sections from the log files above.

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/7528068/config-x64-windows-out.log)

I want to install PCL library. Please help!

**Comment by yurybura** [comment]
@GiantDeveloper021 Please attach C:\vcpkg\buildtrees\boost-atomic\install-x64-windows-dbg-out.log

**Comment by GiantDeveloper021** [comment]
Sure.

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7531605/install-x64-windows-dbg-out.log)

**Comment by yurybura** [comment]
@GiantDeveloper021 Looks like you compile with VS2015 (MSVC 19.0). One intrinsic hasn't been found: `x86_vector_tools.hpp(36): error C3861: '_mm_set1_epi64x': identifier not found`
Could you try to build with VS2017 or later?

**Comment by GiantDeveloper021** [comment]
@yurybura Thanks for replying. Yes i am compiling it with VS2015 because i am using librealsense library (https://github.com/IntelRealSense/librealsense/tree/legacy). If you check the link and goto compatibile platform section the library was tested on windows 10 with Visual Studio 2015 update 2 due to that i didn't compile this library with Visual Studio higher than 2015 but going to try it on VS2017.

**Comment by Kojoley** [comment]
>  Visual Studio 2015 update 2

I guess the intrinsic is available only since Update 3, you should be able to safely upgrade to Update 3. If you could find  `_mm_set1_epi64x`  in compiler headers report that to https://github.com/boostorg/atomic/issues/52.

**Comment by GiantDeveloper021** [comment]
Sorry for replying late. @Kojoley i installed VS2017 and it fixed my issue. Thanks alot @yurybura !
