### ISSUE TITLE
[physx] Build error ,Physx arm64

### ISSUE THREAD

**Issue by Nanoatic** [microsoft/vcpkg#22860]
**Host Environment**
- OS: Widows 10 Pro , 10.0.19043
- Compiler:  ndk 22.0.7026061

**To Reproduce**
`./vcpkg install physx:arm64-android-mixed`

**Failure logs** 

```
In file included from B:/Packaging/vcpkg/buildtrees/physx/src/be49a99479-2db4990732.clean/physx/source/foundation/include/unix/PsUnixInlineAoS.h:40:
B:/Packaging/vcpkg/buildtrees/physx/src/be49a99479-2db4990732.clean/physx/source/foundation/include/unix/neon/PsUnixNeonInlineAoS.h:3582:10: error: argument value 2 is outside the valid range [0, 1]
                return vdupq_lane_f32(vget_low_f32(a), index);
                       ^                               ~~~~~
D:\Android-SDK\ndk\22.0.7026061\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\11.0.5\include\arm_neon.h:5926:14: note: expanded from macro 'vdupq_lane_f32'
  __ret_18 = splatq_lane_f32(__s0_18, __p1_18); \
             ^                        ~~~~~~~
D:\Android-SDK\ndk\22.0.7026061\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\11.0.5\include\arm_neon.h:734:25: note: expanded from macro 'splatq_lane_f32'
  __ret = (float32x4_t) __builtin_neon_splatq_lane_v((int8x8_t)__s0, __p1, 9); \
                        ^                                            ~~~~
B:/Packaging/vcpkg/buildtrees/physx/src/be49a99479-2db4990732.clean/physx/source/geomutils/src/mesh/GuRTreeQueries.cpp:106:18: note: in instantiation of function template specialization 'physx::shdfnd::aos::V4SplatElement<2>' requested here
        Vec4V nqMinz4 = V4SplatElement<2>(nqMin);
                        ^
1 warning and 1 error generated.
```

**Package**
 package: physx[core]:arm64-android-mixed -> 4.1.2#1
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 6ba505cf2 2022-01-28 (2 days ago)

**Comment by Nanoatic** [comment]
works fine with NDK 21.1.6352462
